Repository corona-warn-app/cwa-app-ios, pull requests merged in 2020-07, with the labels that each got.

#827 Update changelog
  CHANGELOG.md
Labels: admin

#829 Updated [TR] html content to Turkish translations
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
Labels: feature

#830 Next dev release
  CHANGELOG.md
  README.md
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Onboarding_Risikoerekennung_Off.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Onboarding_Risikoerekennung_Off.imageset/Illu_Onboarding_Risikoerekennung_Off-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Onboarding_Risikoerekennung_Off.imageset/Illu_Onboarding_Risikoerekennung_Off.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Models/Onboarding/OnboardingInfo.swift
  src/xcode/ENA/ENA/Source/Models/Settings/NotificationSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewControllerUtils.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
  src/xcode/Gemfile.lock
Labels: admin

#832 Update turkish translation
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: enhancement

#841 Fixed number of active days
  src/xcode/ENA/ENA/Source/Workers/TracingStatusHistory.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/TracingStatusHistoryTests.swift
Labels: bug

#843 Exposure Submission Flow - Error Alert adjustments
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Alert.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/UIViewcontroller+AlertTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionTanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionViewUtils.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#822 Updating of home cells
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
Labels: bug

#849 fixes wrong days with tracing info on home screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/RiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Workers/ActiveTracing.swift
  src/xcode/ENA/ENA/Source/Workers/TracingStatusHistory.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/ActiveTracingTests.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/TracingStatusHistoryTests.swift
Labels: bug

#840 integrate new localized errors for exposurenotification settings
  CHANGELOG.md
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Alert.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/UIViewcontroller+AlertTest.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/WebPageHelper.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: enhancement

#838 ExposureDetectionViewController refresh countdown
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/View Helpers/CountdownTimer.swift
  src/xcode/ENA/ENA/Source/View Helpers/__tests__/CountdownTimerTests.swift
Labels: enhancement

#869 Fixed wrong implementation of shouldPerformExposureDetection
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/__tests__/RiskProvidingConfigurationTests.swift
Labels: bug

#868 Risk Calculation Errors - Alert Refinement
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/Error+FAQUrl.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#825 Fix blank Data Privacy page after 5 minutes without user interaction
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
Labels: bug

#824 Reschedule bgtasks
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
Labels: enhancement

#874 Home Screen Risk Cell Update on App start + Risk Calc Refinements
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/Models/States/HomeInteractor+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
Labels: enhancement

#866 Add home screen risk cell update button countdown
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeRiskLevelCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/CountdownTimer.swift
  src/xcode/ENA/ENA/Source/View Helpers/__tests__/CountdownTimerTests.swift
Labels: enhancement

#875 Remove backend urls from settings
  scripts/switch_to_dev_env.sh
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/Helper/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
Labels: chore

#879 Fix text on risk detail page
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
Labels: bug

#882 Add basic tests for getTestResult()
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
Labels: tests

#859 [Bug] Make configurators hashable
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Home/HomeActivateCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeInfoCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeFindingPositiveRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeInactiveRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeRiskLevelCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeThankYouRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeHighRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeLowRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskLevelCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeUnknownRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeTestResultCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeTestResultLoadingCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Protocols/CollectionViewCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
Labels: enhancement

#877 [fix] integrate russian and arabic EULA and privacy notice
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/usage.html
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
Labels: feature

#904 Make activate cell support voice over
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/ActivateCollectionViewCell.swift
Labels: bug

#883 Background Fetching Disabled alert
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Alert.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/UIViewcontroller+AlertTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: enhancement

#873 Loading state for risk cell
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeHighRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeLowRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewControllerDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskConsumer.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskLevelCollectionViewCell.swift
Labels: feature

#884 Display underline in ENATanInput when character is invalid
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENATanInput.swift
Labels: bug

#913 Exposure detection information i18n
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureNotificationSetting.storyboard
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/TracingHistoryTableViewCell.swift
Labels: bug

#833 Add interactivity to links in App Settings Imprint (Legal) Screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTypeTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerFooterTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerHeaderTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerRegisterCellsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewTextViewCellTests.swift
Labels: feature

#919 Force tan input field to be ordered left-to-right even for RTL languages
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENATanInput.swift
Labels: enhancement

#925 Fix the active days in Turkish(JIRA-1803)
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug

#928 1.1.1
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureNotificationSetting.storyboard
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController+HowRiskDetectionWorks.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/TracingHistoryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Workers/ActiveTracing.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/ActiveTracingTests.swift
Labels: admin

#923 Make risk encounter detail text show amount of days since last exposure
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/MockExposureDetectionViewControllerDelegate.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#831 Submission service tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/ENTemporaryExposureKey+Processing.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ENTemporaryExposureKey+ProcessingTests.swift
  src/xcode/ENA/ENA/Source/Models/Converting Keys/__tests__/ConvertingKeysTests.swift
  src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENATests/Helper/TemporaryExposureKeyMock.swift
Labels: tests

#750 Add unit tests for ExposureDetectionExecutor
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENATests/Helper/MockExposureDetector.swift
  src/xcode/ENA/ENATests/Helper/SAPDownloadedPackage+Helpers.swift
  src/xcode/ENA/ENATests/Helper/SAPDownloadedPackagesStore+Helpers.swift
Labels: tests

#926 Fix AppNavigationController navigation bar transparency
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
Labels: bug

#931 Translation updates
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: enhancement

#935 Bring back lost translation keys
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug

#930 Certificate pinning for download server
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CoronaWarnURLSessionDelegateTests.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: feature, on hold

#938 Improve background task scheduling
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
Labels: enhancement

#940 Update dev release 1.2.0
  .circleci/config.yml
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CoronaWarnURLSessionDelegateTests.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/Gemfile.lock
Labels: admin

#939 Fix automated screenshots
  src/xcode/ENA/ENA/Source/Workers/TracingStatusHistory.swift
  src/xcode/fastlane/Snapfile
  src/xcode/fastlane/SnapshotHelper.swift
Labels: admin

#951 fixed pinning for distribution endpoint
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/HostWhitelist.plist
  src/xcode/ENA/ENA/Resources/PublicKeys.plist
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CoronaWarnURLSessionDelegateTests.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: bug

#953 Fix/pinning develop
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/HostWhitelist.plist
  src/xcode/ENA/ENA/Resources/PublicKeys.plist
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CoronaWarnURLSessionDelegateTests.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: bug

#834 Introduce Coordinator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/__tests__/CoordinatorTests.swift
Labels: enhancement

#961 Translation updates relevant for RC-1.2.0
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: feature

#907 48h Unknown card for new risk level
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeInactiveRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeRiskLevelCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknown48hRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeHighRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskLevelCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeUnknown48hRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement, feature

#959 Translation Update for keys introduced by hotfixes
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: feature

#964 App Config Protobuf Changes (closes #862)
  proto/resources/app_config.proto
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/gen/output/app_config.pb.swift
Labels: bug, low priority

#944 Add long text reference support for links, phone and email
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Workers/LinkHelper.swift
Labels: enhancement

#966 Risk calculation manually - after 2 days inactivity update not easy to find - the state switching logic
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
Labels: feature

#968 Increase the robustness of the exposure submission http client
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: enhancement

#945 Unknown Outdated Risk Detail Screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
Labels: feature
