Repository corona-warn-app/cwa-app-ios, pull requests merged in 2020-06, with the labels that each got.

#94 [Bug] Hide Navigation Bar on Initial Onboarding Screen (closes #98)
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: UI polish

#117 [Feature] home different cards sample
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Home/HomeActivateCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeExposureSubmissionStateCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeInfoCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/group/HomeRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeSubmitCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Protocols/CollectionViewCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeLayout.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/HomeTestResultCell.swift
Labels: enhancement

#53 [Feature] Improved Reachability / Internet-Connection check
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Reachability+ObserverDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ENStateTests.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/Mocks/MockReachabilityService.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/Mocks/MockStateHandlerObserverDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENStateHandler.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/ReachabilityService/ConnectivityReachabilityService.swift
  src/xcode/ENA/ENA/Source/Services/ReachabilityService/ReachabilityService.swift
Labels: on hold

#299 [Technical] Verify SAP_ApplicationConfiguration Signature
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/de-config
  src/xcode/ENA/ENA/Resources/PublicKeys.plist
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/SAPDownloadedPackage.swift
  src/xcode/ENA/ENA/Source/Workers/PublicKeyStore.swift
Labels: on hold

#301 [Technical] Public Key Pinning for HTTPClient
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/HostWhitelist.plist
  src/xcode/ENA/ENA/Resources/PublicKeys.plist
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CoronaWarnURLSessionDelegateTests.swift
  src/xcode/ENA/ENA/Source/Extensions/Bundle+ReadPlist.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: on hold

#362 Automate legal notices
  THIRD-PARTY-NOTICES
  licenses.json
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/actions/update_third_party_notice.rb
Labels: on hold

#392 [Feature] Risk calculation store
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeInactiveRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store.swift
Labels: bug, enhancement

#365 [Bug] + [Tests] Fix for SAPDownloadedPackage Signature Verification
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/SAPDownloadedPackage.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/SAPDownloadedPackageTests.swift
Labels: on hold

#487 Disable QR code scanning for RELEASE builds
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
Labels: GoLive

#484 Remove Developer Menu from RELEASE builds
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
Labels: GoLive, on hold

#537 fixed keychain issue
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Workers/Keychain/CFDictionary+KeychainQuery.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/__tests__/CFDictionary+KeychainQueryTests.swift
  src/xcode/ENA/ENA/Source/Workers/KeychainHelper.swift
Labels: on hold

#551 [Bug] Exp. Detection error: Nilling out summary (EXPOSUREAPP-1509)
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: on hold

#595 Retire "Details" Button in ErrorPrompt
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
Labels: on hold

#597 store is now pruned
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesInMemoryStore.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesSQLLiteStore.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesStore.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/KeyPackagesStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift
Labels: on hold

#729 [Admin] Automate release notes
  .grenrc.js
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#745 EXPOSUREAPP-1531 Sharing function is missing explanation text
  src/xcode/ENA/ENA/Source/Scenes/FriendsInvite/FriendsInviteController.swift
Labels: bug

#752 [Feature] ENAButton accessibility
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureDetection.storyboard
  src/xcode/ENA/ENA/Source/Scenes/FriendsInvite/FriendsInviteController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/ResetViewController.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENACloneButton.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/HomeTestResultCollectionViewCell.xib
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskLevelCollectionViewCell.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskLevelCollectionViewCell.xib
Labels: feature

#751 [Bug] Remove invite friends footer translucency
  src/xcode/ENA/ENA/Resources/Storyboards/InviteFriends.storyboard
Labels: bug

#728 [Chore] Split background tasks on develop branch
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
Labels: chore

#753 [Feature] ENAButton activity indicator for submission flow
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionTanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationControllerWithFooter.swift
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationFooterItem.swift
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationFooterView.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
Labels: feature

#779 [Bug] Nutzung Chapter 7 link (de) updated
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: bug

#768 Build for TestFlight from public CI
  .circleci/config.yml
  README.md
  scripts/switch_to_dev_env.sh
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/fastlane/.env.TestFlight
  src/xcode/fastlane/Deliverfile
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Matchfile
  src/xcode/fastlane/README.md
Labels: admin

#746 Fixed deadlock when clicking on risk cell (closes #747)
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#725 [bug] Mitteilungen - image not focusable with voice over (closes 1427)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Settings/NotificationSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#807 Fix pruning of tracing history
  src/xcode/ENA/ENA/Source/Workers/TracingStatusHistory.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/TracingStatusHistoryTests.swift
Labels: bug

#809 Version bump for hotfix release
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin
