Repository corona-warn-app/cwa-app-ios, pull requests merged in 2020-09, with the labels that each got.

#1081 fixed cancellation bug
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/CancellationToken.swift
  src/xcode/ENA/ENA/Source/Models/__tests__/CancellationTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#1105 removed property from AppDelegate that never gets written to
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate+PlausibleDeniability.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
Labels: chore

#1102 Update QR code scan & test removal texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1101 made public keys a compile time setting/constant
  COMPILATION_CONDITIONS.md
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/PublicKeys.plist
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/SAPDownloadedPackage.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/SAPDownloadedPackageTests.swift
  src/xcode/ENA/ENA/Source/Workers/PublicKeyStore.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/PublicKeyProviderTests.swift
Labels: chore

#1114 remove fatalError in ENStateHandler
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENStateHandler.swift
Labels: bug

#1093 Update of EULAs – Jira #1781
  NOTICE
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/usage.html
Labels: bug

#1111 Fix storyboard warnings
  src/xcode/ENA/ENA/Resources/Storyboards/Home.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/Settings.storyboard
Labels: chore

#1104 Add package database support for country column (Interop)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migration/Migration.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migration/Migrations/Migration0To1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migration/SerialMigrator.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V0/DownloadedPackagesSQLLiteStoreV0.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V0/DownloadedPackagesStoreV0.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesSQLLiteStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Migration/0To1/Migration0To1Tests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/SerialMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENATests/Helper/SAPDownloadedPackagesStore+Helpers.swift
  src/xcode/ENA/ENATests/Helper/SerialMigratorFake.swift
Labels: feature

#1133 Require confirmation when submission is canceled
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/RequiresDismissConfirmation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#1135 Low risk encounter explanations text update
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: enhancement

#1134 Show Alert when AppConfig could not be loaded during RiskCalculation
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: To Be Reviewed, bug

#1130 bugfix/resolve missing advice text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1132 Words wrap around correctly in Test Result Screen on small devices [EXPOSUREAPP-2125]
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.xib
Labels: bug

#1129 Improve loading of packages to avoid memory overload crash
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V0/DownloadedPackagesStoreV0.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/AppleFilesWriter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/AppleFilesWriterTests.swift
Labels: enhancement

#1146 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: enhancement

#1158 Handle 'corrupted' database key
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/__tests__/KeychainHelperTests.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/SQLiteKeyValueStoreTests.swift
  src/xcode/ENA/ENAUITests/UITestingParameters.swift
Labels: bug

#1160 introduce new DynamicCell style link
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
Labels: bug

#1088 implementing combined registration/test-result behavior
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionOverviewViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
Labels: bug

#1169 Bugfix: smallest text change ever
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: bug

#1137 Apply minimum risk score values from configuration
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#1170 Onset of Symptoms
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Source/Extensions/Calendar+GregorianLocale.swift
  src/xcode/ENA/ENA/Source/Extensions/ENTemporaryExposureKey+Processing.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ENTemporaryExposureKey+ProcessingTests.swift
  src/xcode/ENA/ENA/Source/Models/SymptomsOnset.swift
  src/xcode/ENA/ENA/Source/Models/__tests__/SymptomsOnsetTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewBulletPointCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/__tests__/ExposureSubmissionSymptomsOnsetViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/__tests__/ExposureSubmissionSymptomsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Custom/ExposureSubmissionDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerDay.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerDayView.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerDayViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerOptionView.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerOptionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/__tests__/DatePickerDayViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/__tests__/DatePickerOptionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/OptionGroupView.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/OptionGroupViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.xib
Labels: feature

#1177 [Bugfix] Bug/update text2662
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1175 Change ENDeveloperRegion in Debug and Testflight
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
Labels: admin

#1171 Remove outdated RKI number from Terms of Use
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: enhancement

#1162 Country key package download and risk detection (INTEROP 1660-2510)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ExposureConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/CountryKeypackageDownloader.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Models/EUTracingSettings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1172 QR code validation improvements
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionOverviewViewControllerTests.swift
Labels: enhancement

#1182 Release version 1.3.1
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Storyboards/Home.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/Settings.storyboard
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENStateHandler.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: admin

#1149 EXPOSUREAPP-2491 Error Code 400 now has a better wording
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1184 Fix: Make symptom options selectable on iOS 14
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewOptionGroupCell.swift
Labels: bug

#1173 Adjust wrong TAN error messages
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTanInputViewControllerTests.swift
Labels: enhancement

#1185 Update unit test
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnEuropeTravelConfirmationViewControllerTests.swift
Labels: bug

#1186 Update error message for invalid TANs
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1190 Admin/trigger ci rcbuild via tags
  .circleci/config.yml
Labels: admin

#1187 Update CI to Xcode 12
  .circleci/config.yml
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Snapfile
Labels: admin

#1200 Remove INTEROP switches for exposure detection.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+AppConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Migration/0To1/Migration0To1Tests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENATests/Helper/SAPDownloadedPackagesStore+Helpers.swift
  src/xcode/gen/output/app_config.pb.swift
  src/xcode/gen/output/app_config_V0.pb.swift
Labels: chore

#1202 Set deployment Target to 13.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: chore

#1196 Change link to turkish FAQ website. (2515)
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug

#1204 Fix missing character in error text (2549/2768)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1194 EXPOSUREAPP-2547: Countdown stopped working when resuming app from ba…
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
Labels: bug

#1211 Fix behaviour on key upload
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#1201 remove arabic and russian language files from versioning
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/usage.html
Labels: chore

#1205 Country key download and exposure detection (Interop – 2667, 2764)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+AppConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ExposureConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesSQLLiteStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/CountryKeypackageDownloader.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Models/TracingStatusHistory.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: feature

#1203 Tess relay for technical hotline (2554)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#1214 Add german einwilligung texts for onset of symptoms. (2778)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: enhancement

#1216 Data privacy note EN/DE updated. Terms of use (DE): replaced "Handy" …
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: bug

#1180 updated Fastlane
  src/xcode/Gemfile.lock
Labels: admin

#1219 new text for data privacy note TR
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug

#1224 Removed RKI Phone Number
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
Labels: bug

#1229 added new ua codeowner
  CODEOWNERS
Labels: admin

#1225 Feature/2668 new interop submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewSection.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerRowsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeCountrySelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeTravelConfirmationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSymptomsOnsetViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSymptomsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnEuropeConsentViewControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnEuropeCountrySelectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnEuropeTravelConfirmationViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1223 Feature/2711 eusettings ui
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability - Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1231 New legal texts (Onset of Symptoms) – Text Strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1218 Textual Enhancement in Context of "Gesundheitsamt" (2577)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: enhancement

#1237 Move submission consent to new Localizable.legal.strings file
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore

#1238 Encounter with low risk: Wrong text in risk details
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
Labels: bug

#1244 Replace header asset in submission for interoperability
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_AndereWarnen.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_AndereWarnen.imageset/Illu_Submission_AndereWarnen-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_AndereWarnen.imageset/Illu_Submission_AndereWarnen.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_AndereWarnen.imageset/Illustration - Submission EU Interoperability - Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_AndereWarnen.imageset/Illustration - Submission EU Interoperability.pdf
Labels: UX

#1243 Feature/1856 prepare 15th key
  src/xcode/ENA/ENA/Source/Extensions/ENTemporaryExposureKey+Processing.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ENTemporaryExposureKey+ProcessingTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
Labels: feature

#1228 exchange text according to JIRA 2716
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: enhancement

#1250 Update privacy-policy.html (ESPOSUREAPP-2777)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: bug

#1226 Delta onboarding logic (2665 - 2761)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Extensions/Bundle+Version.swift
  src/xcode/ENA/ENA/Source/Extensions/String+Compare.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15ViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/AppUpdateCheckHelper.swift
Labels: feature

#1251 Update privacy-policy.html (EXPOSUREAPP-2777)
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: enhancement

#1230 Fix misleading EN Settings (2841)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ENStateTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeActivateCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/States/ENStateHandler+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENStateHandler.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ActionDetailTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ActionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ImageTableViewCell.swift
Labels: bug

#1255 Fix legal texts UI (2805 - 2851)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1242 EUSettings - Empty List (2881 - 2557)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Wifi.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Wifi.imageset/Icon_Wifi.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewRoundedCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeCountrySelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1256 Update privacy-policy.html in Turkish - device to smartphone (EXPOSUREAPP-2777)
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug

#1253 Fix repeated onboarding elements (2862)
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#1262 exclude legal files from translation
  translation_v2.json
Labels: chore

#1263 Update Fastlane: 2.159.0 -> 2.161.0
  src/xcode/Gemfile.lock
Labels: chore

#1264 Set Export Compliance to No
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
Labels: chore

#1260 [chore] Refactoring: extract the legal text of 2716 to legal.strings file
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore

#1254 Separate activity indicators for download and risk detection (2350)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeRiskLevelCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknown48hRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeHighRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeLowRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskLevelCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeUnknown48hRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeUnknownRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskViewConfigurators/HomeRiskLoadingItemViewConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskConsumer.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/__tests__/CoordinatorTests.swift
Labels: feature

#1252 Submit days since onset of symptoms (2432)
  proto/resources/temporary_exposure_key_export.proto
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Extensions/ENTemporaryExposureKey+Processing.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ENTemporaryExposureKey+ProcessingTests.swift
  src/xcode/ENA/ENA/Source/Models/SymptomsOnset.swift
  src/xcode/ENA/ENA/Source/Models/__tests__/SymptomsOnsetTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/gen/output/temporary_exposure_key_export.pb.swift
Labels: feature

#1267 2916 Open Settings instead of FAQ if ExposureNotifications cant be enabled
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: enhancement

#1265 Risk calculation screen with country information (2667)
  COMPILATION_CONDITIONS.md
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Wifi.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Wifi.imageset/Icon_Wifi.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability - Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+AppConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ExposureConfigTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/Country.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewRoundedCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnEuropeCountrySelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsViewController.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesSQLLiteStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/CountryKeypackageDownloader.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Models/TracingStatusHistory.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: feature

#1270 Feature/2762 delta onboarding view
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUWideOnboarding-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUWideOnboarding.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Resources/Storyboards/RiskLegend.storyboard
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15ViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15ViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingViewControllerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1248 Caching App-Config (2790 - 2858)
  proto/resources/app_config.proto
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/Sap_FilebucketTests.swift
  src/xcode/ENA/ENA/Backend/__tests__/de-config-int-2020-09-25
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingClientMock.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSessionConfiguration+Default.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: chore, enhancement

#1266 Interop Onboarding Screen (#2763)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/__tests__/OnboardingInfoViewControllerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature
