Repository corona-warn-app/cwa-app-ios, pull requests merged in 2020-08, with the labels that each got.

#981 fix: pinning is no longer disabled for testing and development
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: bug

#929 brought hourly fetching back
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesStore.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
Labels: bug

#1009 Availability of Tess Relay
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: accessibility

#1024 Support for redeemed test result
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.swift
Labels: feature

#1031 Introduce separate property to enable background fake requests
  src/xcode/ENA/ENA/Source/AppDelegate+PlausibleDeniability.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#970 Remove constant connectivity check
  THIRD-PARTY-NOTICES
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Internet_aus.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Internet_aus.imageset/Icons_Internet_aus-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Internet_aus.imageset/Icons_Internet_aus.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_iOS_Wifi.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_iOS_Wifi.imageset/Icons_iOS_Wifi.pdf
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeActivateCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/States/ENStateHandler+State.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENStateHandler.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Services/ReachabilityService/ConnectivityReachabilityService.swift
  src/xcode/ENA/ENA/Source/Services/ReachabilityService/ReachabilityService.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ActionDetailTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ActionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/ENSetting/ImageTableViewCell.swift
Labels: feature

#1023 Improved dev menu
  sonar-project.properties
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Cells/DMFakeRequestCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMQRCodeScanViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMQRCodeViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBackendConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMErrorsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMKeysViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLastRiskCalculationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLastSubmissionRequetViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMTracingHistoryViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMKeyCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/SAP_TemporaryExposureKey+DeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Workers/Logger.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: chore

#1043 Test result header wraps around (closes 2065 and 2125 )
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.xib
Labels: enhancement

#1038 Link contact form on imprint page
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1044 remove unused strings and keys
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore

#1049 2199 rephrased german hint on problems evaluating test results
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#1036 Dead man notifications
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1058 Feature/leichte sprache
  Icon 
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Source/Models/Onboarding/OnboardingInfo.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: accessibility

#1054 Fixed RiskLevel Comparison
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskLevel.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/RiskLevelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/RiskCalculationTests.swift
Labels: bug

#1066 1.3.0 RC 5
  Icon 
  cfg/VERSION
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Resources/Localization/ar.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ru.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskLevel.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/RiskLevelTests.swift
  src/xcode/ENA/ENA/Source/Models/Onboarding/OnboardingInfo.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/RiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: admin

#1084 Reduce timer rescheduling (JIRA 2302)
  src/xcode/ENA/ENA/Source/Models/DetectionMode.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskLevel.swift
  src/xcode/ENA/ENA/Source/Models/States/ENStateHandler+State.swift
  src/xcode/ENA/ENA/Source/Models/States/HomeInteractor+State.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Workers/ActiveTracing.swift
Labels: bug

#1085 Fix: Grammar error in data privacy (EXPOSUREAPP-2251)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: bug

#1073 [Proposal] handling for local settings and parameters
  .gitignore
  scripts/switch_to_dev_env.sh
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENACommunity.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENAUITests.xcscheme
  src/xcode/ENA/ENA/LocalSettings.default.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/check_localsettings.sh
Labels: chore, component proposal

#1092 Update english EULA – Jira #1781
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
Labels: bug

#1074 Integrate jazzy for GitHub Pages
  .circleci/config.yml
  .gitignore
  README.md
  src/xcode/.jazzy.yaml
  src/xcode/Gemfile
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
Labels: admin

#1099 Support MS App Center distribution for test builds
  .circleci/config.yml
  src/xcode/ENA.plist
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/Gemfile
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Matchfile
  src/xcode/fastlane/Pluginfile
  src/xcode/fastlane/README.md
Labels: admin

#1095 Fix warning during Onboarding
  src/xcode/ENA/ENA/Resources/Storyboards/Onboarding.storyboard
Labels: chore
