Repository corona-warn-app/cwa-app-ios, pull requests merged in 2020-11, with the labels that each got.

#1436 Feature/3533 generate new swiftfiles from proto
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/exposure_detection_parameters.pb.swift
  src/xcode/gen/output/internal/key_download_parameters.pb.swift
Labels: feature

#1426 Feature/3241 check if the user has the correct time
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/URLSession+ConvenienceTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Utils/ENAFormatter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: feature

#1447 PROMOTION
  cfg/VERSION
  proto/resources/internal/app_config.proto
  proto/resources/internal/exposure_detection_parameters.proto
  proto/resources/internal/key_download_parameters.proto
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/URLSession+ConvenienceTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Utils/ENAFormatter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: promotion

#1446 Fix/QR Scanner doesn't accept uppercase GUID URL and extra slash
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
Labels: bug

#1442 Remove Label “Aktualisierung alle 24 Stunden" from riskcards
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeRiskLevelCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknown48hRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeUnknownRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeLowRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskLevelCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskLevelCollectionViewCell.swift
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskLevelCollectionViewCell.xib
Labels: feature

#1445 Chore/fastlane update
  src/xcode/Gemfile.lock
Labels: admin

#1448 Promotion
  .grenrc.js
  cfg/VERSION
  proto/resources/internal/app_config.proto
  proto/resources/internal/exposure_detection_parameters.proto
  proto/resources/internal/key_download_parameters.proto
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/URLSession+ConvenienceTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/Models/SymptomsOnset.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSymptomsOnsetViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionServiceFactory.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Utils/ENAFormatter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/Gemfile.lock
Labels: promotion

#1451 avoid // in QR Code path
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
Labels: bug

#1450 Promotion
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/Gemfile.lock
Labels: promotion

#1449 Translations for warn others feature
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1444 Feature/3505 http retry
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/MockURLSession.swift
Labels: bug

#1455 admin/enable new internal pipeline for continous builds and checks
  .pipeline/Jenkinsfile
  .pipeline/config.yml
  Jenkinsfile
  cfg/VERSION
  cfg/XMAKE_VERSION
  cfg/build.scriptname
  cfg/central-signing/NAASSigning.xcconfig
  cfg/central-signing/NaasSigningExportOptions.plist
  cfg/xcode.cfg
  scripts/adjust_version.sh
  wss-unified-agent.config
Labels: admin

#1459 fix(settings): properly check cell actions (closes #1458)
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureNotificationSetting.storyboard
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: bug

#1460 Lint before test
  src/xcode/fastlane/Fastfile
Labels: admin

#1466 Update usage.html #3251
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: bug

#1467 Promotion
  .pipeline/Jenkinsfile
  .pipeline/config.yml
  Jenkinsfile
  cfg/VERSION
  cfg/XMAKE_VERSION
  cfg/build.scriptname
  cfg/central-signing/NAASSigning.xcconfig
  cfg/central-signing/NaasSigningExportOptions.plist
  cfg/xcode.cfg
  scripts/adjust_version.sh
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureNotificationSetting.storyboard
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/fastlane/Fastfile
  wss-unified-agent.config
Labels: promotion

#1457 Feature/TASK 3483 risk calculation v2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/CWARiskLevel.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/ENARange.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/ExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/MinutesAtAttenuationFilter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/MinutesAtAttenuationWeight.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/NormalizedTimePerEWToRiskLevelMapping.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/RiskCalculationConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/RiskCalculationV2Result.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/ScanInstance.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/TrlEncoding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/TrlFilter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/proto/risk_calculation_parameters.pb.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/RiskCalculationV2.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/RiskCalculationV2Error.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/ENARangeTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/ExposureWindowTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/Models/ExposureWindow+Decodable.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/Models/ExposureWindowTestCase.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/Models/TestCasesWithConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/RiskCalculationV2Test.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/ScanInstanceTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/exposure-windows-risk-calculation.json
Labels: feature

#1454 Fix/3570 retry risk check caching bug (work in progress)
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#1465 Feature/task 3497 download packages
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Extensions/String+Today.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesSQLLiteStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/DownloadedPackagesStoreErrorStub.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/CountryKeypackageDownloader.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/DeltaCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/DeltaCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: task

#1471 Feature/task 3481 update protobuf
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/exposure_detection_parameters.pb.swift
  src/xcode/gen/output/internal/key_download_parameters.pb.swift
  src/xcode/gen/output/internal/v2/app_config_android.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/app_features_v2.pb.swift
  src/xcode/gen/output/internal/v2/exposure_detection_parameters.pb.swift
  src/xcode/gen/output/internal/v2/key_download_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
  src/xcode/gen/output/internal/v2/semantic_version.pb.swift
Labels: feature

#1473 Fix/xcode not found
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Snapfile
Labels: admin

#1462 Fix/3553 missing close icon
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
Labels: bug

#1464 fix(submission): Popping multiple navigation children results results in broken footer state (closes #1463)
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationControllerWithFooter.swift
Labels: bug

#1468 Feature/Task 3583 Download Hour Packages on WiFi Only
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/ClientWifiOnly.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/Helper/HTTPClient+MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSessionConfiguration+Default.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: task

#1472 Feature/task 3582 increase risk calculation cycle
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#1470 Update Localizable.strings #3277
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1478 Update Localizable.strings #3655
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1480 bring wifi client to DM and trigger hour loading on it
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
Labels: task

#1481 Feature/Task 3614 – Unit Tests for Hour Package Cleanup
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: task, tests

#1485 Feature/1567 Fix Invalid Redeclaration
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
Labels: task

#1483 Feature/task 3498 DM for hourly packages wifi mode toggle
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClient.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClinteViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
Labels: task

#1479 Feature/task 3613 fix downloading detecting state
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/String+Today.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/String+TodayTests.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskConsumer.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
  src/xcode/ENA/ENA/Source/Workers/ActiveTracing.swift
Labels: task

#1488 Pipeline enhancement to upload new release candidates to the Mobile Device Cloud
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/fastlane/Fastfile
Labels: admin

#1484 Feature/task 3577 fix alert for no disk space
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/Models/CancellationToken.swift
  src/xcode/ENA/ENA/Source/Models/__tests__/CancellationTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#1489 Feature/task 3667 dm disable hourly packages download
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClient.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/Cell/DMSwitchCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/Cell/DMSwitchTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/Cell/DMSwitchTableViewCell.xib
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClinteViewController.swift
Labels: task

#1491 Fix/3463 re enable test
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: bug

#1486 Feature/3627 invalidate cached files
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/AppConfig+CacheInvalidation.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesStoreV2.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/DownloadedPackagesStoreErrorStub.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
Labels: feature

#1494 Protocol Buffer update for release 1.7.x at Wed Nov 11 08:42:43 UTC 2020
  proto/resources/internal/key_download_parameters.proto
Labels: admin

#1495 Protocol Buffer update for release 1.8.x at Wed Nov 11 08:51:21 UTC 2020
  proto/resources/internal/key_download_parameters.proto
  proto/resources/internal/v2/key_download_parameters.proto
Labels: admin

#1499 Update configuration when appconfig updates.
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderAndNewKeyPackagesTests.swift
Labels: task

#1482 Feature/3298 reminder to share a positive test result
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWarnOthersNotificationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Extensions/UNUserNotificationCenter+WarnOthers.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersNotificationsTimeInterval.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersRemindable.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersReminder.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersReminderTests.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersTests.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSuccessViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1500 updated protobuf files and references in code
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/AppConfig+CacheInvalidation.swift
  src/xcode/gen/output/internal/key_download_parameters.pb.swift
Labels: chore

#1503 feature/3516 translations
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1506 Fix/3711 refactor cached app config
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/AppConfigMetadata.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: bug

#1508 Feature/task 3482 exposure windows
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/Sap_FilebucketTests.swift
  src/xcode/ENA/ENA/Backend/__tests__/config-wru-2020-11-13
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMServerEnvironmentViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/Date+Age.swift
  src/xcode/ENA/ENA/Source/Extensions/ENExposureConfiguration+Convenience.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ExposureManagerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/AppConfig+CacheInvalidation.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/RiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/SAP_RiskScoreClass+LowAndHighTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/Models/RiskCalculationV2Result.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/RiskCalculationV2.swift
  src/xcode/ENA/ENA/Source/Services/Risk/CalculationV2/__test__/RiskCalculationV2Test.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderAndNewKeyPackagesTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/AppUpdateCheckHelper.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/SAP_SemanticVersion+Compare.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/String+SemanticVersion.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/__tests__/AppUpdateCheckerHelperTests.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/__tests__/SAP_SemanticVersionTests.swift
  src/xcode/ENA/ENATests/Helper/MockExposureDetector.swift
  src/xcode/ENA/ENATests/Helper/SAPApplicationConfiguration+Helpers.swift
  src/xcode/gen/output/internal/app_config.pb.swift
Labels: task

#1502 feature/TASK-3762 Consent to share submission data added to the framework
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: task

#1516 Fix/3773 Show unkown risk cell when the risk is not available.
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
Labels: bug

#1510 Fix/dont show allready running alert
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#1519 Fix/3806 no key download between detections
  src/xcode/ENA/ENA/Source/Extensions/String+Today.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
Labels: bug

#1524 Fix/3809 No reminder to share a positive test result if user first register QR code before test result positive
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
Labels: bug

#1526 Feature/3755 translations
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1529 Update Localizable.strings #1996
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1530 Update privacy-policy.html #3512
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#1532 Update privacy-policy.html #3512
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#1538 Admin/ci maintenance
  .circleci/config.yml
  src/xcode/Gemfile.lock
Labels: admin

#1540 Fix SwiftLint install on CI
  .circleci/config.yml
Labels: admin

#1539 Fix/3851 fix sql injection vulnerability
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
Labels: enhancement

#1535 Fix/error handling bg task
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderAndNewKeyPackagesTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: bug

#1541 Feature/3780 exposure window risk calculation v2 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/__tests__/RiskProvidingConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderAndNewKeyPackagesTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/__tests__/CountdownTimerTests.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/SQLiteKeyValueStoreTests.swift
  src/xcode/ENA/ENATests/Helper/TimeInterval+Convenience.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: admin

#1536 fix/Duplicate code lines removed
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: bug

#1537 Update privacy-policy.html #3512
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#1547 added missing translation key
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1545 Update privacy-policy.html #3512
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#1550 Feature/3854 risk calculation v2 ui
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/URLSession+ConvenienceTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeHighRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeLowRiskCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeHighRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeLowRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/__tests__/HomeRiskCellConfiguratorTests.swift
  src/xcode/ENA/ENA/Source/Models/States/ExposureDetectionViewController+State.swift
  src/xcode/ENA/ENA/Source/Models/States/HomeInteractor+State.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/__tests__/DatePickerDayViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/Models/ExposureWindowTestCase.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/RiskCalculationTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/exposure-windows-risk-calculation.json
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/RiskTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1555 Describe origin of public keys
  src/xcode/ENA/ENA/Source/Workers/PublicKeyStore.swift
Labels: admin

#1556 move defer block to the right place
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/__tests__/CountdownTimerTests.swift
Labels: admin

#1558 Fix/3893 show process state on failed cell
  src/xcode/ENA/ENA/Source/Models/Home/HomeRiskCellConfigurator/HomeRiskCellConfigurators/HomeFailedCellConfigurator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#1559 TASK 3756 – New Text For Submit Card & Button
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: task

#1546 Update Localizable.strings [EXPOSUREAPP-3882]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1560 Fix UI freeze: Don't dispatch to main in URLSession
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: bug

#1557 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1568 Update Localizable.strings [EXPOSUREAPP-3887]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1566 Dispatch ui changes to main queue
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: bug

#1571 Call completion instead of failing on target queue
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#1561 Feature/task 3630 testresult available
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Testresult_available.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Testresult_available.imageset/iOS-dark-Ergebnis-liegt-vor-Einverstaendnis_428.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Testresult_available.imageset/iOS-light-Ergebnis-liegt-vor-Einverstaendnis_428.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewHeader.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerHeaderTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionNavigationControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/TestResultAvailableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/TestResultAvailableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1569 fix/3951 – Fetch available data with wificlient.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/ClientWifiOnly.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/Helper/HTTPClient+MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClientTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
Labels: bug

#1570 Update Localizable.strings [EXPOSUREAPP-3830]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1574 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#1572 Update Localizable.legal.strings [EXPOSUREAPP-3513]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#1573 Fix/3902 filter negative seconds since last scan
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/RiskCalculationTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/exposure-windows-risk-calculation.json
Labels: bug

#1562 Feature/3516 user consent switch automatic result sharing
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWarnOthersNotificationViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/Date+Age.swift
  src/xcode/ENA/ENA/Source/Extensions/NSTextAttachment+ImageHeight.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersRemindable.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersReminder.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersReminderTests.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewAction.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewConsentCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewSpaceCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/TestResultAvailableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/UITestingParameters.swift
Labels: feature

#1564 TASK 3761 Changed Illustration on Screen "Vielen Dank"
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_VielenDank.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_VielenDank.imageset/Illu_Submission_VielenDank-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_VielenDank.imageset/Illu_Submission_VielenDank.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_VielenDank.imageset/VielenDank_GemeinsamCoronabekaempfen_Dark_428.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_VielenDank.imageset/VielenDank_GemeinsamCoronabekaempfen_Light_428.pdf
  src/xcode/ENA/ENA/Source/Views/Home Screen/Cells/Risk/RiskThankYouCollectionViewCell.xib
Labels: task

#1565 Feature/3755 acknowledgement screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - FaceID.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - FaceID.imageset/Icon_Einverstaendnis_Test_Scannen_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - FaceID.imageset/Icon_Einverstaendnis_Test_Scannen_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Once.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Once.imageset/Icon_Einverstaendnis_Test_Einmal_Scannen_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Once.imageset/Icon_Einverstaendnis_Test_Einmal_Scannen_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Appinfo_Datenschutz_2.imageset/Appinfo_Datenschutz_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Appinfo_Datenschutz_2.imageset/Appinfo_Datenschutz_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Appinfo_Datenschutz_2.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Extensions/UIStackView+prune.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionQRInfoModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/Common/LabeledCountriesView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicAcknowledgementCell.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicAcknowledgementCell.xib
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/LabeledCountriesCell.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/LabeledCountriesCell.xib
Labels: feature

#1578 Fix/legal strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
Labels: bug

#1576 Fix: Moved submission consent legal texts to localizable legal file
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: admin

#1575 Fix/fix for leave crash
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#1579 Feature/integration with other screens
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/TestResultAvailableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/TestResultAvailableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
Labels: feature

#1583 Feature/3758 test result available cell
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersRemindable.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersReminder.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersReminderTests.swift
  src/xcode/ENA/ENA/Source/Models/Home/HomeTestResultCellConfigurator.swift
  src/xcode/ENA/ENA/Source/SceneDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1580 Task: Added a submission consent switch to the warn others notification DM,…
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWarnOthersNotificationViewController.swift
Labels: task

#1584 Change button title on positive test result cell
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: enhancement

#1586 Feature/3755 handle legal texts
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/NSAttributedString+BulletPoint.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewBulletPointCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionQRInfoModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicAcknowledgementCell.swift
Labels: chore

#1595 Adopt TRL encoding to ENF restrictions (EXPOSUREAPP-4039)
  src/xcode/ENA/ENA/Resources/default_app_config_18
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/exposure-windows-risk-calculation.json
Labels: bug

#1589 Feature/3718 task submission flow add alerts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionNavigationControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSymptomsOnsetViewControllerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1582 Feature/3622 3623 translations
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1598 4014 – Fix crash in HomeInteractor
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeInteractor.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeInteractorTests.swift
Labels: bug

#1591 fix/removed configuration inside exposure windows inside debug menu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDebugRiskCalculationViewController.swift
Labels: chore

#1602 Fix/3790 AppStore Screenshots
  src/xcode/ENA/ENAUITests/ENAUITests.swift
Labels: bug

#1600 Fix/cleanup packages (3959)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/FileManager+KeyPackageStorage.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/AppleFilesWriter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/AppleFilesWriterTests.swift
Labels: bug

#1594 force app config update in onboarding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug
