Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-05, with the labels that each got.

#2603 Replace Countup with Date of Registration
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
Labels: enhancement

#2604 Fixed typo in 'Neue Funktionen' Screen (DE) - Fehlerprotokoll
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2599 fix for two flaky UI Tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_09_TraceLocations.swift
Labels: admin, chore

#2598 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2610 Make whole UA Team Codeowner instead of single people
  CODEOWNERS
Labels: admin

#2608 Rapid Test - FirstName and SecondName are reversed when scanned in PoC Portal
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/Cells/QRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/Cells/__tests__/QRCodeCellViewModelTests.swift
Labels: bug

#2613 Test Reports in Circle CI
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/TestPlans/SmokeTests.xctestplan
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Pluginfile
Labels: chore

#2593 6742 Return certificate representation for fetching of proof certificate.
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HealthCertificateToolkit.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/CertificateRepresentations.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/HealthCertificate.swift
Labels: task

#2611 Feature/6893 get value sets for vaccination certificate
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueDataSets.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueSetsProvider.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueSetsProviding.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/__tests__/VaccinationValueSetsProvidingTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/check_in_export.pb.swift
  src/xcode/gen/output/internal/evreg/event.pb.swift
  src/xcode/gen/output/internal/evreg/poster_template.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
Labels: task

#2609 panel ‘Fehlerberichte‘ button ‘Teilen und fortsetzen‘ with wrong title
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#2619 fix/6989 change in hotline number and disclaimer
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2581 Test result not updated when clicking on "Test anzeigen"
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
Labels: bug

#2615 Refactor snapshots based UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITests_05_DataDonation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITests_04b_ExposureDetection.swift
  src/xcode/ENA/ENAUITests/ExposureLogging/ENAUITests_04c_ExposureLogging.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/Helper/AccessibilityLabels.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_09_TraceLocations.swift
  src/xcode/ENA/ENAUITests/UpdateOS/ENAUITests_08_UpdateOSUITests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: chore

#2621 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2620 Fix/6984 els upload otp issue
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
Labels: bug

#2623 Bump to next Version 2.2.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2614 Missing popup when deleting antigen profile
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2618 Add Missing text
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2624 Stabilize flaky test: test_SubmitTAN_SecondaryFlowWithoutSymptomsScreens()
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: admin, chore

#2626 Contact Journal - Locations - change duration is hidden by the keyboard
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#2627 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2629 Extend trace package download logs
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
Labels: task

#2616 Risk calculation fails after Onboarding and thereby "Risiko-Überprüfung fehlgeschlagen" appears
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
Labels: bug

#2625 remove precondition failures to prevent crashes in the catch block
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/StreamReader.swift
Labels: bug

#2622 Wrong tile on the "Register Test" screen after deleting antigen profile
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionImageCardCell.swift
Labels: bug

#2633 fix forgotten placeholder
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportHistory/ErrorReportHistoryViewModel.swift
Labels: bug

#2630 Feature/6742 vaccination certificate/6940 decoding
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/HealthCertificateToolkit/.swiftpm/xcode/xcshareddata/xcschemes/HealthCertificateToolkit.xcscheme
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/README.md
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HealthCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HealthCertificateToolkit.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/CertificateRepresentations.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/HealthCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/CBOR+AnyMap.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/HealthCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/HealthCertificateToolkitTests.swift
Labels: task

#2638 fix/6989 changes in hotline number and disclaimer
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2636 Feature/5474 flaky tests/test screenshot submission not possible
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: admin, chore

#2640 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#2641 Feature/6747 health certificate service protocol and data models
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/FetchProofCertificateTrigger.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/DigitalGreenCertificate+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationCertificate+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/ProofCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HealthCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateAccess.swift
Labels: feature

#2644 Fix path
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: chore

#2634 Feature/6742 vaccination certificate/6940 json validation
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/HealthCertificateAccessTests.swift
Labels: task

#2639 Feature/5474 flaky tests/more ci tweaks
  .circleci/config.yml
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
  src/xcode/fastlane/Snapfile
Labels: enhancement

#2649 Feature/6747 deletion
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
Labels: task

#2650 Use grouped table view style to prevent headers and footers from floating above the cells
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2645 PCR & Rapid Test - After deleting a test, the risk card is not updated
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#2651 Adapting new privacy notices for 2.2 release
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#2643 fix/6884 removing call button and it's corresponding logic
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionHotlineViewControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionNavigationControllerTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2628 Feature/6454 register vaccination certificates/7077 update qr code verification
  src/xcode/ENA/ENA/Source/Scenes/Vaccination/VaccinationQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Vaccination/__tests__/VaccinationQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: task

#2655 Using same text from RAT for PCR in consent screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2656 fixes for two more flaky tests
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: admin, chore

#2658 Remove space below footer view
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
Labels: bug

#2663 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2661 Fix/6989 wrong number while calling
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug

#2664 Empty space on main screen (uikit buttons)
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
Labels: bug

#2653 Feature/6742 vaccination certificate/6941 proof certificate fetch
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/ProofCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HTTP/HTTPService.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HealthCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateDownload.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/ProofCertificateDownloadTests.swift
Labels: task

#2671 Removing unused UI tests in tests plans which cause flakiness
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: chore

#2669 truncating output of very long logs in developer menu
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogging/DMLogsViewController.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/StreamReader.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/__tests__/StreamReaderTests.swift
Labels: bug

#2675 added strings for the health certificate details
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: feature, text-change

#2665 Feature/6747 health certificate service implementation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/FetchProofCertificateTrigger.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/ProofCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2680 Feature/5474 flaky tests/6877 prevent new flaky tests
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITests_05_DataDonation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITests_04b_ExposureDetection.swift
  src/xcode/ENA/ENAUITests/ExposureLogging/ENAUITests_04c_ExposureLogging.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITestsSettings.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_09_TraceLocations.swift
Labels: admin, chore

#2691 Fix typo "an der Teststelle"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2681 Add protocols to provide better testability.
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateDownload.swift
Labels: task

#2692 Remove proof certificate download from framwork
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
  src/xcode/ENA/HealthCertificateToolkit/README.md
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/HTTP/HTTPService.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/ProofCertificateDownload.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/CBOR+AnyMap.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/ProofCertificateDownloadTests.swift
Labels: task

#2687 Fix/7121 wrong screen flow RAT
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewController.swift
Labels: bug

#2682 Capitalize Adjectives
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, text-change

#2710 Protocol Buffer update for release 2.4.x at Mon May 17 11:32:54 UTC 2021
  proto/resources/internal/ppdd/ppa_data.proto
Labels: admin

#2711 update generated protobuf swift file
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
Labels: admin, chore

#2712 UA Text Change (EXPOSUREAPP-7141)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2702 Antigen test profile creation: Add textContentType to text fields
  src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileInputCell.swift
Labels: community, enhancement

#2709 Activate pinning for wifi only and caching clients.
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: bug

#2713 Feature/6454 register vaccination certificates/xxx legal texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Consent/HealthCertificateConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2714 UA Text Change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2697 Decapitalize "IHR BEFUND" (COMMUNITY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, text-change

#2716 UA Text Change 'bei jeder teilnehmenden Teststelle'
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2701 fix: do not add cell selection for step cells
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewSpaceCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DaysSinceInstallTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.swift
Labels: community, mirrored-to-jira

#2718 Increase timeouts
  .circleci/config.yml
Labels: admin

#2719 tests DO fail build
  src/xcode/fastlane/Fastfile
Labels: admin

#2728 Protocol Buffer update for release 2.4.x at Wed May 19 06:57:59 UTC 2021
  proto/resources/internal/ppdd/ppa_data.proto
  proto/resources/internal/ppdd/tri_state_boolean.proto
Labels: admin

#2727 Fix/@Published timing issues
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Utils/DidSetPublished.swift
  src/xcode/ENA/ENA/Source/Utils/__tests__/DidSetPublishedTests.swift
Labels: bug

#2708 7230 changes vaccination certificate/7260 decoding tests
  src/xcode/ENA/HealthCertificateToolkit/.swiftpm/xcode/xcshareddata/xcschemes/HealthCertificateToolkit.xcscheme
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/CBOR+AnyMap.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
Labels: task

#2730 generate new swift files
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
  src/xcode/gen/output/internal/ppdd/tri_state_boolean.pb.swift
Labels: admin, chore

#2721 Fix for RiskProvider tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Consent/__tests__/HealthCertificateConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Utils/DidSetPublished.swift
  src/xcode/ENA/ENA/Source/Utils/__tests__/DidSetPublishedTests.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
Labels: bug

#2724 Fix/6085 adjust info screen to announce new release features for 2.3
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2717 Adjusted Privacy Policies DE, EN, TR for 2.3
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: feature

#2698 7261 Add detailed error handling.
  src/xcode/ENA/HealthCertificateToolkit/.swiftpm/xcode/xcshareddata/xcschemes/HealthCertificateToolkit.xcscheme
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/CBOR+AnyMap.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
Labels: task

#2734 Add logs.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
Labels: task

#2723 fix/7320 changes to fix the voice over issues on contact journal
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: accessibility

#2735 add swift linter rule to prevent using tap directly
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: admin

#2736 Add privacy policy in english language for PL, BG, RO
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: bug

#2705 information when CWA app was installed partially wrong
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
Labels: bug

#2732 UA Bugfix Privacy Policy (EXPOSUREAPP-7274)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#2739 Bump to next Version 2.3.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2737 Crash on NSProgress addChild:withPendingUnitCount:
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#2725 Feature/6454 register vaccination certificates/7234 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Cells/HealthCertificateSimpleTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Cells/HealthCertificateSimpleTextCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertifiedPerson/Cells/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/CreateHealthCertificate.swift
Labels: feature, tests

#2738 Feature/7535 a11y
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Consent/HealthCertificateConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/Cell/HealthCertificateKeyValueTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertifiedPerson/Cells/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/HealthCertificateRegistration/HomeHealthCertificateRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature, tests

#2744 Bump to next Version 2.3.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2746 Fix/7370 empty vaccination details
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/Locale+SupportedLanguage.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/Locale+SupportedLanguageTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#2747 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#2748 Feature/5883 risc details cards text change
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2751 wrong open link method leads to crash
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
Labels: bug

#2754 Bump to next Version 2.3.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2757 Fix/7397 qr code crash fix
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: bug

#2752 Fix/small vaccination fixes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertifiedPerson/Cells/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/MockHealthCertificateService.swift
Labels: bug

#2753 Clean up date formatter naming
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+Extensions.swift
  src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+extentions.swift
  src/xcode/ENA/ENA/Source/Models/Profile/AntigenTestProfile.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/AntigenTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: chore

#2762 Fix/7393 background task crash
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#2749 Database changes to store test results in journal
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV5/ContactDiaryMigration4To5.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV5/ContactDiaryStoreSchemaV5.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV5/ContactDiaryMigration4To5Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV5/ContactDiaryStoreSchemaV5Tests.swift
Labels: feature

#2731 Added two additional unit tests to test/proof the right vcard escaping
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/__tests__/QRCodeCellViewModelTests.swift
Labels: bug

#2704 Replacement of a invalid PCR does not trigger the PCR exchange screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#2741 RAT Profile: DoB off one day
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/AntigenTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/__tests__/CreateAntigenTestProfileViewModelTests.swift
Labels: bug

#2756 feature/7232 automated screenshots
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/CreateHealthCertificate.swift
Labels: admin

#2764 Screen Tan Input page - crash when automating ios 12.5.x devices
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/Cells/TANErrorCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/Cells/TANInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
Labels: bug

#2722 Feature/6125 ppa antigen tests/7308 collector extension
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestResult.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult+Extenstion.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsTestResultCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: task

#2763 missing heading on the screen: TAN für PCR-Test anfragen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
Labels: bug

#2768 Bump to next Version 2.3.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2766 contact journal localizable strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: feature, text-change

#2771 Censor personal antigen test data
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#2742 Feature/7068 refactor launch arguments/7314 refactoring
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITests_05_DataDonation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITests_04b_ExposureDetection.swift
  src/xcode/ENA/ENAUITests/ExposureLogging/ENAUITests_04c_ExposureLogging.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITestsSettings.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_09_TraceLocations.swift
  src/xcode/ENA/ENAUITests/UpdateOS/ENAUITests_08_UpdateOSUITests.swift
Labels: chore

#2770 Configure cell synchronously as it is reloaded on changes anyway
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
Labels: bug

#2775 Add missing screenshot for fully vaccinated person
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/CreateHealthCertificate.swift
Labels: bug

#2772 Fix/7339 Autolayout crash
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/ExposureLogging/HomeExposureLoggingTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TraceLocations/HomeTraceLocationsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeLoadingItemView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeLoadingItemView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeTextItemView.xib
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#2761 Feature/6125 ppa antigen tests/7364 extend key submission metadata
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsSubmissionCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: task

#2785 removed check that last vaccination has to be last doseInSeries
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#2684 PCR scanned followed by TAN Input does not trigger the PCR exchange screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2765 Feature/6125 ppa antigen tests/7309 extend submitter
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsSubmissionCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: task

#2787 Bump to next Version 2.3.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2788 "lets fight coronavirus together" screen - link to information in easy language
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#2769 Feature/5947 tests contact journal extension/7363 extend UI
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_green.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_green.imageset/Test_green.png
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_red.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_red.imageset/Test_red.pdf
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2789 Censor logs only in release builds
  src/xcode/ENA/ENA/Source/Extensions/StringInterpolation+Private.swift
Labels: enhancement

#2779 Feature/6125 ppa antigen tests/7371 unit tests
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: task

#2778 extend cleanup logic and matching unittest
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: feature

#2793 Fix date description for antigen tests
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.swift
Labels: bug

#2776 Feature/5947 tests contact journal extension/7375 extend tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
Labels: feature

#2783 Feature/6125 ppa antigen tests/7477 renaming
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsSubmissionCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsTestResultCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: task

#2781 Feature/5947 tests contact journal extension/7406 add coronatest to contact journal
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: feature

#2777 UA Bugfix
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2794 Converted comments to Markdown
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
Labels: enhancement

#2790 Protocol Buffer update for release 2.4.x at Thu May 27 09:29:46 UTC 2021
  proto/resources/internal/stats/local_statistics.proto
Labels: admin

#2795 Link to repository table in documentation repository (README change only)
  README.md
Labels: admin

#2802 fix/#6608-data-beeing-downloaded-again
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
Labels: bug

#2755 Feature/#6124 ppa event registration/#7306 dev menu
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAMostRecentData.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsActualData.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/Model/CheckinRiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: feature, task

#2797 feature/6125-PPA-Antigen-Tests/7538-Fix-KeySubmission-Logging
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: task

#2803 Protocol Buffer update for release 2.4.x at Fri May 28 11:04:39 UTC 2021
  proto/resources/internal/stats/local_statistics.proto
Labels: admin

#2804 UA Bugfix Capitalization in Enumerations
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2805 Shortening of the title
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2808 Fix/7556 no anonymous proof
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
Labels: bug

#2807 Fix/7088 certificates tab/7544 new design
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Background.imageset/TestCertificate_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Icon.imageset/TestCertificate_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Background.imageset/VaccinationCertificate_CompletelyProtected_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Icon.imageset/VaccinationCertificate_CompletelyProtected_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Background.imageset/VaccinationCertificate_FullyVaccinated_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Icon.imageset/VaccinationCertificate_FullyVaccinated_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Background.imageset/VaccinationCertificate_PartiallyVaccinated_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Icon.imageset/VaccinationCertificate_PartiallyVaccinated_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Vacc_Incomplete.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Vacc_Incomplete.imageset/Vacc_half.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Vaccination_Register.imageset/vacc_Completed.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Vaccination_full.imageset/Vaccination_full.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Add_Vacination.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Add_Vacination.imageset/Illu_Add_Vaccination.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Add_Vacination.imageset/Illu_Add_Vaccination_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Background Colors/ENA Background Light Gray Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Background Colors/ENA Cell Background Color 2.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Card Colors/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Card Colors/ENA Card Border Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Card Colors/ENA Card Shadow Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Card Colors/ENA Dashed Card Border Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/Description/HealthCertificateOverviewDescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertificateRegistration/HomeHealthCertificateRegistrationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertificateRegistration/HomeHealthCertificateRegistrationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertificateRegistration/HomeHealthCertificateRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateInfo/TestCertificateInfoCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateInfo/TestCertificateInfoTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateInfo/TestCertificateInfoTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateRegistration/HomeHealthCertificateRegistrationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateRegistration/HomeHealthCertificateRegistrationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateRegistration/HomeHealthCertificateRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENALabel.swift
  src/xcode/ENA/ENA/Source/Views/CardView.swift
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#2811 Bump to next Version 2.3.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2812 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change
