Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-02, with the labels that each got.

#1888 Fix/4872 contact diary layout not centric
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/Cells/DiaryEditEntriesTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/Cells/DiaryEditEntriesTableViewCell.xib
Labels: Fix 1.12, bug

#1885 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#1879 The highlight effect does not work on all elements of the Homescreen
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Info/HomeInfoTableViewCell.xib
Labels: bug

#1889 Feature/4779 4843 dummy navigation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: task

#1890 Fix/4732 scrolling glitch
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#1874 fix/4862 – Confusing Popup – do not activate exposure logging
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewControllerUtils.swift
Labels: text-change

#1893 Enhance error logging in risk calculation
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
Labels: bug

#1882 Adjust risk cards story
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: feature

#1894 Bump to next Version 1.12.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1895 Create icon cell layout in code to mitigate layout issues on iOS 12
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.xib
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewSpaceCell.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
Labels: bug

#1891 Feature/4850 task protocol fake
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Date+Age.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/PPACDeviceCheck.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/PPACToken.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/TimestampedToken.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACDeviceCheckMock.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACServiceTest.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/TimestampedTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/gen/output/internal/ppdd/edus_otp.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_android.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/ppac_android.pb.swift
  src/xcode/gen/output/internal/ppdd/ppac_ios.pb.swift
  src/xcode/gen/output/internal/v2/app_config_android.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_edus_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_ppac_parameters.pb.swift
Labels: feature

#1878 Feature/4787 translations adjust info screen new release features 1.13
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1897 fix/2450 Accessibility For Toggles On Notifications Settings Screen
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/Cells/NotificationSettingsOnTableViewCell.swift
Labels: accessibility, bug

#1898 Disable screenshots for bulgarian
  .circleci/config.yml
Labels: admin

#1899 This fix ensures, that the deltaOnboarding view controller only shows up once
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#1900 Feature/4940 home screen preload timing
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#1907 Bump Xcode on CI to 12.4
  .circleci/config.yml
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Snapfile
Labels: admin

#1906 Hintergrundaktualisierung - Anleitung teilen - Issue in Dark Mode
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/BackgroundAppRefreshViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/BackgroundAppRefreshViewController.xib
Labels: bug

#1910 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#1901 Feature/4779 4840 survey card
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey.imageset/Group.pdf
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/__tests__/ExposureDetectionSurveyCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: task

#1904 Feature/4851 debug menu ppac
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMButtonCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMButtonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMConfigureableCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMKeyValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMKeyValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMSwitchCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMSwitchTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/DMSwitchTableViewCell.xib
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeviceTimeCheck/DMDeviceTimeCheckViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeviceTimeCheck/DMDeviceTimeCheckViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACDeviceCheck.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACDeviceCheckMock.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACServiceTest.swift
Labels: feature

#1911 Reset timeUntilUpdate on timer end
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
Labels: bug

#1903 Fix/4961 Missing Paragraph On Diary Info Screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/__test__/DiaryInfoViewModelTest.swift
Labels: bug, text-change

#1909 catching errors & added extra logging to some local data related func…
  src/xcode/ENA/ENA/Source/Extensions/FileManager+KeyPackageStorage.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/AppleFilesWriter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/AppleFilesWriterTests.swift
  src/xcode/ENA/ENA/Source/Services/Migration/SerialMigrator.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/Models/RiskCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
Labels: bug

#1915 Bump to next Version 1.12.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1916 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#1917 Bump to next Version 1.12.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1892 Protocol Buffer update for release 1.13.x at Mon Feb 1 14:10:53 UTC 2021
  proto/resources/internal/ppdd/ppa_data.proto
  proto/resources/internal/ppdd/ppa_data_request_android.proto
  proto/resources/internal/ppdd/ppa_data_request_ios.proto
  proto/resources/internal/v2/app_config_android.proto
  proto/resources/internal/v2/app_config_ios.proto
  proto/resources/internal/v2/ppdd_ppa_parameters.proto
Labels: admin

#1913 Feature/xxx improve d menu device time check
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMButtonCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMButtonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMKeyValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMKeyValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMStaticTextCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMStaticTextTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMSwitchCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMSwitchTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMSwitchTableViewCell.xib
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeviceTimeCheck/DMDeviceTimeCheckViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeviceTimeCheck/DMDeviceTimeCheckViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewController.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACService.swift
Labels: feature

#1912 Feature/4824 task api token shoud outlast reset
  src/xcode/ENA/ENA/Source/AppDelegate.swift
Labels: feature

#1868 Headless Unit Tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Globals.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/PlausibleDeniabilityService.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/main.swift
  src/xcode/ENA/ENA/Source/Extensions/Bundle+ReadPlist.swift
  src/xcode/ENA/ENA/Source/Extensions/UIApplication+CoronaWarn.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/StatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENATests/Helper/TimeInterval+Convenience.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: chore

#1902 Feature/4785 adjust consent flow to new apple api
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ExposureManagerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: feature

#1920 Update privacy-policy.html - line break missing [EXPOSUREAPP-4934]
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#1919 Feature/4779 4841 consent screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey_Consent.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey_Consent.imageset/Group 75.pdf
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: task

#1922 Preserve environment settings on app reset.
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#1905 Feature/4833 fetch enable flag from server
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
Labels: task

#1924 Feature/4783 tabbar
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Diary.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Diary.imageset/Vector.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Home.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Home.imageset/Path 1.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Diary.imageset/Illu_Diary.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Child.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/DiaryEditEntriesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/DiaryEditEntriesViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Diary/HomeDiaryCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Diary/HomeDiaryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Diary/HomeDiaryTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Diary/__tests__/HomeDiaryCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationControllerWithFooter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/__tests__/CoordinatorTests.swift
Labels: feature

#1928 Feature/5004 reset consent on test deletion
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
Labels: bug

#1927 The "Consent"-Button disappears, when you click on "Update" test result
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.xib
Labels: Fix 1.12, bug

#1925 Fix/4968 Remove Close Button From Data Privacy Screens
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/DataPrivacyViewControllerDisablingSwipeToDismiss.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
Labels: bug

#1926 Feature/4784 fql link how to get tested
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Test Tube.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Test Tube.imageset/Icons - Test Tube.png
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Test Tube.imageset/Icons - Test Tube@2x.png
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Test Tube.imageset/Icons - Test Tube@3x.png
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: feature

#1929 Feature/4787 adjust info screen new release features 1.13
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/String+Compare.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1932 Feature/4994 task list of selection
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Checkmark.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Checkmark.imageset/Icons_Checkmark.pdf
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/Cell/SelectValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/Cell/SelectValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/Cell/__tests__/SelectValueCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProvider.swift
Labels: feature

#1939 Feature/5012 task http request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitAnalyticsDataTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPResponse.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/PPACToken.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/TimestampedToken.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACDeviceCheck.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACDeviceCheckMock.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/__tests__/PPACServiceTest.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/__tests__/PPACTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/__tests__/TimestampedTokenTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASResponse.swift
Labels: task

#1935 Check if the OTP is authorized then navigate accordingly.
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
Labels: task

#1945 observe background refresh status notification for updating ui
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewController.swift
Labels: bug

#1930 Feature/4779 4842 implement view model
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/default_app_config_113
  src/xcode/ENA/ENA/Resources/default_app_config_18
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyURLServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: task

#1943 Use completion handler in functions of MockExposureManager (closes #1918)
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
Labels: bug, community, mirrored-to-jira

#1940 Tweak Linter for tests
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClientTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerRowsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewTextViewCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Info/__tests__/HomeInfoCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/__test__/RiskLegendeTest.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: chore, devcamp

#1948 Feature/4779 4990 reset otp when risk changes
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMOTPService/DMOTPServiceViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMOTPService/DMOTPServiceViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyURLServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/__tests__/CoordinatorTests.swift
Labels: task

#1946 Different Selection Buttons in the Popup, when scanning invalid QR-Code
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Alert.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#1947 Fix/otp service update
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#1952 Fix none ENF iOS startup
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/PlausibleDeniabilityService.swift
Labels: bug

#1953 adding missing entry in mock store
  src/xcode/ENA/ENA/Source/Scenes/PPA/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: task

#1951 Feature/4788 translations ppa onboarding and settings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1944 Update Survery Consent strings and UI
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#1949 formatting the data privacy notes EN/DE
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: bug

#1954 Feature/4779 finalize flow
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyURLServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACServiceTest.swift
Labels: task

#1959 Add new localizable strings for end-of-life behaviour
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1958 Datadonation list value strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1961 rename constent flag
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#1960 Feature/4781 end of life behaviour
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/UNUserNotificationCenter+DeadManSwitch.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/WarnOthersReminder.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersReminderTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/ThankYou/HomeThankYouCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/ThankYou/HomeThankYouTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/ThankYou/HomeThankYouTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/ThankYou/__tests__/HomeThankYouCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/DeadmanNotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/UserNotificationCenter.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/Mocks/MockDeadmanNotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/Mocks/MockUserNotificationCenter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1950 Feature/4779 texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: task, text-change

#1962 Feature/4779 event based link to rki survey
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey.imageset/Group.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey_Consent.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Survey_Consent.imageset/Group 75.pdf
  src/xcode/ENA/ENA/Resources/default_app_config_113
  src/xcode/ENA/ENA/Resources/default_app_config_18
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMOTPService/DMOTPServiceViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMOTPService/DMOTPServiceViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewModel.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/ExposureDetectionSurveyTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/Survey/__tests__/ExposureDetectionSurveyCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyURLServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAC/__tests__/PPACServiceTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/__tests__/CoordinatorTests.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: feature

#1957 Change 'Umfrage' to 'Befragung'
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1955 Task/4919-collect-risk-exposure-data
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskExposureMetadata.swift
  src/xcode/ENA/ENA/Source/Models/User/UserMetadata.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: task

#1966 Feature/TASK DeveloperMenu DeltaOnboarding Enhancement
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
Labels: task

#1963 Feature/5013 pp analytics submitter
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskLevel.swift
  src/xcode/ENA/ENA/Source/Models/User/AgeGroup.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/District.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#1967 Feature/5014 developer menu ppa submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsActualData.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsMostRecent.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#1970 Refactor/refactoring pp storage
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: chore

#1973 Less optional try please
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetTestResultTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+RegistrationTokenTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TANForExposureSubmitTests.swift
  src/xcode/ENA/ENA/Source/Client/Security/iOS 12 Fallback/CryptoKitFallbacks.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V1/DownloadedPackagesSQLLiteStoreV1.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/Models/RiskCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/Gemfile.lock
Labels: enhancement

#1965 12.5 Exposure Logging ON/OFF jumps to text-switch-area
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionDetailTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionDetailTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DescriptionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/EuTracingTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/EuTracingTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ImageTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ImageTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/TracingHistoryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/TracingHistoryTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ENSettingModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENASwitch.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.swift
  src/xcode/ENA/ENA/Source/Views/SeperatorLineLayer.swift
Labels: bug

#1975 Feature/4996 tsk data donation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Illu_DataDonation.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Illu_DataDonation_DarkMode.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/ppdd-ppa-administrative-unit-set-ua-approved.json
  src/xcode/ENA/ENA/Source/Extensions/URL+StaticString.swift
  src/xcode/ENA/ENA/Source/Models/User/AgeGroup.swift
  src/xcode/ENA/ENA/Source/Models/User/UserMetadata.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/DataDonationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/DataDonationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/DataDonationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/DataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/District.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/__tests__/DataDonationModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/__tests__/DataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/__tests__/testData.json
  src/xcode/ENA/ENA/Source/Scenes/Datadonation/__tests__/testDataInvalid.json
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingDataDonation.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/__tests__/SelectValueCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: task

#1976 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#1977 Feature/4997 add datadonation to settings
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Settings_Datenspende.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Settings_Datenspende.imageset/Icons_Settings_Datenspende.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/BaseDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/BaseDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/DefaultDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/SettingsDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/testData.json
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/testDataInvalid.json
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/DataDonationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/District.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/__tests__/DataDonationModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/__tests__/DistrictTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/__tests__/DataDonationDetailsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingDataDonation.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1968 Feature/task 5097 journal data structure
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayEntryCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryContactPerson.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryEntry.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/LocationVisit.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryEntryTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryLocationTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
Labels: task

#1972 Fix/4786 Data Privacy Note For Release 1.13
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
Labels: text-change

#1978 Add community build to CI
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENACommunity.xcscheme
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/TestPlans/SmokeTests.xctestplan
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
Labels: admin

#1971 Feature/4790-5104_client_metadata
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENACommunity.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENAScreenshots.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA/Source/Models/ClientMetaData/ClientMetaData.swift
  src/xcode/ENA/ENA/Source/Models/ClientMetaData/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#1981 Fixing flaky test_0022_AppInformationFlow_faq
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: admin

#1985 Bump to next Version 1.13.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1987 Bump to next Version 1.13.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1991 Rename errorState to errorCode
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitAnalyticsDataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASResponse.swift
Labels: bug

#1983 Feature/task 5000 data donation UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITestsDataDonation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITestsSettings.swift
Labels: feature

#1995 Fix/otp debug menu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMOTPService/DMOTPServiceViewModel.swift
Labels: bug

#1988 Feature/5083 translations adjust info screen to announce new release features for 1.14
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1994 Fix Screenshots
  src/xcode/ENA/ENAUITests/ENAUITests.swift
Labels: admin

#1996 App crashes while scrolling the No TAN yet Screen
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.swift
  src/xcode/ENA/ENA/Source/Views/SeperatorLineLayer.swift
Labels: bug

#1993 Exposure Logging - Country List not loading after WLAN on + app in foreground
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
Labels: bug

#1999 Bump to next Version 1.13.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1986 feature/TASK-5151 Fixed Text Issues for Data Donation "Ausführliche Informationen zur Datenspende"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2003 Fix missing pop-up on fresh install
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#2000 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
Labels: text-change

#2006 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2009 The labels of the buttons in Settings disappear when you activate white mode and vice versa
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Settings_Datenspende.imageset/Contents.json
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/Cells/MainSettingsCell.xib
Labels: bug

#2011 handle attempt to dismiss in DataDonationDetailsViewController
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewController.swift
Labels: bug

#2013 Unnecessary toggle switch in In-App-Settings share data settings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/BaseDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
Labels: bug

#2012 Fix/5208 device check token generation error
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACDeviceCheck.swift
Labels: bug

#2010 Added one more mention of 'Drittländer' to legal texts (RKI survey)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#2015 4895 screenshot incomplete testplan missing
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: bug

#2016 Reset positiveTestResultWasShown, it might still be set from 1.12
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
Labels: bug

#2017 Bump to next Version 1.14.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2008 Fix/5164 remove image and shorten text in ppa onboarding and delta onboarding
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Illu_DataDonation.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_DataDonation.imageset/Illu_DataDonation_DarkMode.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/DefaultDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/SettingsDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTypeTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITestsDataDonation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: bug

#2018 remove some languages from snapshots
  .circleci/config.yml
Labels: admin

#2005 Feature/4790 5102 test result metadata
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/ClientMetaData/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Models/TestResultMetaData/TestResultMetaData.swift
  src/xcode/ENA/ENA/Source/Models/TestResultMetaData/TestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/TestResultMetaData/__tests__/TestTestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult+Extenstion.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2019 Bump to next Version 1.13.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2004 Feature/task 5087 add new attributes to add edit person place screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/TextFieldManager.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/TextFieldsManagerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2021 i18n strings for translation for contact journal notes info
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1990 Feature/task 5085 adapt and migrate database
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV3/ContactDiaryMigration2To3.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV3/ContactDiaryStoreSchemaV3.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryAccess.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV1/ContactDiaryStoreSchemaV1Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV2/ContactDiaryMigration1To2Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV2/ContactDiaryStoreSchemaV2Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV3/ContactDiaryMigration2To3Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV3/ContactDiaryStoreSchemaV3Tests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/MigrationStub.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/SerialDatabaseQueueMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/SerialMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/Migration/Migration.swift
  src/xcode/ENA/ENA/Source/Services/Migration/SerialDatabaseQueueMigrator.swift
  src/xcode/ENA/ENA/Source/Services/Migration/SerialMigrator.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
Labels: task

#2024 Not all EN-Errors link to the FAQ page correctly
  src/xcode/ENA/ENA/Source/Extensions/Error+FAQUrl.swift
Labels: bug

#2020 Feature/4790 5103 key submission data
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/AgeGroup.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/KeySubmissionMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/LastSubmissionFlowScreen.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/RiskExposureMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetaData.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/UserMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/__tests__/TestTestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/__tests__/UserMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#2023 TASK5235 – Corrections To The Legal Texts (EN/TU) And Data Privacy Note
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#2026 Reload table view completely on statistics update
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2029 Bump to next Version 1.13.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2027 Fix/5192 close button missing on screens
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionThankYouViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/TestResultAvailableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionHotlineViewControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionNavigationControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/NavigationControllerWithFooter/ENANavigationControllerWithFooter.swift
  src/xcode/ENA/ENA/Source/Views/Common/CloseBarButtonItem.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2033 Deadman Notifications are scheduled and sent in End-of-Life State
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
Labels: bug

#2025 Feature/task 5080 5090 adapt export
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: task

#2034 PPDD Error messages do not contain CWA error code for 429/API_TOKEN_QUOTA_EXCEEDED
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#2028 Feature/4790 new exposure windows collection
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Metadata/ExposureWindowsMetadata/ExposureNotifications+Extension.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/ExposureWindowsMetadata/ExposureWindowsMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/ExposureWindowsMetadata/ExposureWindowsMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetaData/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/DebugRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2037 Feature/task 5080 5089 show attributes in overview
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAFont.swift
  src/xcode/ENA/ENA/Source/Extensions/UIFont+DynamicType.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2039 text label layout fixed
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTypeTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/__tests__/DynamicTableViewControllerRowsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
Labels: bug

#2035 Leave downloading activity state in EOL state when download is finished
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#2041 Feature/4790 5266 save registration token in test metadata
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetaData.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetaData/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/TestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
Labels: task

#2042 set defauilt ViewController with correct background color
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: admin

#2038 Feature/4790 5243 add exposure windows metadata tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Metadata/ExposureWindowsMetadata/ExposureWindowsMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/ExposureWindowsMetadata/__tests__/ExposureWindowsMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#2040 Feature/task 5080 fix migration
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: bug

#2043 Feature/4790 5221 key submission metadata unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Metadata/Client Metadata/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureNotifications+Extension.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureWindowsMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureWindowsMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/__tests__/ExposureWindowsMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/LastSubmissionFlowScreen.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/RiskExposureMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/AgeGroup.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/UserMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/__tests__/UserMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2044 Bump to next Version 1.13.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2048 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2036 Feature/task 5080 5088 new info screen for notes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayNotesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayNotesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayNotesInfoViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2052 Bump to next Version 1.13.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2051 removed non needed layout request
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeShownPositiveTestResultTableViewCell.swift
Labels: bug

#2056 data privacy note 1.13 DE
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: bug

#2054 Contact Journal Texts.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: feature

#2050 Feature/task 5277 more migration fixes
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV2/ContactDiaryMigration1To2.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV3/ContactDiaryMigration2To3.swift
Labels: bug

#2047 Feature/4790 data collection extended
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENACommunity.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENAScreenshots.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Client Metadata/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureNotifications+Extension.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureWindowsMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureWindowsMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/__tests__/ExposureWindowsMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/LastSubmissionFlowScreen.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/RiskExposureMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadataService.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/AgeGroup.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/UserMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/__tests__/TestResultMetadataServiceTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/User Metadata/__tests__/UserMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult+Extenstion.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmission+TestResult.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/DebugRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/gen/output/internal/ppdd/ppa_data_request_android.pb.swift
Labels: feature

#2053 Adding new localised string for high risk caused by multiple low risks
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2049 Additional text changes for new features of version 1.14
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2055 Fix/5251 wrong text risk detail screen with low encounter
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, text-change

#2057 Bump to next Version 1.13.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2058 Background Process Disabled Popup reappears
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2059 Feature/5083 changed new release features for 1 14
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/NewVersionFeature.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2061 fix/5261-Double whitespace removed
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#2060 Fix/5242-Fixed issue with not closed HTML tag
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: bug

#2064 Bugfix/1876 voice over jumping in long html strings
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/DataPrivacyViewControllerDisablingSwipeToDismiss.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HTMLViewController/HTMLViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HTMLViewController/HTMLViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/HTMLViewController/HtmlInfoModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15ViewModel.swift
Labels: bug

#2065 Fixes an issue with data donation delta onboarding not shown, resp. n…
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: bug

#2066 The icon for the "Share Data"-button has wrong background colour in dark mode
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Settings_Datenspende.imageset/Icons_Settings_Datenspende.pdf
Labels: bug

#2067 Flag images wrong aspect ratio
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
Labels: bug

#2069 Too many linebreaks at the top of the "Data Donation - Details" screen on Onboarding and Delta Onboarding
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewController.swift
Labels: bug

#2031 Feature/5081 app launcher shortcut
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/book.closed.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/book.closed.imageset/book.closed.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITestsQuickActions.swift
  src/xcode/ENA/ENA/Source/Extensions/NotificationName.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: feature, text-change
