Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-11, with the labels that each got.

#3753 Feature/9802 recycle corona test/10131 recycle tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__test__/RecycleBinViewModelTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/AntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestRestorationHandler.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestedPerson.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRestorationHandler.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/Model/RecycleBinRestorationHandling.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/__tests__/RecycleBinTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3757 Feature/9802 recycle corona test/10134 override notice
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/RecycleBinViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__test__/RecycleBinViewModelTest.swift
Labels: task

#3771 Feature/7701 refactor http client/xxx add locators and clients
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AppConfigurationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/AppConfiguration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/AvailableDays.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/DCCRules.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/DSCList.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/DiagnosisKeys.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/LocalStatistics.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/QRPosterTemplate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/Statistics.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/TWPDiscovery.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/TWPDownload.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/VaccinationValueSets.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/ValidationOnboardedCountries.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/AuthorizeOtpEdus.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/AuthorizeOtpEls.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/DCCRegisterPublicKey.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/DigitalCovid19Certificate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/KeySubmission.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/RegistrationToken.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/SubmitELS.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/SubmitOnBehalf.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/SubmitPPA.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/TANForExposureSubmit.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/TestResultDownload.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/ProtobufReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/SendResources/EmptySendResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountriesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/WifiOnlyRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
Labels: chore

#3749 feature/10190 add timestamp to the ENError message after failed risk check
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionTransaction+DidEndPrematurelyReason.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/RateLimitLogger.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
Labels: community, mirrored-to-jira

#3776 Make it clearer that one can't verify certificates from others with the CWA
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, mirrored-to-jira

#3743 Fix/9914 layout of badge for certificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: community, mirrored-to-jira

#3770 Fix/10211 calculation of most recent date changed incorrect
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: bug

#3778 Feature/9802 recycle corona test/10155 restore on reregistration
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/RecycleBinViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__test__/RecycleBinViewModelTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/AntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: task

#3780 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3783 Bump to next Version 2.13.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3784 Feature/9802 recycle corona test/10135 UI tests
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/RecycleBin.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
Labels: task

#3785 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3786 Story/9802 recycle corona test
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/RecycleBinViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__test__/RecycleBinViewModelTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/AntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestRestorationHandler.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestedPerson.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRestorationHandler.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/Model/RecycleBinRestorationHandling.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/RecycleBin.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/__tests__/RecycleBinTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
Labels: feature

#3787 Fix/ Unit test. Use utc calendar.
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
Labels: bug

#3790 Fix/5896 remove highlighting from risk legend
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/Cell/RiskLegendDotBodyCell.swift
Labels: community

#3794 Adjustment of "Neue Funktionen 2.14"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3789 Fix/5897 highlight on selection of transnational exposure logging
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/EuTracingTableViewCell.swift
Labels: community

#3788 Fix/9910 tabbar becomes transparent contact diary day view
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#3797 Feature/10275 invalidate certificates/10387 state UI
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateValidityState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3795 Replace scannen with wählen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3793 Make it clearer to only scan your certificates (COMMUNITY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, mirrored-to-jira

#3782 New rest service, caching solution
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Locator.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/CachedRestServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore+Creation.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/__tests__/KeychainHelperTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureCache.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStoring.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: task

#3798 Regenerate protobuf models
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_export.pb.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_signature_list.pb.swift
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/app_version_config.pb.swift
  src/xcode/gen/output/internal/attenuation_duration.pb.swift
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data_request_ios.pb.swift
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/risk_score_parameters.pb.swift
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_edus_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_els_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_ppa_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: task

#3800 Fix/10442 booster rule reset
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/FakeBoosterNotificationsService.swift
Labels: bug

#3806 Bump to next Version 2.14.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3808 Feature/10275 invalidate certificates/10388 identifier check
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/String+DataWithHexString.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/TraceLocationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/String+Utils.swift
Labels: task

#3809 Feature/10275 invalidate certificates/10391 notifications
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: task

#3811 return the first passed rule according to the server order of rules
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/RuleValidation/ValidationRulesAccessTests.swift
Labels: bug

#3812 use current app configuration instead of waiting up to 5 minutes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodeErrorCorrectionLevelProvider.swift
Labels: bug

#3816 Admin/bump to next version 2.13.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3818 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3819 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3820 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3821 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3822 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: text-change

#3823 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3825 Feature/10275 invalidate certificates/disable validity check
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
Labels: task

#3824 Add external library CryptoSwift.
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENASecurity/.swiftpm/xcode/xcshareddata/xcschemes/ENASecurity.xcscheme
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/fastlane/README.md
Labels: task

#3826 Story/10291 most relevant dcc
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
Labels: feature

#3810 Add new test cases for the AES-CBC encryption.
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/AESEncryptionTests.swift
Labels: task

#3827 Bump to next Version 2.13.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3828 Feature/10275 invalidate certificates/last minute changes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3815 Story/10275 invalidate certificates
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/String+DataWithHexString.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/TraceLocationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateValidityState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/String+Utils.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_export.pb.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_signature_list.pb.swift
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/app_version_config.pb.swift
  src/xcode/gen/output/internal/attenuation_duration.pb.swift
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data_request_ios.pb.swift
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/risk_score_parameters.pb.swift
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_edus_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_els_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_ppa_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: feature

#3817 Feature/10349 crypto functions part1/10434 aes gcm
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/CBCEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/GCMEncryption.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/CBCEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/GCMEncryptionTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
Labels: task

#3829 Feature/10349 crypto functions part1/10435 rsa oaep with sha256
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/RSAEncryptionTests.swift
Labels: feature

#3833 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3837 Bump to next version 2.13.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3836 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3830 Extend error handling.
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/CBCEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/GCMEncryption.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/CBCEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/GCMEncryptionTests.swift
Labels: task

#3844 Fix/10553 no database entry after test registration
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_export.pb.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_signature_list.pb.swift
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/app_version_config.pb.swift
  src/xcode/gen/output/internal/attenuation_duration.pb.swift
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data_request_ios.pb.swift
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/risk_score_parameters.pb.swift
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_edus_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_els_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_ppa_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: bug

#3831 Replace entfernen by löschen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3807 Feature/10349 crypto functions part1/10433 check certificate chain
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Utils/Data+SHA256.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
Labels: task

#3835 Feature/10349 crypto functions part1/10436 extract jwk public key
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/Model/JSONWebKeyTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: task

#3851 Bump to next Version 2.14.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3840 ECSHA256 signing
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECSHA256Signer.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/ECSHA256SignerTests.swift
Labels: task

#3853 Adjust text Find Testing Center
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3857 Fix Release build
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionService.swift
Labels: bug

#3856 Adapt privacy policy for release 2.14
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#3850 Feature/10349 crypto functions part1/10440 verifiy signature jwt
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/JWTVerification.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/JWTVerificationTests.swift
  src/xcode/fastlane/README.md
  src/xcode/fastlane/actions/update_third_party_notice.rb
Labels: task

#3805 Feature/10249 update get tan for exposure submit request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/PlausibleDeniabilityService.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/RegistrationTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/__tests__/HTTPClientCertificatePinningTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/SubmissionTANModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Send/SendRegistrationTokenModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/ServiceError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionError.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/__tests__/FakeRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionError.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/__tests__/OnBehalfCheckinSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENATests/Helper/RestServiceProviderFactory.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
Labels: task

#3845 Feature/10349 crypto functions part1/10437 generating an ec key pair with curve p 256
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPair.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPairGeneration.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/ECKeyPairGenerationTests.swift
Labels: task

#3847 Feature/10350 ticketvalidation consent/10542 consent screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TicketValidation.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TicketValidation.imageset/Illu_TicketValidation-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TicketValidation.imageset/Illu_TicketValidation.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3855 Feature/10350 ticketvalidation consent/10537 UI test
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/BaseDataDonationViewModel.swift
  src/xcode/ENA/ENAUITests/TicketValidation/ENAUITests_19_TicketValidation.swift
  src/xcode/ENA/ENAUITests/UniversalQRCodeScanner/ENAUITests_16_UniversalQRCodeScanner.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
Labels: task

#3858 Refactor x5c property to array.
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/JWTVerificationTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/Model/JSONWebKeyTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
Labels: task

#3861 Update outdated state correctly for antigen tests with outdated pointOfCareConsentDate
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
Labels: bug

#3802 fix/10180 localisation of countries for certificate validation
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: community

#3843 fix/5624 enable link preview for onboarding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
  src/xcode/ENA/ENA/Source/Workers/LinkHelper.swift
Labels: community, mirrored-to-jira

#3875 Story/10167 adjust info screen release 2.15
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3841 Remove 3rd Bullet Point from "Check Validity" screen (Addresses cwa-documentation issue 721) (COMMUNITY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: community, mirrored-to-jira

#3867 Feature/10349 crypto functions part1/10575 extend http client dynamic pinning
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DefaultEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DynamicEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/_EvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/__tests__/FakeEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/__tests__/URLSessionDelegate+UpdateEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/DynamicPinningRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/ServiceType.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/WifiOnlyRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockURLSession.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
Labels: feature

#3879 Story/10349 crypto functions part1/storybranch
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DefaultEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DynamicEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/_EvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/__tests__/FakeEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/__tests__/URLSessionDelegate+UpdateEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/DynamicPinningRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/ServiceType.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/WifiOnlyRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockURLSession.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENASecurity/.swiftpm/xcode/xcshareddata/xcschemes/ENASecurity.xcscheme
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/CBCEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPair.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPairGeneration.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECSHA256Signer.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/GCMEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/JWTVerification.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Utils/Data+SHA256.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/AESEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/CBCEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/ECKeyPairGenerationTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/ECSHA256SignerTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/GCMEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/JWTVerificationTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/Model/JSONWebKeyTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/RSAEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/fastlane/actions/update_third_party_notice.rb
Labels: feature, task

#3880 Feature/extending new http client for crypto calls
  src/xcode/ENA/ENA/Source/HTTPClient/Endpoint.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTANResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service.swift
Labels: task

#3865 Feature/10352 ticket validation result screen/10637 implementation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/DynamicCell+TicketValidationResult.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/TicketValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/TicketValidationResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/__tests__/TicketValidationResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/__tests__/TicketValidationResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResult+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResult.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3863 Add encrypt and sign of DCC.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Data+Random.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/DCCEncryption.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/EncryptAndSignDCC/EncryptAndSignError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/EncryptAndSignDCC/EncryptAndSignResult.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/EncryptAndSignDCC/EncryptionScheme.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/DCCEncryptionTests.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/Model/TicketValidationInitializationData+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/TicketValidationTests.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Utils/SecKey+Creation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/RSAEncryptionTests.swift
Labels: task

#3884 Test changes to info screen as per figma update
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3882 Feature/10351 ticket validation select certificate second consent/10562 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions+Fake.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/TicketValidation/ENAUITests_19_TicketValidation.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
Labels: task

#3873 Feature/10555 ticket validation select certificate
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Cells/TicketValidationNoSupportedCertificateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Cells/TicketValidationNoSupportedCertificateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/TicketValidationCertificateSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/TicketValidationCertificateSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/__tests__/TicketValidationCertificateSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions+CertificateSelection.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/__tests__/ValidationConditions+CertificateSelectionTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/TicketValidation/ENAUITests_19_TicketValidation.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
Labels: task

#3890 Add and cleanup models.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationAccessToken.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationConditions+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationConditions.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationInitializationData.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResult.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationServiceIdentityDocument.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationTransactionContext.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
Labels: task

#3889 Story/10351 ticket validation select certificate second consent
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Cells/TicketValidationNoSupportedCertificateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Cells/TicketValidationNoSupportedCertificateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/TicketValidationCertificateSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/TicketValidationCertificateSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/__tests__/TicketValidationCertificateSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions+CertificateSelection.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationConditions+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/__tests__/ValidationConditions+CertificateSelectionTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/TicketValidation/ENAUITests_19_TicketValidation.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
Labels: feature

#3893 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3894 Story/10464 crypto functions part 2/add pinningless rest service
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/DisabledPinningRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/ServiceType.swift
Labels: task

#3886 Add possibility for detailed trust evaluation error handling.
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DefaultEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DynamicEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/_EvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/URLSessionDelegates/__tests__/FakeEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/ServiceError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
Labels: task

#3866 Make notifications time sensitive
  src/xcode/ENA/ENA/Resources/ENA.entitlements
  src/xcode/ENA/ENA/Resources/ENACommunity.entitlements
  src/xcode/ENA/ENA/Resources/ENATest.entitlements
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
Labels: community

#3885 Story/10636 requesting the service identity document of the validation decorator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/IdentityDocumentDecorator.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentValidationDecoratorResource.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationDecorator/ServiceIdentityDocumentValidationDecoratorError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationDecorator/TicketValidationServiceIdentityDocumentValidationDecorator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
Labels: task

#3901 Protocol Buffer update for release 2.15.x at Mon Nov 29 09:52:03 UTC 2021
  proto/resources/internal/dgc/validation_service_allowlist.proto
Labels: admin

#3877 fix/3870 mock more external links during unit test
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintTableViewCell.swift
Labels: community

#3891 Feature/10352 ticket validation result screen/10663 UI tests
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/TicketValidationCertificateSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/TicketValidation/ENAUITests_19_TicketValidation.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
Labels: tests, screenshots

#3892 Feature/10464 crypto functions part 2/10640 requesting service identity document
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/String+Regex.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Endpoint.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/Locator+ServiceIdentityDocument.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/ServiceIdentityDocumentResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/_EvaluateTrust.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/ServiceError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/MockURLSession.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationServiceIdentityDocument+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationServiceIdentityDocument.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationServiceIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/ServiceIdentityDocumentProcessorTests.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey+Fake.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
Labels: task

#3903 Feature/10464 crypto functions part 2/10642 requesting result token
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/TicketValidationResultTokenLocator.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationResultTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationAccessTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationResultTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Send/TicketValidationResultTokenSendModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/DynamicCell+TicketValidationResult.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/Cells/TicketValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/EncryptAndSignDCC/DCCEncryption.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/EncryptAndSignDCC/EncryptAndSignError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/EncryptAndSignDCC/EncryptAndSignResult.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/EncryptAndSignDCC/EncryptionScheme.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResultToken+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResultToken.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationTransactionContext.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ResultToken/TicketValidationResultTokenProcessingError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ResultToken/TicketValidationResultTokenProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ResultToken/TicketValidationResultTokenResult.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ServiceIdentityDocument/TicketValidationServiceIdentityDocumentError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ServiceIdentityDocument/TicketValidationServiceIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ServiceIdentityDocument/TicketValidationServiceIdentityDocumentResult.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/ServiceIdentityDocumentValidationDecoratorError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationServiceIdentityDocumentValidationDecorator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/TicketValidationResultTokenProcessorTests.swift
Labels: task

#3888 Story/10733 validation decorator unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentValidationDecoratorResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/ServiceIdentityDocumentValidationDecoratorResourceTests.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationDecorator/ServiceIdentityDocument.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/ValidationDecorator/__tests__/ValidationDecoratorServiceTests.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
Labels: task

#3904 fix/#10179-overlapping-icons
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
Labels: bug

#3905 Protocol Buffer update for release 2.15.x at Tue Nov 30 10:00:43 UTC 2021
  proto/resources/internal/dgc/validation_service_allowlist.proto
Labels: admin

#3907 Protobuf files update for release 2.15
  src/xcode/gen/output/internal/dgc/validation_service_allowlist.pb.swift
Labels: admin

#3908 Story/adapt privacy policy release 2.15
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#3898 feature/5624 add preview for 2 links
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
Labels: community, mirrored-to-jira

#3909 Fix/flaky test_AddStatisticsButton_flow
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENAUITests/Helper/SnapshotHelper.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
  src/xcode/ENA/ENAUITests/Utils/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/Utils/UITestingParameters.swift
Labels: tests
