Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-01, with the labels that each got.

#1753 Fix/4490 set time zone in contact journal date formatter
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+ContactDiary.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreV1Tests.swift
Labels: bug

#1756 Update fastlane to 2.171.0
  src/xcode/Gemfile.lock
Labels: admin

#1761 Add close button to debug menu.
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
Labels: feature

#1757 fix/4476-Loop_After_Reset
  src/xcode/ENA/ENA/Source/Coordinator.swift
Labels: bug

#1759 fix community build errors
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
Labels: bug

#1760 fix/4106 – Create file logger only once.
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
Labels: bug

#1758 Remove not used alert controller factories.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENACommunity.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENAScreenshots.xcscheme
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENATests.xcscheme
  src/xcode/ENA/ENA/Source/Extensions/ExposureDetection_DidEndPrematurelyReason+ErrorHandling.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_DidEndPrematurelyReason+ErrorHandlingTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ExposureDetection_FAQ_URL_Tests.swift
Labels: chore

#1763 fix/4502-Missing_label_for_menu_button
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1737 fix Prefixed zeros not being saved correctly in Contact Journal
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV1/ContactDiaryStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV2/ContactDiaryMigration1To2.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV2/ContactDiaryStoreSchemaV2.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migrations/Migration0To1.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migrations/Migration1To2.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/SerialMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/Migration/Migration.swift
  src/xcode/ENA/ENA/Source/Services/Migration/SerialMigrator.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITestsSettings.swift
Labels: bug

#1766 Admin/screenshot artifakt failing test
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/fastlane/Fastfile
Labels: admin

#1767 Fix testNavigationToInformationVC
  .circleci/config.yml
  scripts/xccov-to-sonarqube-generic.sh
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/fastlane/Fastfile
Labels: admin

#1765 Don't update testresult on view appear.
  src/xcode/ENA/ENA/Source/Scenes/NewHome/HomeTableViewController.swift
Labels: bug

#1768 Fix/new home fixes
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeShownPositiveTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeShownPositiveTestResultTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/NewHome/HomeTableViewController.swift
Labels: bug

#1771 Fix test result color
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.xib
Labels: bug

#1754 Include license in README.md
  README.md
Labels: mirrored-to-jira

#1774 Admin/improve sonar coverage
  .circleci/config.yml
  scripts/cococo
  scripts/xccov-to-sonarqube-generic.sh
  scripts/xcov_to_sonar.sh
  src/xcode/fastlane/Fastfile
Labels: admin

#1773 Fix/2452 read color in risk status box
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeRiskTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Views/HomeImageItemView.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/Cell/RiskLegendDotBodyCell.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/Cell/RiskLegendDotBodyCell.xib
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/__test__/RiskLegendeTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1776 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1777 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#1779 Fix two homescreen screenshots
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: admin

#1782 fix/negavie calculation days interval
  src/xcode/ENA/ENA/Source/Workers/ActiveTracing.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/ActiveTracingTests.swift
Labels: bug

#1784 fix test result is not updated on the home screen + app crash
  src/xcode/ENA/ENA/Source/Scenes/NewHome/HomeTableViewController.swift
Labels: bug

#1780 Fix/failing tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/ExposureLogging/ENAUITests_05_ExposureLogging.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: admin

#1781 Fix/4572 button to system notifications does not work
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.xib
Labels: bug

#1788 Fix/4204 Text Länderübergreifende Risikoermittlung
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug, text-change

#1787 Update encounter/visit selection and deselection faster
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#1785 added open combine to spm package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: admin

#1792 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#1789 Fix/new home voice over fixes
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Diary/HomeDiaryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/ExposureLogging/HomeExposureLoggingTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeRiskTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/Risk/HomeShownPositiveTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/TestResult/HomeTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Cells/ThankYou/HomeThankYouTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/NewHome/Views/HomeListItemView.swift
Labels: accessibility

#1793 Feature/3719 update protobuf
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/AppConfig+CacheInvalidation.swift
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/stats/card_header.pb.swift
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/statistics.pb.swift
  src/xcode/gen/output/internal/v2/app_features.pb.swift
  src/xcode/gen/output/internal/v2/key_download_parameters.pb.swift
Labels: enhancement

#1794 change the button title ons electing an option
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1797 use fastlane to update Legal Notice displayed inside the app
  licenses.json
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
Labels: admin

#1796 text correction
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug, text-change

#1790 Fix/load test result initially
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#1799 Fix/small fixes
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
Labels: enhancement

#1800 updated text on home screen tile
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: feature, text-change

#1804 Bump to next Version 1.12.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1798 Fix/3781 throttling app config request
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#1778 Update Localizable.strings [EXPOSUREAPP-4580]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#1801 Feature/task 4614 over view
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high.imageset/Icons_Attention.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_low.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_low.imageset/Icons_Attention_gray.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#1805 Feature/4613 task information screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high_small.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high_small.imageset/Icon_Attention_High_small.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature, text-change

#1807 fetch & cache statistical data
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcbaselines/85D7595324570491008175F0.xcbaseline/4D380FF7-7C4B-42F6-833F-6B98345B5DEA.plist
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/HTTPURLResponse+Header.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/StatisticsMetadata.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryContactPerson.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryEntry.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryEntryType.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/LocationVisit.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryEntryTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryLocationTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/StatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.bin
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.sha256
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store+Statistics.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: enhancement

#1809 Fix/4648 cell animation crash
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#1808 Feature/4615 task extend risk calculation for exposure history
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/RiskLevelPerDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/__tests__/HomeRiskCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: feature

#1810 fix no new risk calculation in automatic mode
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
Labels: bug

#1813 Add localizable strings for statistics
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1816 Failing Tests should fail CI
  src/xcode/fastlane/Fastfile
Labels: admin

#1820 Feature/task 3411 UI tests for statistics
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: tests

#1814 4434-create-missing-screenshots
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#1817 build tests as well
  src/xcode/fastlane/Fastfile
Labels: enhancement

#1818 Feature/4526 os update info screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_UpdateOS.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_UpdateOS.imageset/Illu - Update Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_UpdateOS.imageset/Illu - Update.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/AppDisabled/AppDisabledView.swift
  src/xcode/ENA/ENA/Source/Scenes/AppDisabled/AppDisabledViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppDisabled/AppDisabledViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/UpdateOS/UpdateOSView.swift
  src/xcode/ENA/ENA/Source/Scenes/UpdateOS/UpdateOSViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/UpdateOS/UpdateOSViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/UpdateOS/ENAUITests_08_UpdateOSUITests.swift
Labels: feature

#1821 Bump to next Version 1.11.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1824 Chore/release 1.12.x merge party 🥳
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcbaselines/85D7595324570491008175F0.xcbaseline/4D380FF7-7C4B-42F6-833F-6B98345B5DEA.plist
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Extensions/HTTPURLResponse+Header.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/StatisticsMetadata.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryContactPerson.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryEntry.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryEntryType.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/LocationVisit.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryEntryTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryLocationTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/StatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.bin
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.sha256
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store+Statistics.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/fastlane/Fastfile
Labels: admin

#1826 Update Localizable.strings #EXPOSUREAPP-46694669
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1819 Feature/xxx task risk calculation migration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/Models/RiskCalculationResultTests.swift
Labels: feature

#1835 Fix/4686 compressed text
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
Labels: bug

#1806 Fix/4602 Delta Onboarding Close Button Doesn't Work
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/V15/DeltaOnboardingV15ViewController.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: bug

#1834 Feature/4699 task pass risklevelper date to view
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+ContactDiary.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/HistoryExposure.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: feature

#1836 fix/2566 Removed Prefix +49 From Phone Numbers
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: Fix 1.12

#1831 Fix loading state in exposure detection view controller
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
Labels: bug

#1812 iOS 12.5: Shifted Views on table view cell reuse
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/UIStackView+prune.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionRiskCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionRiskCell.xib
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/Cell/RiskLegendDotBodyCell.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/Cell/RiskLegendDotBodyCell.xib
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/__test__/RiskLegendeTest.swift
Labels: bug

#1839 Disable flaky tests and update fastlane
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/Gemfile.lock
Labels: admin

#1837 Feature/106 story exposure history
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high.imageset/Icons_Attention.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high_small.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high_small.imageset/Icon_Attention_High_small.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_low.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_low.imageset/Icons_Attention_gray.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+ContactDiary.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/HistoryExposure.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/RiskLevelPerDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/__tests__/HomeRiskCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/Models/RiskCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#1822 fix/4528 Data Privacy Note Adapted
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#1830 Update Localizable.strings#EXPOSUREAPP-4580
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1832 [iOS] "No Test Result Notifications" does not work
  src/xcode/ENA/ENA/Source/AppDelegate+ENATaskExecutionDelegate.swift
Labels: bug

#1828 fix titles margins in iOS 12.5
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FriendsInvite/InviteFriendsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FriendsInvite/InviteFriendsViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Reset/ResetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Reset/ResetViewController.xib
Labels: bug

#1841 Bugfix/repair cached configuration unit tests
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: admin

#1840 [iOS] Contact Dialy export to Mail: Subject is missing
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryExportItem.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#1825 Feature/task 4610 statistics app store screenshot
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: tests

#1843 Refactoring contact diary store and its unit tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: admin, chore

#1845 Bump to next Version 1.11.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1846 Bump to next Version 1.12.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1838 Feature/4386 translations info screen to anounce new release features
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#1844 Fix/1721 remove trait
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/__test__/DiaryInfoViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewHeader.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewSection.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
Labels: bug

#1842 Fix/4601 log chronological
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogsViewController.swift
  src/xcode/ENA/ENA/Source/Workers/Logging.swift
Labels: bug

#1852 Fix/4375 show large titles correctly
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/DiaryEditEntriesViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#1853 change dateFormatter to utcDateFormatter
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
Labels: admin

#1851 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#1855 [MINOR] Correct a typo in CODEOWNERS file
  CODEOWNERS
Labels: admin

#1856 Fix/4738 screenshot failure
  src/xcode/ENA/ENAUITests/ENAUITests.swift
Labels: admin

#1850 Feature/4386 info screen to anounce new release features
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/I_NeueFunktionen_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/I_NeueFunktionen_light.pdf
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/TracingHistoryTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/NewVersionFeature.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/__tests__/DeltaOnboardingNewVersionFeaturesControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: feature

#1858 fixed UITests; use mock data for statistics
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: admin

#1857 4434-create-screenshots-screen-7
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#1859 Fix/4749 segmented control on 12.5
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.xib
Labels: bug

#1860 Statistical data are not present after restart of the mobile
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProvider.swift
Labels: bug

#1861 Fix/4743 text formatting statistics info screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
Labels: bug, text-change

#1862 Bump to next Version 1.11.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1864 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#1849 Fix/3267 Wrong Environment After Reset
  src/xcode/ENA/ENA/Source/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/Helper/HTTPClient+MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClientTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Coordinator.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBackendConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMServerEnvironmentViewController.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#1865 Bump to next Version 1.11.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1866 Fix/4386 fix info screen new features
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: Fix 1.12

#1863 help windows users to handle compressed tars
  .circleci/config.yml
Labels: admin

#1869 Bump to next Version 1.12.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1870 Bump to next Version 1.13.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#1871 Protocol Buffer update for release 1.13.x at Thu Jan 28 09:13:29 UTC 2021
  proto/resources/internal/ppdd/edus_otp.proto
  proto/resources/internal/ppdd/edus_otp_request_android.proto
  proto/resources/internal/ppdd/edus_otp_request_ios.proto
  proto/resources/internal/ppdd/ppac_android.proto
  proto/resources/internal/ppdd/ppac_ios.proto
  proto/resources/internal/v2/app_config_android.proto
  proto/resources/internal/v2/app_config_ios.proto
  proto/resources/internal/v2/ppdd_edus_parameters.proto
  proto/resources/internal/v2/ppdd_ppac_parameters.proto
Labels: admin

#1867 Screenshot risk detection active states and additional launch argument
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#1872 Label cut off
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
Labels: bug

#1873 fixed font size and color
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#1875 Change of text on risk card
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: feature, text-change

#1881 Remove whitespace in the navigationBar for iOS 12.5
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#1883 Feature/4874-TASK-time check
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/DeviceTimeCheckTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: feature

#1876 Fix/screenshot collection
  .circleci/config.yml
  scripts/announce_screenshots.sh
Labels: bug
