Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-07, with the labels that each got.

#3048 Link to FAQ to find test centers
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Test_Centers.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Test_Centers.imageset/Illu_Submission_Test_Centers-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Test_Centers.imageset/Illu_Submission_Test_Centers.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionIntroViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: feature

#3052 Bump to next Version 2.5.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3053 pass through the eTag
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
Labels: task

#3055 Changes for persistence of saved districts
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#3054 Add UITest for the Flow
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: task

#3049 Feature/7648 7841 task UI tests and screenshots
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#3068 UA Bugfix (EXPOSUREAPP-8218)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3069 Data Privacy and Terms of Use have white background in dark mode
  src/xcode/ENA/ENA/Resources/Localization/style.css
  src/xcode/ENA/ENA/Source/Views/Common/HTMLView.swift
Labels: bug

#3063 Pin date formatter on certificate screen to Gregorian calendar
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
Labels: bug

#3060 Feature/#8024 dcc validation/8103 decoding rule set
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/MockDigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Constants.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/CertLogic+Fakes.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/OnboardedCountriesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/Ressources/dcc-validation-rule.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/ValidationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/ValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Validation/ValidationRulesAccessTests.swift
Labels: task

#3070 Show correct error code for HC_PREFIX_INVALID
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
Labels: bug

#3061 Feature/dcc validation data structure
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/DCCValidationService.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/MockHealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/Model/DCCValidationError.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/Model/DCCValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/Model/HealthCertificateValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/Model/ValidationOnboardedCountriesError.swift
Labels: chore

#3071 Fix/8217 app crash re-checkin
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
Labels: bug

#3066 ASCII control characters allowed in check-in QR-code address and description
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
Labels: bug

#3081 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#3078 No Space possible in RAT Test Profile
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
Labels: bug

#3076 Fix/8215 UI glitches in webviews
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Views/Common/HTMLView.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: bug

#3077 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3080 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Labels: text-change

#3072 Adjust CardView shadows
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeCardView.swift
Labels: enhancement

#3079 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3073 Inserting non-breaking spaces(EXPOSUREAPP-8120)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#3074 Updating-FAQ-Link(EXPOSUREAPP-8216)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
Labels: text-change

#3075 Updating-FAQ-Link(EXPOSUREAPP-8216)
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
Labels: text-change

#3085 Updating Button Text(EXPOSUREAPP-8216)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3083 Fix/add more logg for error in enf 2.5
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
Labels: chore

#3086 Bump to next Version 2.5.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3084 Fix/certificate header optionality
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/CBORWebTokenHeader.swift
Labels: chore

#3046 Feature/8191 profile edit delete buttons
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2977 CoronaTestService Refactoring
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Async Operation/AsyncOperation.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestResultOperation.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug, feature

#3090 Assign correct app string for yesterday on fully vaccinated card
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3094 Shortening the Text for Statistics Card
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3098 Change preferred person switch description
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
Labels: feature

#3099 Add localizable string
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: task

#3051 Feature/8193 Implement edit profile functionality.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputDescriptionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/__tests__/CreateAntigenTestProfileViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: task

#3102 Feature/8238 1 of 1 hint
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3107 Bump to next Version 2.5.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3059 Feature/#8096 validation onboarded countries
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ValidationOnboardedCountries.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DCCValidationService/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/MockHealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/ValidationOnboardedCountriesCache.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/ValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/__tests__/HealthCertificateValidationServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/OnboardedCountriesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/OnboardedCountriesCBORDataFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Validation/OnboardedCountriesAccessTests.swift
Labels: task

#3111 Add missing legal text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3105 Error Report - EN Legal text with wrong button text
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
Labels: bug

#3106 Several character rendering erros: "z.u00A0B." instead of "z. B."
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#3058 Feature/8202 edit profile UI test
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3091 Add unit test for input view model.
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/__tests__/CreateAntigenTestProfileViewModelTests.swift
Labels: task

#3109 Feature/8025 dcc validation ux/8095 coordinator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/ValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: task

#3110 UA Bugfix(EXPOSUREAPP-8250)
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#3104 UA Bugfix(EXPOSUREAPP-8265)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
Labels: text-change

#3113 Feature/7651 edit profile
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputDescriptionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/__tests__/CreateAntigenTestProfileViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#3100 Feature/#8096 dcc rule validation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetDccRules.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/ValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/ValidationRulesCache.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/__tests__/HealthCertificateValidationServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/ValidationRulesAccess.swift
Labels: task

#3114 Add keyboard subscriptions only to screens with textfields
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
Labels: bug

#3116 Several character rendering erros: "z.u00A0B." instead of "z. B."
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#3117 Typo in Check-in
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#3126 Fix/8260 add meaningful entries to screenshots
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#3124 fix/#8326-missing-permission-screen
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#3127 Add Screenshots to new statistics cards
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: bug

#3112 Add correct message in case of no network
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+AuthorizationOTPElsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3133 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3119 Feature/8067 adjust info screen to announce new release features for 2.6
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3134 Antigen test fix
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
Labels: bug, tests

#3137 Bump to next Version 2.6.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3130 Positive Test Result - swipe down moves the buttons
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
Labels: bug

#3145 fix deletion problem in the cell
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#3122 Feature/#8305 8241 validation service refactoring + adopt new tech spec changes
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/MockHealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/HealthCertificateValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/HealthCertificateValidationRuleType.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/ValidationRulesCache.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/Model/HealthCertificateValidationOnboardedCountriesCache.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/Model/HealthCertificateValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/__tests__/HealthCertificateValidationOnboardedCountriesProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationService/Model/HealthCertificateValidationReport.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/CertLogic+Equatable.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/CertLogic+Fakes.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/MockValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/OnboardedCountriesCBORDataFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/ValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Validation/ValidationRulesAccessTests.swift
Labels: task

#3144 Feature/#5612 Translucent Tab Bar (Implements #2159)
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: community

#3141 Feature/#8381 change country codes
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/MockHealthCertificateValidationService.swift
Labels: task

#3143 UA Bugfix
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3147 Chore/fix flaky UI tests
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/HTTPClientCertificatePinningTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: admin, chore

#3148 Feature/#8382 value set change
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueSetsProvider.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueSetsProviding.swift
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/__tests__/VaccinationValueSetsProvidingTests.swift
Labels: feature

#3150 REVERT - Positive Test Result - swipe down moves the buttons
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
Labels: bug

#3142 Event Creation - manual called info screen and using the "x" has two issue
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#3123 Feature/8025 dcc validation ux/8245 validation screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/info.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/info.imageset/info.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/CountrySelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/ValidationDateSelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_42_ValidateHealthCertificate.swift
Labels: feature

#3121 Feature/7622 adapt privacy notice for release 2.6
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#3128 Feature/#8101 validation service unittests
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
Labels: task

#3146 Cell selection doesn't disappear on FAQ card
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#3136 Correct the Sorting
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: bug

#3151 Feature/8025 dcc validation ux/8246 validation result screens
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Failed.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Failed.imageset/Icon_CertificateValidation_Failed.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Failed.imageset/Icon_CertificateValidation_Failed_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Open.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Open.imageset/Icon_CertificateValidation_Open.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CertificateValidation_Open.imageset/Icon_CertificateValidation_Open_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Invalid.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Invalid.imageset/Illu_Validation_Invalid.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Invalid.imageset/Illu_Validation_Invalid_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Unknown.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Unknown.imageset/Illu_Validation_Unknown.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Unknown.imageset/Illu_Validation_Unknown_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Valid.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Valid.imageset/Illu_Validation_Valid.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Illu_Validation_Valid.imageset/Illu_Validation_Valid_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Extensions/SAP_Internal_Dgc_ValueSet+DisplayText.swift
  src/xcode/ENA/ENA/Source/Extensions/SAP_Internal_Dgc_ValueSets+ValueSetType.swift
  src/xcode/ENA/ENA/Source/Extensions/UITableView/UITableViewController+Enum.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/ConfigureableCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DismissHandlingNavigationController/DismissHandlingNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHeadlineWithImageCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/InformationScreen/ValidationInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/DynamicCell+ValidationResult.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/TechnicalValidationFailedRulesTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateTechnicalValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/RecoveryEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/TestEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/MockHealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/HealthCertificateValidationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/MockHealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/Model/HealthCertificateValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: feature

#3120 Bug/8232 text size and layout glitches using large fonts
  src/xcode/ENA/ENA/Source/Extensions/NSAttributedString+BulletPoint.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController/SendErrorLogsViewModel.swift
  src/xcode/ENA/ENA/Source/Views/AccessibleStackView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalCell.swift
Labels: bug

#3154 gem updates
  src/xcode/Gemfile.lock
Labels: chore

#3158 Bump to next Version 2.6.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3157 Show rule version with identifier
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
Labels: feature

#3160 use cache for 304 in every case
  src/xcode/ENA/ENA/Source/Services/VaccinationValueSets/VaccinationValueSetsProvider.swift
Labels: bug

#3155 Feature/8400 Store selected date and country permanently.
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/ValidationDateSelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3166 Feature/8330 signature check/8425 apis and protocols
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/HealthCertificateSignatureVerificationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/HealthCertificateSignatureVerifying.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/MockHealthCertificateSignatureVerificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidityState/HealthCertificateValidityState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidityState/HealthCertificateValidityStateProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidityState/MockHealthCertificateValidityStateService.swift
Labels: task

#3164 Feature/8409 fix ui tests for local statistics
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/DeleteCircle.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/ManageStatisticsCellTests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: enhancement

#3167 Fix/8432 external link crash
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Button Colors/ENA Button Primary Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Text Colors/ENA Text Tint Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/NSMutableAttributedString+Link.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateTechnicalValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3168 UA Text Change(EXPOSUREAPP-8403)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3172 added check for recoveryEntry uniqueCertificateIdentifier
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
Labels: bug

#3165 fix/7762 Insert hint row if needed.
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
Labels: bug

#3170 Feature/7087 8415 small fixes after feedback
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/SelectedLocalStatisticsTuple.swift
Labels: enhancement

#3152 Positive Test Result - swipe down moves the buttons
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/__tests__/FooterViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/__tests__/FooterViewModelTests.swift
Labels: bug

#3173 Bump to next Version 2.6.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3175 Feature/8449 Use the country code as fallback if there is no localized name.
  src/xcode/ENA/ENA/Source/Models/Exposure/Country.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
Labels: task

#3156 Feature/#8305 8220 unit tests cert logic engine
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/TestData/CertLogicEngineTestData.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/TestData/dcc-validation-rules-common-test-cases.json
Labels: task

#3177 Use the country code as fallback if there is no localized name.
  src/xcode/ENA/ENA/Source/Models/Exposure/Country.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
Labels: task

#3171 Update manage Cell UI
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/ManageStatisticsCellTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3180 Feature/8332 add technical validity to certificates details
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateExpirationDateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateExpirationDateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3176 3D Touch / Haptic touch allows bypass of check-in legal information
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
Labels: bug

#3178 Feauture/8420 interface signature validation
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Equatable.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Fakes.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/MockValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/OnboardedCountriesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/Ressources/dcc-validation-rule.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerification.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerificationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/Model/DCCSigningCertificate.swift
Labels: task

#3183 Bump to next Version 2.6.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3181 Change validation screen button title
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#3193 Fix/8454 number of vaccinations
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
Labels: bug

#3192 PCR+RAT DGC Redeemed have issue with certificate screenflow
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#3191 Fix/8456 accept float dates
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Access/DigitalCovidCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Access/DigitalCovidCertificateFakeTests.swift
Labels: bug

#3198 Title Change(EXPOSUREAPP-8422)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#3197 Improve wording of certificate QR code scanner
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3186 Remove "." from notification title (COMMUNITY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, text-change

#3199 added keyboard avoidance
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewController.swift
Labels: bug

#3196 Error Log - Button hidden due to taskbar
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.xib
Labels: bug

#3195 UI artifacts from custom incidence locations when offline during onboarding
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#3201 updated Protocol Buffer files for DSCList
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/dgc/dsc_list.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_android.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
Labels: feature

#3204 Disable failing UITests temporarily
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: bug

#3202 Fix/8435 fetch statistics for an entire federal state
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsDistrict.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsFederalState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsRegion.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/RegionType.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/SelectedLocalStatisticsTuple.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/SevenDayData.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/LocalStatisticsStateTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#3209 Fix/8475 add screenshots for local statistics
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.xib
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: bug, tests

#3212 Bump to next Version 2.6.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3182 Fix/#8397 validation result unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/__tests__/HealthCertificateValidationResultTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/__tests__/ValidationResultCellModelTests.swift
Labels: task

#3208 Update legal texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#3215 Use launch arguments only in UI tests
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#3214 add new screenshot test to the testplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: bug

#3219 Update CertLogic dependency
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: chore

#3207 Wrong texts used
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3211 Update TUR legal strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#3210 Update EN legal strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
Labels: text-change

#3220 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3218 Feature/8407 manage statistics voice over
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/DeleteCircle.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/ManageStatisticsCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: accessibility, enhancement

#3221 Feature/8025 8248 UI tests screenshots
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/MockHealthCertificateValidationService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_42_ValidateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Validation/CertLogic+Fakes.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#3223 Chore/use UI button for deletion updated
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/delete.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/delete.imageset/delete.pdf
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
Labels: bug

#3225 Bump to next Version 2.6.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3216 UA Bugfix(EXPOSUREAPP-8518)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3226 Bump to next Version 2.6.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3228 Fix/8538 disable add statistics button at maximum count
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/DeleteCircle.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/ManageStatisticsCellTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: bug

#3230 enforce end editing before pushing a viewController to make sure the …
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#3194 Feature/8430 invalid signature scanner errror
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/HealthCertificateSignatureVerificationError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/HealthCertificateSignatureVerifying.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateSignatureVerification/MockHealthCertificateSignatureVerificationService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerification.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerificationError.swift
Labels: feature

#3229 Harmonize "Zertifikats" usage
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3235 Bump to next Version 2.6.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3234 Minor fixes in privacy agreement(EXPOSUREAPP-8552)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3236 Fix/8548 vaccination entry labels
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
Labels: bug

#3237 Update fastlane to 2.188.0
  src/xcode/Gemfile.lock
Labels: chore

#3238 Minor fixes in privacy agreement(EXPOSUREAPP-8552)
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#3239 validation pass count only ruleType acceptence
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
Labels: bug

#3244 Fix double "die" (COMMUNITY)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, text-change

#3240 show empty values as well
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
Labels: bug

#3206 Feature/8440 dsc list request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListProviding.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/__tests__/DSCListProvidingTests.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/default_dsc_list.bin
Labels: feature

#3224 Feature/8419 dsc list provider
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListMetaData.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListProvider.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListProviding.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/Default/default_dsc_list.bin
  src/xcode/ENA/ENA/Source/Services/DSCList/__tests__/DSCListProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/Model/DCCSigningCertificate.swift
Labels: feature

#3245 Fix/8446 local statistics deletion improvement
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/LocalIncidence.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/LocalIncidence.imageset/LocalIncidence-Dark.pdf
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TraceLocations/HomeTraceLocationsTableViewCell.xib
Labels: bug

#3246 noResponse error will get handled as noConnection now
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/__tests__/HealthCertificateValidationOnboardedCountriesProviderTests.swift
Labels: bug

#3250 Fix/fallback to countrycode on result
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/__tests__/ValidationResultCellModelTests.swift
Labels: bug

#3251 Update CertLogic package
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: bug

#3249 only save statistics ID after successful fetch
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
Labels: bug

#3247 Feature/8429 validity state management
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateValidityState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidityState/HealthCertificateValidityStateProviding.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidityState/MockHealthCertificateValidityStateService.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task

#3255 reuse textWithLinks cell, removed and move text assets
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateTechnicalValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3248 Feature/use dsc list provider
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/MockDSCListProvider.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/TestCertificateRequest.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task
