Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-06, with the labels that each got.

#2786 Fix for the "year 2262" issue
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/CreateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
Labels: bug

#2750 Feature/#6124 ppa event registration/#7305 implementation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAMostRecentData.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsActualData.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/RiskLevel.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/__tests__/RiskExposureMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/Model/CheckinRiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsSubmissionCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsTestResultCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature, task

#2809 Missing "Auswahl" on selected person
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
Labels: accessibility, bug

#2815 fixed local linter script
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2810 Fix/7554 wrong screen after TAN input
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENAUITests/AppDelegate/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: bug

#2823 Bump to next Version 2.4.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2824 Bump to next Version 2.3.2.0
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2821 Feature/7500 rsa key pair generation
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CryptoFallbackTests.swift
  src/xcode/ENA/ENA/Source/Client/Security/iOS 12 Fallback/CryptoKitFallbacks.swift
Labels: task

#2816 Feature/#6608 data beeing downloaded again unittest
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningPackageDownloadTests.swift
Labels: chore

#2820 Feature/7498 add submission screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_01.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_01.imageset/icon_certificate01.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_01.imageset/icon_certificate01_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_02.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_02.imageset/icon_certificate02.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_02.imageset/icon_certificate02_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_Certificate.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_Certificate.imageset/Test_Certificate_Illustration_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_Certificate.imageset/Test_Certificate_Illustration_Light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/Dateformatter+vCard.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/Cell/BirthdayDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/__tests__/ExposureSubmissionTestCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENATextField.swift
Labels: feature

#2817 Feature/7497 adjust text on existing screens
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionQRInfoModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2829 Feature/7340 test certificate/7511 decrypt assemble compress encode
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/DigitalGreenCertificate+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Constants.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/AESEncryption.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/String+Utils.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Utils/AESEncryptionTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Utils/Data+CompressionTests.swift
Labels: task

#2825 Feature/#7499 extend registration token request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+RegistrationTokenTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/ExposureSubmissionParsable.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/AntigenTestQRCodeInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/AntigenTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/AntigenTestInformation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/AntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestCertificateConsent.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestedPerson.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/AntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/PCRTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionError.swift
Labels: task

#2834 Use new button titles for cancel dialog
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2838 fix/7602 fix wordings for certificate tab
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2832 Feature/7349 adjust info screen to announce new release features for 2.4
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2836 Add prefix.
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
Labels: bug

#2818 After App Reset with a positive Test: Error 9 occurs during the onboarding
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#2827 PCR+RAT redeemed with redeemed Popup but they are scanned
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#2828 Feature/7187 add delete button remove positive test/storybranch
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: feature

#2845 Fix/pinning tests
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/HTTPClientCertificatePinningTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/SmokeTests.xctestplan
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: chore

#2842 CWA crashes at Start
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/SQLiteKeyValueStoreTests.swift
Labels: bug

#2847 Run SecTrustEvaluateAsyncWithError on session queue
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
Labels: bug

#2835 Feature/7502 register rsa request
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Environment/Environments.default.json
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DccRegisterPublicKeyTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Environment/Environments.swift
  src/xcode/ENA/ENA/Source/Environment/__tests__/TestEnvironments.json
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/RegistrationError.swift
  src/xcode/Gemfile
  src/xcode/Gemfile.lock
Labels: feature

#2843 Generate protobuf models
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
Labels: task

#2837 Feature/#7503 dcc request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetDigitalCovid19CertificateTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/DCCErrors.swift
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/DCCResponse.swift
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/RegistrationError.swift
Labels: task

#2833 7595/adapting-privacy-policy-2.4
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#2841 Feature/7340 certificate request/7610 screen integration
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
Labels: task

#2852 Fix large title bug on Tan input screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
Labels: bug

#2839 Prevent deleted locations from re-appearing in the contact journal
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Extensions/Checkin+Update.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
Labels: bug

#2854 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#2857 Bump to next Version 2.4.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2846 Possible fix for UI crash
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.swift
Labels: bug

#2855 fix/test for 2.4 release
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: admin

#2851 Adjust text on Antigen pending and negative test result screens
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/certificate-qr-light.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/certificate-qr-light.imageset/certificate-qr-light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/certificate-qr-light.imageset/qr_dark (1).pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/test-result-diary_light.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/test-result-diary_light.imageset/test-result-diary_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/test-result-diary_light.imageset/test-result-diary_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2859 Feature/7088 7515 adjust info screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/icon-smartphone-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/icon-smartphone-light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateInfoViewModel.swift
Labels: text-change

#2858 Statistics with font size issue
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/StackViewLabel.swift
  src/xcode/ENA/ENA/Source/Views/__tests__/StackViewLabelTests.swift
Labels: bug

#2863 VCARD-Display different for iOS and Android
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/__tests__/QRCodeCellViewModelTests.swift
Labels: bug

#2861 Feature/7340 test certificate/7600 cose cleanup
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateFakeTests.swift
Labels: task

#2864 Fix/7680 i os13 crashes
  src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift
Labels: bug

#2867 Bump to next Version 2.4.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2874 Logging, small fixes
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: task

#2866 Feature/7340 test certificate/xxxx extend unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DccRegisterPublicKeyTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetDigitalCovid19CertificateTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
Labels: tests

#2879 Fix/7704 asset wrong resolution
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_green.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_green.imageset/Test_green.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Test_green.imageset/Test_green.png
Labels: bug

#2880 Feature/760x better package integration
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Constants.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/XCTestManifests.swift
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: chore, enhancement

#2876 Feature/7640 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateInfo/TestCertificateInfoCellModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
Labels: task

#2878 Hide button when already warned others
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
Labels: bug

#2877 Text adjustments (EXPOSUREAPP-7665)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2884 Bump to next Version 2.4.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2885 UA Bugfix Spelling
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#2886 feature/7708 Add faq link to error alert.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificate/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2882 Text adjustments legal texts (EXPOSUREAPP-7665)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#2887 Translucent Tab Bar (Implements #2159)
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: community

#2889 Fix/7740 json schema bg se
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
Labels: bug

#2890 Fix/7702 wrong date in contact jounal
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#2888 Fix link to FAQ on low risk encounter (Fixes #2510)
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
Labels: community

#2892 Fix/7707 Remove views from superview, before adding them again.
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
Labels: bug

#2893 Bump to next Version 2.3.0.13
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2894 Bump to next Version 2.4.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2897 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2896 Show the timetravel warning only once in foreground.
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#2895 Fix/7690 Add default date to birthday pickers.
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/Cell/BirthdayDatePickerCell.swift
Labels: bug

#2900 Check that model is there when reloading too early on iOS 12
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#2860 Vaccination certificate: Name determined incorrectly when parts are missing
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
Labels: bug

#2872 Event Creation - manual called info screen and using the "x" has two issue
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Info/TraceLocationsInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#2901 Statistics - dark mode - text with black background color
  src/xcode/ENA/ENA/Source/Views/StackViewLabel.swift
Labels: bug

#2902 Dont set the Textcolor in xib since it overrides the color on 12.5
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionImageCardCell.xib
Labels: bug

#2903 Add certificates tab app store screenshot
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: chore

#2911 Bump to next Version 2.5.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2912 Bump to next Version 2.4.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2904 Feature/7340 certificate request/7639 unit tests 2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Security/DCCRSAKeyPair.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/DCCRSAKeyPairTests.swift
  src/xcode/ENA/ENA/Source/Extensions/CertificateDecodingError+Equatable.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateRequest/TestCertificateRequestCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HomeHealthCertificateRegistrationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HomeHealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/TestCertificateInfoCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/TestCertificateRequestCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/TestCertificateRequest.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/MockDigitalGreenCertificateAccess.swift
Labels: task

#2905 Fix/failing UI test
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: chore

#2909 Fix/health certificate validation
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
Labels: task

#2914 Information disclosure of users meta data and reputational risk due to usage of in-app browsing functionality
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionDetailTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/BackgroundAppRefreshViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Workers/LinkHelper.swift
  src/xcode/ENA/ENA/Source/Workers/Update Checker/AppUpdateCheckHelper.swift
Labels: bug

#2916 wrong Icons on "Ihr Einverständnis"
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
Labels: bug

#2922 Fix/#7828 tan is not registered as pcr in contact journal
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
Labels: bug

#2921 UA Bugfix (EXPOSUREAPP-7834)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2910 Fixed Test Plans
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: bug

#2913 Add failure logs to URL session requests
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
Labels: enhancement

#2920 Feature/7833 recovery certificate data structure
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateFakeTests.swift
Labels: task

#2925 Bump to next Version 2.4.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2926 put in some infos when ELS is turned on
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
Labels: chore

#2931 Fix/make release branch green again
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: chore

#2932 improve storage a bit
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#2930 Bug/7205 escaping v card bsi issue
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/__tests__/QRCodeCellViewModelTests.swift
Labels: bug

#2937 Fix/7849 certificate tab badge
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#2934 Feature/7648 family/7814 preparation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/RecoveryEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
Labels: task

#2936 Feature/7648 family/7820 show detail screen after scanning
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: bug

#2928 Fix/7854 Handle the result of registerHealthCertificate()
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: bug

#2915 Fix/health certificate access cleanup
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/DigitalGreenCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/Error.swift
Labels: chore

#2943 Bump to next Version 2.4.0.11
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2945 Fix/7878 Make dateTimeOfTestResult optional.
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
Labels: bug

#2938 Adapt privacy policy for release 2.5
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: text-change

#2923 Feature/7833 recovery certificate data structure tests
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/DigitalGreenCertificateAccessTests.swift
Labels: task

#2947 Minor Text Changes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2940 Adapt naming inconsistencies
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2951 Fix/#7862 black white screen
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#2953 Removed word
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2950 Fix/7831 vaccination validity
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HomeHealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#2952 Add value set support for test name and manufacturer
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
Labels: bug

#2944 feature/7836 FAQ-Link if Certificate is not available
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/TestCertificateRequest.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#2906 Feature/7086 statistic data for vaccinations
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/AtleastOneVaccinated.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/AtleastOneVaccinated.imageset/Einmal_geimpft_d.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/AtleastOneVaccinated.imageset/Mindestens_geimpft.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Doses.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Doses.imageset/Impfdosen_d.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Doses.imageset/Verabreichte_Impfosen (1).pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/FullyVaccinated.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/FullyVaccinated_d.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Extensions/SAP_Internal_Stats_KeyFigure+Formatting.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCard.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_Statistics+SupportedIDsTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: feature

#2956 Bump to next Version 2.4.0.13
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2959 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2961 UA Bugfix
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2948 Quicktest Profile Tile gets not reset on app reset
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: bug

#2939 Feature/7646 certificates detail screens/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/green-stars.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/green-stars.imageset/green stars.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/stars.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/stars.imageset/stars.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Views/GradientBackgroundView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateKeyValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/__tests__/HealthCertificateKeyValueCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: feature

#2966 added new text cells to statistics information screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2960 Add mocked Statistics
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/StatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.bin
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/sample_stats.sha256
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/stats.bin
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: bug

#2949 Test Certificate Details - First Name Last Name instead of other way around
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
Labels: bug

#2968 ENALabel: Remove default style
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENALabel.swift
  src/xcode/ENA/ENA/Source/Views/StackViewLabel.swift
Labels: bug

#2963 Feature/7647 recovery certificate/7961 details screen
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
Labels: feature

#2970 wrong order?
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: admin, chore

#2957 Fix Swiftlint on Xcode 12.5
  .circleci/config.yml
  .gitattributes
  .gitignore
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
  vendor/README.md
  vendor/swiftlint
Labels: enhancement

#2971 Rename key
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#2962 Feature/7648 family/7840 preferred person and certificate
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/TestEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArrayMostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
Labels: task

#2973 Minor Text Change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2974 Fix/crash when showing error
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#2929 Feature/7649 adjust info screen to announce new release features for 2.5
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2978 Feature/7647 recovery certificate/storybranch
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
Labels: feature

#2976 Linking to English Version of Government Website
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#2981 Hot Fix legal text changes
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: bug, text-change

#2946 display issues on TAN-Eingabe
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/__tests__/TopBottomContainerViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
Labels: bug

#2972 Feature/7953 layout fix in statistics cells
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
Labels: enhancement

#2982 Linking to Website - English (EXPOSUREAPP-8009)
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#2986 Feature/7648 family/7842 new card design
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/EUStarsGroup.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/EUStarsGroup.imageset/lightStarsNew.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/green-stars.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/green-stars.imageset/green stars.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HomeHealthCertifiedPersonTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HomeHealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENALabel.swift
  src/xcode/ENA/ENA/Source/Views/CardView.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: feature

#2987 Adjust German Translation of EU Certificate
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2988 Fix/4573 installed days
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
Labels: bug

#2980 Use DCCDateStringFormatter for dateOfFirstPositiceNAAResult and dateOfBirth
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
Labels: task

#2985 Fix SAP internal ci
  README.md
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2983 handle different UIDatePicker-UITest behavior for ios 14.4 and ios 14.5
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: chore

#2992 set errorCorrectionLevel to .medium in QRCodes for HealthCertificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
Labels: enhancement

#2989 removed non needed views, moved border to bottom view to improve layo…
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: feature

#2995 Fix/4348 ns progress again
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
Labels: bug

#2993 Fix/#7858 els logging for testers
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMErrorLogSharing/DMErrorLogSharingViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMErrorLogSharing/DMErrorLogSharingViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Extensions/StringInterpolation+Private.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: feature

#2994 remove LaunchArgument for statistics
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: bug

#3001 Updated with new official name
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3006 UA Bugfix
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3000 Icons Toggled on PCR/RAT > "COVID-Testzertifikat"
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
Labels: bug

#3003 Feature/7087 statistic data local 7 day incidence/7687 UI 7 day local incidences
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddLocalStatisticsModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/AddStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/AddStatisticsCardView/LocalStatisticsFederalState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/__tests__/SelectValueCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: task

#2999 PCR Redeemed has issue with certificate screenflow
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewController.swift
Labels: bug

#3004 i18n keys for certificate info screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2990 Vaccination certificate accepted with empty mandatory fields
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Model/DigitalGreenCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Ressources/CertificateSchema.json
Labels: bug

#3010 Feature/7648 TASK 7813 update info screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/icon_export_textformat.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/icon_export_textformat_dark.pdf
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/__tests__/HealthCertificateConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: feature

#3009 Fix/7113 log export reloaded
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogging/LogDataItem.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#3002 Feature/7087 statistic data local 7 day incidence/7692 fetch local statistics
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsMetadata.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/__tests__/LocalStatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/__tests__/sample_local_statistics/default_local_statistics.bin
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2991 Fix/7973 html display
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/style.css
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHtmlCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HTMLViewController/HTMLViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HTMLViewController/HTMLViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.xib
  src/xcode/ENA/ENA/Source/Views/Common/HTMLView.swift
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
  src/xcode/ENA/ENA/Source/Views/__tests__/HTMLViewTests.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: enhancement

#3007 Feature/7648 family/7837 person screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/CurrentlyUsedCertificate_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/CurrentlyUsedCertificate_Icon_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/RecoveryCertificate_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/RecoveryCertificate_Icon.imageset/RecoveryCertificate_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Background.imageset/TestCertificate_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/TestCertificate_Icon.imageset/TestCertificate_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Background.imageset/VaccinationCertificate_CompletelyProtected_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_CompletelyProtected_Icon.imageset/VaccinationCertificate_CompletelyProtected_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Background.imageset/VaccinationCertificate_FullyVaccinated_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Icon.imageset/VaccinationCertificate_FullyVaccinated_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Background.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Background.imageset/VaccinationCertificate_PartiallyVaccinated_Background.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_PartiallyVaccinated_Icon.imageset/VaccinationCertificate_PartiallyVaccinated_Icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon - Teilschild.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon - Vollschild.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon - Vollschild.imageset/Icon - Vollschild.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateKeyValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateKeyValueTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/__tests__/HealthCertificateKeyValueCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HomeHealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task

#3020 Bump to next Version 2.5.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3019 Fixing UI tests and screenshots after new flow.
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: screenshots, tests
