Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-09, with the labels that each got.

#3452 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3453 Feature/9171 adjust info screen for release 2.10
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: feature

#3456 Update Xcode/Fastlane
  .circleci/config.yml
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
Labels: admin

#3454 Fix/test testOnBehalfCheckinSubmissionWithQRCodeScan
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_OnBehalfCheckinSubmission.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: admin

#3445 Feature/9119 booster notification/9212 rule check
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/CBORWebTokenHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificateWithHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Protocol.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/Ressources/dcc-validation-rule.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateWithHeaderTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/RuleValidation/ValidationRulesAccessTests.swift
Labels: task

#3411 Scroll to top when clicking on current tab (Implements #2156) (COMMUNITY)
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
Labels: community, mirrored-to-jira

#3457 Skipped HealthCertificateQRCodeViewModelTests tests in all tests plan
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: admin

#3458 Update SnapshotHelper
  src/xcode/fastlane/README.md
  src/xcode/fastlane/SnapshotHelper.swift
Labels: admin

#3462 Feature/9119 booster notification/9210 model extension
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#3466 UA Bugfix(EXPOSUREAPP-9243)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3468 UA Bugfix(EXPOSUREAPP-9263)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3470 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#3464 Feature/9217 booster notifications tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
Labels: task

#3443 Feature/9211 download booster notifications rules
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/Model/HealthCertificateValidationRuleType.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#3461 Fix/9281 #3459 onboarding screens empty space on top
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: community, mirrored-to-jira

#3430 Fix/7385 #2743 large titles change appearance
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FriendsInvite/InviteFriendsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/BackgroundAppRefreshViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.swift
Labels: community, mirrored-to-jira

#3442 Fix/6354 - Too much free space in "Transnational Exposure Logging" screen
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: community, mirrored-to-jira

#3476 Feature/9119 booster notification/9219 add notification routing
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route+Equatable.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMButtonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMLocalNotificationsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.xib
Labels: task

#3480 Fix/9168 update privacy policy for 2.10
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#3482 UA Bugfix(EXPOSUREAPP-9310)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3477 Fix/9268 crash corona test service
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
Labels: bug

#3481 Feature/9119 booster notification/9218 invalid signature notifications
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/HealthCertificateValidationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#3486 Update dependencies of JSONSchema and CertLogic.
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: task

#3487 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3488 review fixes
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: chore

#3490 Feature/9119 booster notification/9214 UI extension
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/CurrentlyUsedCertificate_Icon.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Extensions/CertLogicRule+LocalizedDescription.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3489 Feature/9312 routing the booster notification
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route+Equatable.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificateWithHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/BoosterNotificationRuleValidationError+Equatable.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
Labels: task

#3491 Feature/9311 booster notification unit tests
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/MockBoosterRulesAccess.swift
Labels: task

#3479 Feature/9213 trigger booster notifications
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route+Equatable.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificateWithHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/BoosterNotificationRuleValidationError+Equatable.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/MockBoosterRulesAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
Labels: task

#3498 Bump to next Version 2.10.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3499 Fix/9345 refactor booster notifications review comments
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificateWithHeader.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/BoosterNotificationRuleValidationError+Equatable.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/ValidationRulesAccess.swift
Labels: bug

#3500 Feature/6001 remove do not allow button
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Onboarding/OnboardingInfo.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: task

#3463 Fix/9280 reset scenario for community build with the MockENManager
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/MockENManager.swift
Labels: community, mirrored-to-jira

#3473 Large and normal title size for DataDonationViewController
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsCoordinator.swift
Labels: community

#3503 Fix/9349 submission timeintervall change
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: bug

#3501 Add new texts and icons for risk details screen.
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Shield.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Shield.imageset/icon-shield.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Thermometer.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Thermometer.imageset/icon-thermometer.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3497 Remove misleading about disabled certificate pinning (closes #3495)
  src/xcode/ENA/ENA/Source/Extensions/URLSession+Default.swift
Labels: documentation, community, chore

#3502 Feature/9290 change relevant contact duration
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayEntryCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/ContactPersonEncounter.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV4/ContactDiaryMigration3To4Tests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3505 Include name on title of person screen
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
Labels: bug

#3507 Feature/9215 booster notifications dev menu extension
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterChoosePersonViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterChoosePersonViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/BoosterNotificationRuleValidationError+Equatable.swift
Labels: task

#3504 Certificate notification badge improvement
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/CertificateBadgeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
Labels: task

#3510 Add handling vor COSE entries without tag 18.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateAccessTests.swift
Labels: bug

#3508 Bump to next Version 2.11.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3483 Chore/3474 - navigation items for TopBottomContainer VC
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
Labels: community

#3516 Bump to next Version 2.9.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3517 Fix/9400 improve qr legibility
  src/xcode/ENA/ENA/Source/Extensions/UIImage+QRCode.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Details/Cells/TraceLocationDetailsQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeView.swift
Labels: bug

#3518 UA Bugfix(EXPOSUREAPP-9382)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3519 Show correct screen from booster notification
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#3521 Synchronizing of Geräteeinstellungen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3524 Bump to next Version 2.9.1.0
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3523 Text Change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3525 Adjustment of Release Note
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3522 Feature/9119 booster notification/9348 performance
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterChoosePersonViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: task

#3526 Fix/9400 scale factor fixing
  src/xcode/ENA/ENA/Source/Extensions/TraceLocation+GenerateQRCode.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Details/TraceLocationDetailsViewModel.swift
Labels: bug

#3527 fix/9434-crash-when-export
  src/xcode/ENA/ENA/Source/Extensions/UIImage+QRCode.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/__tests__/QRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
Labels: bug

#3475 feature/5572-click tabbar scroll to top shows large titles
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/App/__test__/NavigationControllerViewScrollingTest.swift
Labels: community

#3528 Replace vaccination icon
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Shield.imageset/icon-shield.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - VaccinatedArm.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - VaccinatedArm.imageset/icon-vaccinatedarm.pdf
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
Labels: task

#3514 Fix/9454 - Hide back button on root view controllers for the tabs
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: community, mirrored-to-jira

#3530 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#3531 Bump to next Version 2.10.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3536 Add missing text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3537 Feature/9119 booster notification/9216 screenshots
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3542 Overhaul PDF generation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/CGPDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/TraceLocation+GenerateQRCode.swift
  src/xcode/ENA/ENA/Source/Extensions/UIImage+QRCode.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/CGPDFDocument+EmbedImageTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
Labels: bug

#3535 Feature/9389 create technical behavior for qr scanner
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/HealthCertificateQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/TorchMode.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
Labels: task

#3534 Feature/9119 booster notification/9346 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/CertLogicRule+LocalizedDescription.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/CertLogicRule+LocalizedDescriptionTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/VaccinationHintCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/Cells/ValidationResultCellModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: task

#3544 version bump for TestFlight to 2.10.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3540 Feature/8395 qrscanner/9388 new UI scanner
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/bolt.fill.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/bolt.fill.imageset/bolt.fill.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/bolt.fill.imageset/flash.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/bolt.fill.imageset/flash_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flash_disabled.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flash_disabled.imageset/noflash.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flash_disabled.imageset/noflash_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3543 Feature/8395 qrscanner/9390 change submission-flow
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: task

#3545 Fix/9484 no submit while collect in background
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
Labels: bug

#3546 fix/#9484-extend-logging-submitter
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: bug

#3550 Fix Certificate printing in iOS 12
  src/xcode/ENA/ENA/Source/Extensions/CGPDFDocument+EmbedImage.swift
Labels: bug

#3511 Fix 3472 - overlap in headline of contact journal
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/DiaryEditEntriesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/NavigationControllerWithLargeTitle.swift
Labels: community, mirrored-to-jira

#3539 Feature/8395-qrscanner/checkinsCoordinator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
Labels: task

#3549 Feature/9037 adjust info screen release 2.11
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3551 Xcode 13 and other quality of life improvements
  .circleci/config.yml
  .gitattributes
  Brewfile.lock.json
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Snapfile
  vendor/README.md
  vendor/swiftlint
Labels: admin, chore

#3548 chore/cleanup navigation item in the data donation view controller.
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
Labels: community

#3541 Feature/8395 qrscanner/certificate coordinator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
Labels: task

#3554 Feature/9303 adapt privacy policy release 2.11
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#3555 Fix failing Screenshots
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: admin, chore

#3553 Feature/8395 qrscanner/badge notification start tab
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#3552 Feature/9494 qr scanner view model tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
Labels: task

#3557 Fix unit tests
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: admin, chore

#3558 Fixing test_AddStatisticsButton_flow flakiness
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: admin, chore

#3556 Feature/9342 note about qr code cov pass check app
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_CovPass_Check.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_CovPass_Check.imageset/Illu_CovPass_Check.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_CovPass_Check.imageset/Illu_CovPass_Check_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHeadlineWithImageCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/CovPassCheckInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/CovPassCheckInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/__tests__/CovPassCheckInformationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3561 ExposureWindow save/load date as date without calculating it form ageInDays
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/ExposureWindow.swift
Labels: bug

#3562 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3564 Feature/8395 qrscanner/stick coordinators together
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/HealthCertificateQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3565 Filter out exposurewindows older than 14 Days
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
Labels: bug

#3563 Fix test_screenshot_TwoPersonsOneLocationAndMessages on iOS 15
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: admin, chore

#3568 updated i button image
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/infoBigger.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/infoBigger.imageset/i-button.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/infoBigger.imageset/i-button_dark.pdf
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
Labels: bug, chore

#3571 Bump to next Version 2.11.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3572 Bump to next Version 2.12.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3574 Write out CWA
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3575 Bump to next Version 2.10.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3569 Feature/8395 qrscanner/9495 cleanup
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeScanner/__tests__/CheckinQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/HealthCertificateQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/QRCodeScanner/__tests__/HealthCertificateQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/MetadataObject.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/HealthCertificateQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CheckinQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/FakeMetadataMachineReadableObject.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/apple-app-site-association
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#3576 Fix/9638 alert crash
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewController.swift
Labels: bug

#3570 Feature/8395 qrscanner/9560 support big fonts scanner
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
Labels: task

#3581 Add missing empty lines to Localizable.strings file (COMMUNTIY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, text-change

#3588 UA Bugfix(EXPOSUREAPP-9687)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3586 change texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: task

#3566 chore/9599 cleanup navigation items for diary and checkin
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/CheckinsOverviewViewController.swift
Labels: community, mirrored-to-jira

#3590 Fix/xxxx missing texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore

#3585 Feature/9179 adding new statistics tiles
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/hospital_rate_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/hospital_rate_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Intensive_Care.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Intensive_Care.imageset/intensive_care_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Intensive_Care.imageset/intensive_care_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCard.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_Statistics+SupportedIDsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: feature

#3592 Feature/9446 adjust info screen release 2.12
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3593 Feature/9280 scan qr codes from image file/9408 actionsheet
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: task

#3591 Fix broken UI tests
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CryptoFallbackTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: bug

#3580 chore/9599 cleanup navigation items for events planning
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/OnBehalfDateTimeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/Info/OnBehalfInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Info/TraceLocationsInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
Labels: community, mirrored-to-jira

#3596 Feature/9280 scan qr codes from image file/9407 button and text
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/file_button.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/file_button.imageset/FileButton.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Button Colors/IconWithText.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3597 Fix test_screenshot_CreateAntigenTestProfileWithLastCertificate again 😇
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: bug

#3582 fix/6354 remove dark band above image of transnational exposure logging
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/EUSettingsViewModel.swift
Labels: community, mirrored-to-jira

#3584 fix/9661 improve timing of scrollViewToTop
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
Labels: community, mirrored-to-jira

#3602 Fix/9656 crash on second test registration
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: bug

#3603 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3604 Fix/9697 dismiss or pop after deletion
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
Labels: bug

#3587 chore/9599 cleanup navigation items: info screens and RAT profile.
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Info/CheckinsInfoScreenViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateInfoViewController.swift
Labels: community, mirrored-to-jira

#3579 Feature/9316 scanner tab/9635 permission denied handling
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/Cells/__tests__/MissingPermissionsCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/__test__/CheckinsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/__tests__/OnBehalfTraceLocationSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/MissingPermissionCell/MissingPermissionsCellModel.swift
  src/xcode/ENA/ENA/Source/Views/MissingPermissionCell/MissingPermissionsTableViewCell.swift
Labels: task

#3594 Feature/9672 special hud
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/ActivityIndicatorView.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3609 Small Text Change(EXPOSUREAPP-9681)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3595 chore/apple-app-sites-file
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/apple-app-site-association
Labels: admin, chore

#3607 chore/fix-ui-tests
  .circleci/config.yml
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/fastlane/Fastfile
Labels: admin, chore

#3611 Quick actions fix
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
Labels: bug, admin, chore

#3612 updated HUD logic
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerIndicatorView.swift
Labels: feature

#3600 chore/9711 Community build: Improve MockENManager, fix getDiagnosisKeysImpl
  src/xcode/ENA/ENA/Source/Models/Exposure/MockENManager.swift
Labels: community, mirrored-to-jira

#3613 Fixing statistics UI tests
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: tests, chore

#3614 Fix QR-Code tests.
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_OnBehalfCheckinSubmission.swift
Labels: chore

#3608 Feature/9280 scan qr codes from image file/9691 qr code validation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/QRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
Labels: feature
