Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-08, with the labels that each got.

#3286 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3285 Suggestions on Rapid Test Profile (textContentType fields) don't work
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
Labels: bug

#3288 Feature/8692 trigger validity updates
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/ValidationStateServiceTests.swift
Labels: feature

#3280 Feauture/8420 dcc signature validation
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/CertificateDecodingError+Equatable.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerification.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/Model/DCCSignatureVerificationError.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/Model/DCCSigningCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/Model/ExtendedKeyUsageObjectIdentifier.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/ECDSA.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateFakeTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/SchemaValidationTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/RuleValidation/OnboardedCountriesAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/RuleValidation/ValidationRulesAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/SignatureVerification/DCCSignatureVerificationTests.swift
Labels: task

#3293 Feature/8693 update determination of most relevant certificate
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
Labels: feature

#3276 Feature/8330 signature check/8694 notifications
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3294 Protocol Buffer update for release 2.8.x at Mon Aug 2 13:06:25 UTC 2021
  proto/resources/internal/dgc/dsc_list.proto
  proto/resources/internal/pt/check_in.proto
  proto/resources/internal/pt/trace_warning.proto
  proto/resources/internal/submission_payload.proto
Labels: admin

#3296 Feature/8330 signature check/8416 valitity state UI
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiredInvalid.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiredInvalid.imageset/Icon_ExpiredInvalid.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiredInvalid.imageset/Icon_ExpiredInvalid_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiringSoon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiringSoon.imageset/Icon_ExpiringSoon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_ExpiringSoon.imageset/Icon_ExpiringSoon_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_WarningTriangle_blocking.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_WarningTriangle_blocking.imageset/Icon_WarningTriangle_blocking.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_WarningTriangle_small.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_WarningTriangle_small.imageset/Icon_WarningTriangle_small.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateExpirationDateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: task

#3298 Protocol Buffer update for release 2.8.x at Tue Aug 3 08:26:46 UTC 2021
  proto/resources/internal/dgc/dsc_list.proto
Labels: admin

#3299 Add license additions.
  .reuse/dep5
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/ECDSA.swift
Labels: task

#3302 8186 show icao name for certificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
Labels: feature

#3303 Initialize validation button later
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
Labels: bug

#3304 fix/#8798 crash when removing certificate
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
Labels: bug

#3305 Fix/6908 prevent loading UI on bg task
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsTestResultCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#3308 Protocol Buffer update for release 2.8.x at Wed Aug 4 10:41:27 UTC 2021
  proto/resources/internal/pt/check_in.proto
Labels: admin

#3310 Feature/8396 encrypt event check in/8819 update proto buf add new request
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/gen/output/internal/pt/check_in.pb.swift
  src/xcode/gen/output/internal/pt/trace_warning.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
Labels: chore

#3313 Show signature check error code on certificate registration
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
Labels: bug

#3316 another protobuf update
  src/xcode/gen/output/internal/pt/check_in.pb.swift
Labels: chore

#3314 Fix/template header
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/IDETemplateMacros.plist
Labels: community

#3307 Fix/8502 fixing snapshot based tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_14_ValidateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: screenshots

#3312 Feature/8807 signature validation UI unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: task

#3320 Bump to next Version 2.8.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3321 UA Bugfix(EXPOSUREAPP-8552)
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
Labels: text-change

#3319 Feature/8711 adjust info screen to announce new release features for 2.8
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: feature

#3322 UA Bugfix(EXPOSUREAPP-8552)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#3315 Feature/8396 encrypt event check in/8812 extend app configuration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfiguration+Features.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/AppConfiguration+FeaturesTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3323 Update readme to make it clear to use xcworkspace
  README.md
Labels: admin

#3325 Fix/8840 local statistics issues
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/RegionStatisticsData.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/SelectedLocalStatisticsTuple.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/SevenDayData.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/__tests__/LocalStatisticsProviderTests.swift
Labels: bug

#3326 Bump to next Version 2.7.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3330 Bump to next Version 2.7.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3306 Feature/8378 Implement exceptions from schema validation
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Ressources/CertificateSchema.json
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/CBOR+CBORMap.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateAccessTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/SchemaValidationTests.swift
Labels: feature

#3333 Update validity state on didBecomeActive notification
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#3334 Fix/8877 skip signature check for requested certificates
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: bug

#3336 Update default dsc list
  src/xcode/ENA/ENA/Source/Services/DSCList/Default/default_dsc_list.bin
Labels: chore

#3335 Fix/8899 event creation legal text bypass
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#3327 Feature/8396 encrypt event check in/8822 upload check in protected report
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
Labels: feature

#3339 Bump to next Version 2.7.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3338 Fix VoiceOver on certificates tab
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug, accessibility

#3337 Fix/8867 federal state name localization
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/DataDonationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/District.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/LocalStatisticsModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsFederalState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsRegion.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3340 Fix/8404 disappearing certificates
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#3328 Feature/8396 encrypt event check in/8820 checkin encryption
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/AESEncryption.swift
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CheckinEncryption/CheckinEncryptionTests.swift
Labels: task

#3344 Text Change(EXPOSUREAPP-8915)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3348 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3347 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3342 Feature/8396 encrypt event check in/8817 puzzle everything together 2
  src/xcode/ENA.xcworkspace/contents.xcworkspacedata
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/CheckinEncryption.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CheckinEncryption/CheckinEncryptionTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningMatching.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningMatcherTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENASecurity/.gitignore
  src/xcode/ENA/ENASecurity/Package.swift
  src/xcode/ENA/ENASecurity/README.md
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/AESEncryption.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Constants.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/AESEncryptionTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/XCTestManifests.swift
  src/xcode/ENA/ENASecurity/Tests/LinuxMain.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/AESEncryption.swift
Labels: task

#3349 Fix/8919 failing background exposure checks
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#3354 Use decorator to take the debug menu entry into account.
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
Labels: bug

#3355 Fix/8711 changes info screen scope change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3356 UA Bugfix(EXPOSUREAPP-8977)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3353 Feature/8970 http client checkins on behalf
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
Labels: task

#3358 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3357 Feature/8979 blog link info screen for statistic data
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3341 Make logging mockable
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/__tests__/LoggingTests.swift
Labels: community, chore

#3362 Fix/activate background checks iOS 12
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#3361 added some private to the logging
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#3368 Protocol Buffer update for release 2.9.x at Mon Aug 16 16:57:30 UTC 2021
  proto/resources/internal/submission_payload.proto
Labels: admin

#3367 Fix/8498 cannot continue feature screen
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#3369 fix/Change iv to 16 bytes.
  src/xcode/ENA/ENA/Source/Client/Security/CheckinEncryption/CheckinEncryption.swift
Labels: bug

#3366 Fix/8843 clear cache refresh dsc list
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMButtonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDSCList/DMDSCListsController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDSCList/DMDSCListsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListProvider.swift
Labels: feature

#3371 Change text and image for the case of no rules.
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, feature

#3373 Feature/8691 show complete vaccination for recovered people immediately after first vaccination
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/VaccinationProductType.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonKnownVaccinationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonOtherVaccinationProductTypeTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
Labels: feature

#3370 Feature/8881 add screenshots certificate states
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: screenshots

#3376 Fix/9024 UI tests for release 2.7
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
Labels: tests

#3378 Changing the timeout for snapshots
  .circleci/config.yml
Labels: admin

#3375 Feature/8356 warning on behalf/9015 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/__tests__/TraceLocationCheckinViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/OnBehalfDateSelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/__tests__/OnBehalfTraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/OnBehalfDateTimeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/__tests__/OnBehalfDateTimeSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/__tests__/OnBehalfScanQRCodeCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/__tests__/OnBehalfTraceLocationSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/__tests__/TraceLocationSelectionCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/TraceLocationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/ExposureSubmissionCheckinsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/__tests__/CheckinSelectionCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/__tests__/ExposureSubmissionCheckinsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/__tests__/TanInputViewModelTests.swift
Labels: task

#3379 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3380 Bump to next version 2.8.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3384 UA Bugfix(EXPOSUREAPP-9023)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3386 Feature/#8384 export certificates/#9062 action sheet
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3388 Feature/#8384 export certificates/#9063 error alert
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3389 Feature/8714 adjust info screen release 29
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#3391 Adding Text(EXPOSUREAPP-8928)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3390 Feature/9035 show booster vaccinations in certificates list
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3395 expand logs for DSC download
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
Labels: chore

#3387 Feature/8356 warning on behalf/8980 request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin+SubmissionPreparation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/CheckinSubmissionPreparationTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionError.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/__tests__/OnBehalfCheckinSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
Labels: task

#3392 Feature/8356 warning on behalf/8971 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/TraceLocationCheckinSelectionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/OnBehalfDateSelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/OnBehalfDurationSelectionCell.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_OnBehalfCheckinSubmission.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3398 fix transparent navigation bar
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewController.swift
Labels: bug

#3397 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
Labels: text-change

#3400 Initialize with cached app config and update publisher before resolving promises
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
Labels: bug

#3401 push districts ViewController instead of presenting it
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#3360 Feature/soft rate limit for risk check
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/RateLimitLogger.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/RateLimitLoggerTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Model/RiskProvidingConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: community

#3404 Fix deletion animation
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
Labels: bug

#3412 Feature/8715 adapt privacy policy for 2.9
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: feature

#3399 Feature/#8384 export certificates/#9066 pdf generation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Certificate-PDF/Certificate-PDF Blue.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Certificate-PDF/Contents.json
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/LICENSE.txt
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Bold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-BoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-ExtraBold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-ExtraBoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Italic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Light.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-LightItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Regular.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-SemiBold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-SemiBoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/RecoveryCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/VaccinationCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
Labels: task

#3405 Feature/8504 Open test certificate from test result
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/AntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: feature

#3406 Add some tests for PDF generation.
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+PDFTests.swift
Labels: task

#3418 Fix typo (EXPOSUREAPP-9180)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3413 UA Bugfix Neue Funktionen 2.9
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3416 Add license for OpenSans.
  licenses.json
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
Labels: task

#3434 Update dependency to 'dgc-certlogic-ios'
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: feature

#3425 Feature/#8384 export certificates/#9065 pdf view UI tests
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3433 Feature/9050 UI test snapshot for test certificate button on test result
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: tests, screenshots

#3439 Feature/#8384 export certificates/storybranch
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Lock2.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Lock2.imageset/Icons_Lock2_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Lock2.imageset/Icons_Lock2_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Certificate_Export.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Certificate_Export.imageset/Illu_Certificate_Export.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Certificate_Export.imageset/Illu_Certificate_Export_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Certificate-PDF/Certificate-PDF Blue.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Certificate-PDF/Contents.json
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/__tests__/HealthCertificatePDFGenerationInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/__tests__/HealthCertificatePDFVersionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/LICENSE.txt
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Bold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-BoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-ExtraBold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-ExtraBoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Italic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Light.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-LightItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-Regular.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-SemiBold.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/OpenSansFont/OpenSans-SemiBoldItalic.ttf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/RecoveryCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/VaccinationCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificate+PDFTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature

#3440 Use fork to include 12-hour override fix
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Extensions/Dateformatter+vCard.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/TestEntry+Extension.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: bug

#3444 Add style from the CSS file
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug

#3446 Feature/9246 vaccination ranking
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/VaccinationProductType.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
Labels: bug

#3450 Bump to next version 2.9.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3448 Feature/9032 reposition faq links on certificate validation screens
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateTechnicalValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/__tests__/HealthCertificateValidationResultTests.swift
Labels: task

#3451 Bump to next version 2.9.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin
