Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-03, with the labels that each got.

#2102 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#2099 Fixed typo in 'New Functions' UI
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2103 Feature/xxx missing tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/__tests__/Sequence+NSAttributedTextTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/UIImage+resizeTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/EUSettings/__tests__/EUSettingsViewModelTests.swift
Labels: admin

#2108 Fix/infinite loop
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/DataDonationModel.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: bug

#2093 Feature/task 5098 unit tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayEntryCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayViewModelTest.swift
Labels: chore

#2071 Fix/5189 log issues
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogging/DMLogsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogging/LogDataItem.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/StreamReader.swift
  src/xcode/ENA/ENA/Source/Workers/SQLiteKeyValueStore.swift
Labels: bug, chore

#2112 Feature/5269 integration of keys from Switzerland
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flags.eu.ch.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flags.eu.ch.imageset/Flags - EU - Switzerland-1.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flags.eu.ch.imageset/Flags - EU - Switzerland.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Country Flags/flag.ch.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Country Flags/flag.ch.imageset/Flags - Switzerland - rect.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Country Flags/flag.ch.imageset/Flags - Switzerland.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUCHWideOnboarding-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUCHWideOnboarding.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUWideOnboarding-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EUTracingOnboarding.imageset/Illu_EUWideOnboarding.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illu_EUCHWideOnboarding-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illu_EUCHWideOnboarding.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability - Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration - EU Interoperability.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_EuropaweitWarnen.imageset/Illustration - EU Warnen - Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_EuropaweitWarnen.imageset/Illustration - EU Warnen.pdf
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/EuTracingTableViewCell.swift
Labels: feature

#2115 base32 decoding
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Evreg_Event_Tests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/Base32DecodingTests.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/check_in_export.pb.swift
  src/xcode/gen/output/internal/evreg/event.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
Labels: task

#2098 Using App Launcher if Contact Journal is used for the first time does not open the actual day
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
Labels: bug

#2088 Feature/task 5099 UI tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: task

#2109 Fix typo and change keyboard type to default to display symbols etc.
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
Labels: bug

#2116 5249 adding screenshots
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#2105 In App Settings, the headers move if you were first on Exposure Logging and then selecting Share Data and/or Background App Refresh
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/BackgroundAppRefreshViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewController.swift
Labels: bug

#2106 Stale date on statistics display early in day
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2114 Fix/5422 quick action states
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITestsQuickActions.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/Gemfile.lock
Labels: bug

#2120 5249 missings screenshots
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#2121 Chore/fix infinite loop in tests
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ENAUITests-Extensions.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
  src/xcode/ENA/ENAUITests/ExposureLogging/ENAUITests_05_ExposureLogging.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITestsOnboarding.swift
Labels: chore

#2090 Feature/5252 adjust info screen to announce new release features for 1.15
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2123 increase version number and set build number to 0
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: bug

#2113 Feature/task 5344 Keys for Legal Texts
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITestsDataDonation.swift
Labels: task

#2117 Feature/5252 translation changes adjust info screen to announce new release features for 1.15
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2122 Bump to next Version 1.14.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2119 AppLauncher does not close screen "Ihr Testergebnis" pending/negative/invalid
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
Labels: bug

#2124 Fix issue snapshot tests failing on CI
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests-Statistics.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: Fix 1.13

#2118 Feature/4497 5342 add error logging main screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icon_fehleranalyse.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icon_fehleranalyse.imageset/icon_fehleranalyse.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorLoggingStatus.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportFooterView.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportFooterView.xib
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportLoggingViewController/ErrorReportLoggingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportLoggingViewController/ErrorReportLoggingViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportViewController/ErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportViewController/ErrorReportViewController.xib
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2129 Fix/5496a link to coronawarn.app screenshots does not work in english
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
Labels: bug

#2130 Add Privacy Cell
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
Labels: task

#2127 Add Ventilation Cell in the RiskDetails screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Ventilation.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Ventilation.imageset/icon_ventilation (1).pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2111 Feature/5276 risk calculation configuration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/default_app_config_113
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/__tests__/ExposureWindowsMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/DebugRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/NormalizedTimeToRiskLevelMapping.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/RiskCalculationConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/TransmissionRiskValueMapping.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationError.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/RiskCalculationTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/exposure-windows-risk-calculation.json
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/default_app_config_115
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/check_in_export.pb.swift
  src/xcode/gen/output/internal/evreg/event.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_android.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_android.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/event_registration_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_els_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: feature

#2131 Feature/task 5472 error report details info screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportDetailedInformation/ErrorReportDetailInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportDetailedInformation/ErrorReportDetailInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportDetailedInformation/__tests__/ErrorReportDetailInformationViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2133 Bump to next Version 1.14.1.0
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2136 Bugfix/5533 client is not collecting metadatas
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsActualData.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: bug

#2134 Fix/5534 app crash after device wakeup & unlock
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2138 Feature/4497 Task 5535 Implement Legal Texts for EN and TU
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportDetailedInformation/ErrorReportDetailInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportDetailedInformation/__tests__/ErrorReportDetailInformationViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
Labels: text-change

#2139 Fix/5544 crash when system time wrong
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#2140 Feature/4497 5521 implement sending screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportViewController/ErrorReportViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.xib
Labels: task

#2143 12.5 - iPhone 5s Statistics - Text in Labels sometimes poorly layouted
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.xib
Labels: bug

#2144 Add Text for Navigation Cell
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2063 12.5 wrong button behaviour for cancelation pop up of a submission without consent
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2148 Chore/hint to plain logging
  src/xcode/ENA/.swiftlint.yml
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENATests/Helper/iOS13TestCase.swift
  src/xcode/ENA/ENAUITests/Helper/AccessibilityLabels.swift
Labels: admin

#2150 Fix updating testResultsMetadata
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
Labels: bug

#2149 Add missing server error code for error message handling
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#2147 Bugfix separator missing data donation
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/SettingsDataDonationViewModelTests.swift
Labels: bug

#2155 Bump to next Version 1.15.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2145 Localizable.strings for translation
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2152 Feature/4497 5556 finalize navigations
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController/SendErrorLogsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController/SendErrorLogsViewModel.swift
Labels: task

#2153 fix/The headline "Ihr Einverständnis" on the Data Donation Screen behaves strangely
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#2162 fix/Removed Duplicate Text Strings from Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2163 Fix/remove duplicate text strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITestsQuickActions.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
Labels: bug

#2167 Safe the date fo the last PPA submission
  src/xcode/ENA/ENA/Source/Models/Metadata/Risk Exposure Metadata/RiskExposureMetadata.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: bug

#2164 Bump to next Version 1.15.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2168 properly dimiss all presented view controllers
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
Labels: bug

#2169 Slight text adjustment to sync with Android text (re: Risikoüberprüfung regelmässig anstoßen [EXPOSUREAPP-5541]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2171 Update privacy-policy.html - incorrect plural [EXPOSUREAPP-5435]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#2174 Update Localizable.legal.strings - missing 'an' in string [EXPOSUREAPP-5576]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#2165 Feature/5279 5368 event checkin persistence mock
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceTimeIntervalMatch.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceWarningPackageMetadata.swift
Labels: task

#2175 Fix/5621 submission qr issue
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: bug

#2180 Fix the missing windows metadata bug + refactoring
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalyticsActualData.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/__tests__/ExposureWindowsMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#2170 Feature/5279 5434 local qr code generation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/PDFDocument+EmbedImageTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/resources/qr-code-print-template.pdf
  src/xcode/ENA/ENA/Source/Extensions/__tests__/resources/qr-code-to-embed.png
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePlayground.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/QRCodePlaygroundTests.swift
Labels: task

#2181 Feature/5279 event spike
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Evreg_Event_Tests.swift
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Icons_Tabbar_Checkin.pdf
  src/xcode/ENA/ENA/Resources/ENA.entitlements
  src/xcode/ENA/ENA/Resources/ENACommunity.entitlements
  src/xcode/ENA/ENA/Resources/ENATest.entitlements
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/PDFDocument+EmbedImageTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/resources/qr-code-print-template.pdf
  src/xcode/ENA/ENA/Source/Extensions/__tests__/resources/qr-code-to-embed.png
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/CheckInCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/CheckInDetail/CheckInDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/CheckInDetail/CheckInDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/CheckIns/CheckInsTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/CheckIns/CheckInsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/QRCodeScanner/CheckInQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/QRCodeScanner/CheckInQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/CheckIn/QRCodeScanner/apple-app-site-association
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceTimeIntervalMatch.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceWarningPackageMetadata.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePlayground.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/Base32DecodingTests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/QRCodePlaygroundTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: task

#2177 TASK/Removed analytics feature from new version features for version 1.15
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
Labels: feature

#2182 Fix/5546 low risk with exposure text and link
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2187 add Int Environment for testers
  scripts/switch_to_dev_env.sh
Labels: admin

#2189 Protocol Buffer update for release 2.0.x at Thu Mar 11 10:00:34 UTC 2021
  proto/resources/internal/evreg/event.proto
  proto/resources/internal/evreg/poster_template.proto
  proto/resources/internal/pt/check_in.proto
  proto/resources/internal/pt/qr_code_poster_template.proto
  proto/resources/internal/pt/trace_location.proto
  proto/resources/internal/pt/trace_warning.proto
  proto/resources/internal/submission_payload.proto
  proto/resources/internal/v2/app_config_android.proto
  proto/resources/internal/v2/app_config_ios.proto
  proto/resources/internal/v2/key_download_parameters.proto
  proto/resources/internal/v2/presence_tracing_parameters.proto
Labels: admin

#2191 Generate new protos
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Evreg_Event_Tests.swift
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Pt_TraceLocation_Tests.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/check_in_export.pb.swift
  src/xcode/gen/output/internal/evreg/event.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/pt/check_in.pb.swift
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/pt/trace_warning.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/key_download_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
Labels: chore

#2188 loggers for event registration
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: chore

#2199 Bump to next Version 1.15.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2194 Match iOS README.md to Android README.md
  README.md
Labels: admin

#2201 Update generated Protos
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/pt/trace_warning.pb.swift
Labels: chore

#2193 Task/4497 Legal Text Cleanup
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+DynamicTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController/SendErrorLogsViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITestsAppInformation.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITestsExposureDetection.swift
  src/xcode/ENA/ENAUITests/Helper/UITestHelper.swift
Labels: task

#2206 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2211 Update repositories table (README change only)
  README.md
Labels: admin

#2197 Daily Contact Journal scrolls up during data maintenance
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#2207 Bump to next Version 1.15.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2215 Update generated files from new protobuf
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
Labels: admin

#2200 App crashes when trying to delete log
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/StreamReader.swift
Labels: bug

#2212 DSE - Index - Headline 10 wrong
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: bug

#2208 Feature/5279 5368 event checkin persistence
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Protocols/Store/SecureSQLStore.swift
  src/xcode/ENA/ENA/Source/Protocols/Store/StoreQuery.swift
  src/xcode/ENA/ENA/Source/Protocols/Store/StoreSchema.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV1/ContactDiaryStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV2/ContactDiaryStoreSchemaV2.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV3/ContactDiaryStoreSchemaV3.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryAccess.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV2/ContactDiaryMigration1To2Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV3/ContactDiaryMigration2To3Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/CreateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/DeleteAllCheckins.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/DeleteCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/UpdateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/CreateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/DeleteAllTraceLocationsQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/DeleteTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/UpdateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/CreateTraceTimeIntervalMatchQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/DeleteTraceTimeIntervalMatchQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/CreateTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/DeleteTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/StoreV1/EventStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/StoreV1/EventStoreSchemaV1Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Utils/__tests__/Store/FMDB+Access.swift
  src/xcode/ENA/ENA/Source/Utils/__tests__/Store/FMDB+Utils.swift
  src/xcode/ENA/ENA/Source/Workers/Keychain/KeychainHelper.swift
Labels: task

#2221 Installation date logs.
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMInstallationDate/DMInstallationDateViewController.swift
Labels: chore

#2225 OnboardingInfoViewController pushed twice on second next tap
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
Labels: bug

#2216 Bugfix/5785 no submission for 48h
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Client Metadata/__tests__/ClientMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/Model/DataDonationModel.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASubmissionState.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: bug

#2222 Feature/update licenses
  licenses.json
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
Labels: chore

#2198 iPhone SE: Cannot add email address in contacts
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryEntryTextField.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
Labels: bug

#2178 Feature/5330 Data Privacy Note For 1.15
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#2229 Bump to next Version 1.15.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2210 Remove recommendation to add labels to new issues & PRs and improve CONTRIBUTING.md
  CONTRIBUTING.md
Labels: admin

#2230 Generate new Swift files from new Protos
  src/xcode/gen/output/internal/pt/trace_warning.pb.swift
Labels: chore

#2226 Update Fastlane to 2.178.0
  src/xcode/Gemfile.lock
Labels: chore

#2223 Fix/5389 The headline "Ihr Einverständnis" on the Data Donation Screen behaves strangely
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
Labels: bug

#2231 (After App-Update) App crash when tab "warning" is selected
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#2219 Inconsistent & wrong behaviour of the button to reactivate exposure logging on the risk card in different scenarios
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionDetailTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/__tests__/ENSettingTableViewCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2218 Feature/5409 Event Check In Info Screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Checkin_QR.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Checkin_QR.imageset/Onboarding_QR.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Checkin_QR.imageset/Onboarding_QR_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Event_Attendee.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Event_Attendee.imageset/Illu_Attendee_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Event_Attendee.imageset/Illu_Attendee_Light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/__test__/CheckinsInfoScreenViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/__test__/ENAUITests_09_EventCheckIn.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: enhancement

#2202 Add QR Screen UI
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flash_disabled.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/flash_disabled.imageset/flash_disabled.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/QR Code Scanning/QRScannerError.swift
  src/xcode/ENA/ENA/Source/Models/QR Code Scanning/TorchMode.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Checkins/Cells/StatusCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Checkins/CheckinsTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/QRScannerFocusView.swift
Labels: task

#2239 Risk Card "Risiko-Ermittlung gestoppt" behave different on Home vs. Detailscreen
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
Labels: bug

#2238 FAQ Link of Low Risk With Exposures visible on "Risiko-Ermittlung gestoppt" + "Risiko-Überprüfung fehlgeschlagen"
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
Labels: bug

#2242 Add Days since Install to New Functions Display
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: enhancement

#2243 Bump to next Version 1.15.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2235 Feature/5593 quick action check in
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/qrcode.viewfinder.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/qrcode.viewfinder.imageset/qrcode.viewfinder.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/ENAUITestsQuickActions.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2251 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2247 Daily Contact Journal scrolls up during data maintenance
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#2233 5585 check in download matching risk calculation/5648 http calls
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/api-response-traceWarning
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPMethod.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDiscoveryTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/Date+Utils.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/TraceWarningDownload/Model/TraceWarningDiscovery.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/TraceWarningDownload/Model/TraceWarningDiscoveryResponse.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/TraceWarningDownload/Model/TraceWarningError.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: task

#2240 Alignment of Deadman Alert Title - [EXPOSUREAPP-5541]
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2259 Generate new files from protos
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
Labels: admin

#2254 feature/Translations for new version features 2.0
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2257 Fix/5640 Clean Up Screenshots
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
Labels: Fix 1.15

#2260 fix/5640 Disabled override_status_bar
  src/xcode/fastlane/Snapfile
Labels: Fix 1.15

#2252 Apply changes from newest techspec to event persistence.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/Cells/CheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/Cells/__tests__/CheckinCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/__test__/CheckinsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/CreateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/UpdateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/CreateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/UpdateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/DeleteAllTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/StoreV1/EventStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/TraceLocation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/TraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/__tests__/TraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: task

#2258 Feature/task 5661 create qr code category selection screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/TraceLocationTypeTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/TraceLocation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Cells/SelectTraceLocationTypeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeFooterView.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeHeaderView.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/__tests_/TraceLocationTypeSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2241 AppLauncher - Submission WF (Aufruf-Probleme)
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
Labels: bug

#2262 Fix wrong url and change order in http call
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesStoreV2.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/DownloadedPackagesStoreErrorStub.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: chore, task

#2248 Feature/5582 5851 checkout and journal entry
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/Date+Utils.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/CheckinSplittingService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/CheckinSplittingServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Model/CheckinTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2263 5784 - risk metadata missing after first submission
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: Fix 2.0

#2265 5652 matching of TraceTimeIntervalWarnings with Checkins
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Event Registration/TraceWarningDownload/TraceWarningMatching.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/TraceWarningMatcherTests.swift
Labels: task

#2264 Feature/5409 Legal Text Info Screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_CheckInRiskStatus.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_CheckInRiskStatus.imageset/Icon_CheckInRiskStatus.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_CheckInRiskStatus.imageset/Icon_CheckInRiskStatus_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2266 Fix/5899 ppa hours since test registration are mainly 0
  src/xcode/ENA/ENA/Source/Models/Metadata/Client Metadata/__tests__/ClientMetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Exposure Windows Metadata/ExposureWindowsMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/ExposureWindow.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/Models/ScanInstance.swift
Labels: bug

#2268 Typo in Localizable.strings - event registration
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2270 Fix/5403 info screen “kontakt tagebuch“ scrolls up if you navigate back from “datenschutz"
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/DiaryInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
Labels: bug

#2261 Feature/5589 print qr code
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/icon_share.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icons_Print.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icons_Print.imageset/icon_print.pdf
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/TraceLocation+GenerateQRCode.swift
  src/xcode/ENA/ENA/Source/Extensions/UIColor+HEX.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/PDFDocument+EmbedImageTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/TraceLocation+GenerateQRCodeTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/PrintVersion/TraceLocationPrintVersionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/PrintVersion/TraceLocationPrintVersionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateMetadata.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProvider.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProviding.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/QRCodePosterTemplateProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/sample_qr_code_template/qr_code_template.bin
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#2269 Fix terminology in legal strings (contact journal) - English only
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
Labels: text-change

#2255 Feature/5590 adjust info screen to announce new release features for 2.0
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2275 don't Delete testResultMetadata and KeySubmissionsMetadAta unless the…
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: bug

#2276 Add difference in days between mostRecentRisk and registrationDate in…
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/TestResultMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: bug

#2274 Screen "andere warnen" scrolls up if you navigate back from "Datenschutz"
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2249 Feature/5680 event details screen UI
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/CheckinDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/CheckinDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/AccessibleStackView.swift
Labels: task

#2278 Bump to next Version 2.0.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2271 Feature/5587 create event home screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TraceLocations-Information.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TraceLocations-Information.imageset/Illu_EventPlanning-Information.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TraceLocations-Information.imageset/Illu_Organizer_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_TraceLocations-Information.imageset/Illu_Organizer_Light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Info/TraceLocationsInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Info/TraceLocationsInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Info/__test__/TraceLocationsInfoViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: task

#2280 Fix the id handling of TraceTimeIntervalMatch and TraceWarningPackageMetadata
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/CreateTraceTimeIntervalMatchQuery.swift
Labels: bug

#2282 daysSinceMostRecentDateAtRiskLevelAtTestRegistration should be -1 if …
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
Labels: bug

#2279 Remove duplicated Keys from strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2273 5650 trace warning package downloader
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/api-response-traceWarning
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/CachingHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/SAPDownloadedPackage.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/Verification.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/Helper/HTTPClient+MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/SAPDownloadedPackageTests.swift
  src/xcode/ENA/ENA/Source/Client/Security/__tests__/CryptoFallbackTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/VerificationMock.swift
  src/xcode/ENA/ENA/Source/Extensions/Int+DateFromUnixTimestampInHours.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/AppConfigurationProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/Model/TraceWarningDiscovery.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/Model/TraceWarningError.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/Model/TraceWarningSuccess.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningMatching.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2281 Screen "Ihr Testergebnis" (pending) scrolls up if you navigate back from "Datenschutz"
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionThankYouViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/__tests__/FooterViewModelTests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2283 add texts for contact journal overview
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task, text-change

#2284 5649 checkin risk calculation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Calendar+GregorianLocale.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/CheckinSplittingService.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/CheckinRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/Model/CheckinRiskCalculationResult.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/CheckinRiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningMatching.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningMatcherTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2285 Feature/5582 event check in UI scan qr code/5850 save checkin to store
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2292 Cannot complete onboarding
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingDataDonation.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsCoordinator.swift
Labels: bug

#2293 Fix missing button on Test Result Screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/TestResultAvailableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/TestResultAvailableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: bug

#2300 QR code configuration strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2304 Chore/generate new protos
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Pt_TraceLocation_Tests.swift
  src/xcode/gen/output/internal/pt/check_in.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/pt/trace_warning.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
Labels: chore

#2301 localized strings for adjust checkin times
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: admin, chore, text-change

#2305 Fix/event store update
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/__test__/CheckinsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__test__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayEntryCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/__test__/DiaryEditEntriesCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryEntryTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__test__/DiaryLocationTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV4/ContactDiaryMigration3To4.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV4/ContactDiaryStoreSchemaV4.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/StoreV4/ContactDiaryMigration3To4Tests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/CheckinSplittingService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceTimeIntervalMatch.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceWarningPackageMetadata.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/CreateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/DeleteAllCheckins.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/DeleteCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/UpdateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/CreateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/DeleteAllTraceLocationsQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/DeleteTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/UpdateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/CreateTraceTimeIntervalMatchQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/DeleteTraceTimeIntervalMatchQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/CreateTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/DeleteAllTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceWarningPackageMetadata/DeleteTraceWarningPackageMetadataQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/StoreV1/EventStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/CheckinSplittingServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Model/CheckinTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/TraceLocation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/TraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/__tests__/TraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/__test__/TraceLocationsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: task

#2306 bundle update all
  src/xcode/Gemfile.lock
Labels: chore

#2297 Feature/5588 event host/5662 configuration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Textfield/ENA Textfield Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/TimeInterval+Minutes.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryEntryTextField.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocationType.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/__tests__/FooterViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Cells/SelectTraceLocationTypeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeFooterView.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeHeaderView.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENATextField.swift
Labels: task

#2302 Add interface for native camera
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/QRCodePayload+extention.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocationType.swift
Labels: task

#2299 Feature/5659 adjust checking times
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInBottomCornerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDescriptionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDescriptionCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInHeaderCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInNoticeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTopCornerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/__tests__/CheckInDescriptionCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/__tests__/CheckInTimeModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Views/GradientBackgroundView.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Views/GradientNavigationView.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/__tests__/EditCheckinDetailViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/InfoBoxView.xib
  src/xcode/ENA/ENA/Source/Scenes/Settings/Reset/ResetViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeHeaderView.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2310 updated associated paths
  src/xcode/ENA/ENA/Resources/ENA.entitlements
  src/xcode/ENA/ENA/Resources/ENACommunity.entitlements
  src/xcode/ENA/ENA/Resources/ENATest.entitlements
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/apple-app-site-association
Labels: task

#2308 Feature/5584 contact journal extension/5982 UI implementation2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/NSAttributedString+BulletPoint.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/CheckinWithRisk.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: task

#2311 Feature/5663 display qr code screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsDateTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsHeaderCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsLocationCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: feature

#2296 Feature/5587 Legal Texts For Info Screens
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#2309 Feature/5912 sort check ins
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/__test__/CheckinsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: feature

#2294 Feature/5582 event check in UI scan qr code/6018 implement rounding for automatic checkout time
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: task
