Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-12, with the labels that each got.

#3911 extended description & address to 255 chars
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CheckinQRCodeParserTests.swift
Labels: bug, feature

#3913 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3914 Feature/10464 crypto functions part 2/10684 integration
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationFailedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationOpenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationPassedViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/__tests__/TicketValidationResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/EncryptAndSignDCC/EncryptionScheme.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResultToken+Fake.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationResultToken.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ServiceIdentityDocument/TicketValidationServiceIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationServiceIdentityDocumentValidationDecorator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/ServiceIdentityDocumentProcessorTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPair.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/ECKeyPairGeneration.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/JSONWebKey.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
Labels: task

#3917 Bump to next version
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3918 Fix failing build
  src/xcode/ENA/ENA/Source/Workers/Store/SecureCache.swift
Labels: admin

#3916 Ticket Validation - Add missing logs.
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/DynamicEvaluateTrust.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
Labels: task

#3919 Bump to next Version 2.15.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3921 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3920 Feature/10760 2 g plus check in/10877 adapt certificate priority
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
Labels: task

#3924 Feature/10760 2 g plus check in/10877 adapt certificate priority part 2
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
Labels: task

#3923 Story/10762 text changes negative result
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#3925 Fix/10885 ticket validation broken
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Receive/ServiceIdentityDocument.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationAccessTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationResultTokenResource.swift
Labels: bug

#3926 Feature/10568 ticket validation allow list integration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationResultTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/ServiceIdentityDocumentResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationResultTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/AllowListEvaluationTrust.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListService.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/SAP_Internal_Dgc_ValidationServiceAllowlist+Extension.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/TicketValidationAllowList.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/Model/ValidationServiceAllowlistEntry.swift
  src/xcode/ENA/ENASecurity/Sources/ENASecurity/TrustEvaluation.swift
Labels: task

#3930 Bump to next Version 2.15.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3929 Enhance allow list error handling
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationResultTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationError.swift
Labels: task

#3931 Feature/10879 dm disable allow list validation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMSwitchTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMTicketValidation/DMTicketValidationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMTicketValidation/DMTicketValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListService.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3937 iOS Info-Screen Text difference
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3936 Feature/10834 show prüfpartner from allow list on consent ii screen
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/TicketValidationCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
Labels: task

#3939 Fix/10925 key submission metadata
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadata+Mock.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: bug

#3933 improved numberformatters to correct rounding
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Extensions/SAP_Internal_Stats_KeyFigure+Formatting.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
Labels: bug

#3941 use correct sha256 method
  src/xcode/ENA/ENA/Source/HTTPClient/Security/iOS 12 Fallback/CryptoKitFallbacks.swift
Labels: bug

#3940 Fix for crash at adding progress child
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
Labels: bug

#3938 Feature/10760 2 g plus check in/10859 admission state
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+AdmissionState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPersonAdmissionState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/CWATestCase+HealthCertificateConvenience.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+AdmissionStateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/HealthCertifiedPersonTests.swift
Labels: task

#3943 introduce some optional indentation for the bullet points
  src/xcode/ENA/ENA/Source/Extensions/NSAttributedString+BulletPoint.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerActivityIndicatorView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
Labels: bug

#3932 Feature/10761 text changes recommended actions/10893 10894 details screen texts and navigation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENALinkedTextView.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: task

#3944 Feature/10774 allow list unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/__tests__/AllowListServiceTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/ECKeyPairGenerationTests.swift
  src/xcode/ENA/ENASecurity/Tests/ENASecurityTests/TrustEvaluationTests.swift
Labels: task

#3948 Bump to next Version 2.15.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3942 Feature/10761 text changes recommended actions/10858 hygiene rules info screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Illu_Distanz.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Illu_Distanz_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3952 Ticket Validation - fix for edge case
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/TicketValidationConditions+CertificateSelection.swift
Labels: bug

#3950 Text changes recommended actions - UITests
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Views/Common/CloseBarButtonItem.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITests_04b_ExposureDetection.swift
Labels: task

#3954 Feature/new app version validation check
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProviding.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/MockTicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidating.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/VersionError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3955 Story/10761 text changes recommended actions/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Home Office.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Home Office.imageset/Home Office.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Home Office.imageset/Home Office_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/NoMeetup.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/NoMeetup.imageset/NoMeetup.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/NoMeetup.imageset/NoMeetup_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Public Transport.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Public Transport.imageset/Public Transport.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Public Transport.imageset/Public Transport_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Qarantine.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Qarantine.imageset/Qarantine.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Qarantine.imageset/Qarantine_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Shoppiing.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Shoppiing.imageset/Shoppiing.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Shoppiing.imageset/Shoppiing_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Travel.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Travel.imageset/Travel.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Travel.imageset/Travel_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Couch.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Couch.imageset/Illu_Couch.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Couch.imageset/Illu_Couch_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Illu_Distanz.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Distanz.imageset/Illu_Distanz_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconWithLinkTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/Contagion/ContagionInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/Contagion/ContagionInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENALinkedTextView.swift
  src/xcode/ENA/ENA/Source/Views/Common/CloseBarButtonItem.swift
  src/xcode/ENA/ENAUITests/ExposureDetection/ENAUITests_04b_ExposureDetection.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: feature

#3953 Text changes recommended actions - Unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Info/ContagionInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Info/HygieneRulesInfoViewModelTests.swift
Labels: task

#3947 Ticket Validation - Fix long error messages
  src/xcode/ENA/ENA/Source/HTTPClient/Service/ServiceError.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidationError.swift
Labels: bug

#3957 Bump to next Version 2.15.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3956 Story/10683 show always notifications/10861 show on foreground
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: task

#3959 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3960 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3961 Story/10967 restrict number of persons
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/QRCodeParsableMock.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/OnBehalfCheckinSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureDeviceTimeCheckDecorator.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureUnencryptedEventsDecorator.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/DeviceTimeCheck.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/AppConfiguration+FeaturesTests.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3962 Fix/10619 memory issue
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V2/DownloadedPackagesSQLLiteStoreV2.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#3963 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3964 Show error message if more persons are already registered
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#3965 Fix/corona test service error localization
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTANResource.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
Labels: bug

#3966 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3972 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3971 Fix/11011 invalid date crash
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintCellModel.swift
Labels: bug

#3967 Feature/10876 add new info box on person screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPersonAdmissionState.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#3973 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3974 Bump to next Version 2.15.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3977 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3976 Dismiss screen allow bypasing legal text
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#3979 Fix/10868 improve grouping standardized name
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__test__/Name+ExtensionTests.swift
Labels: bug

#3958 Feature/10951 show badge on home screen tab
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeBadgeWrapper.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeBadgeWrapper+Fake.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeBadgeWrapperTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3981 Story/10683 show always notifications/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeBadgeWrapper.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeBadgeWrapper+Fake.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeBadgeWrapperTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3982 Fix/11018 text changes privacy policy
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug, text-change

#3983 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3984 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug, text-change

#3986 fix/9922 Add some logs.
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDSCList/DMDSCListsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/HealthCertificateQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/QRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/TicketValidationQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Services/DSCList/DSCListProvider.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#3988 Add en links to other languages.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
Labels: bug

#3985 Feature/11007 implement status indicator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.xib
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPersonAdmissionState.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#3990 Bump to next version 2.16.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3989 Feature/10760 2 g plus check in/10875 certificate switch
  licenses.json
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/CurrentlyUsedCertificate_Icon.imageset/CurrentlyUsedCertificate_Icon_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_dark.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_dark.imageset/Icon_CurrentlyUsedCertificate_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_grey.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_grey.imageset/Icon_CurrentlyUsedCertificate_grey.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_light.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_light.imageset/Icon_CurrentlyUsedCertificate_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_medium.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/Icon_CurrentlyUsedCertificate_medium.imageset/Icon_CurrentlyUsedCertificate_medium.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Button Colors/ENA Selected Segment Tint Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHeadlineWithImageCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/EditCheckInTime/Views/GradientBackgroundView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPersonAdmissionState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: task

#3994 Bump to next Version 2.16.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3992 Add screenshot
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3995 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3993 Align icons with top of the label.
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionGuideCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionLongGuideCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/Contagion/ContagionInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewModel.swift
Labels: bug

#3996 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3997 ci maintain
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/App/__tests__/NavigationControllerViewScrollingTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__tests__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__tests__/TextFieldsManagerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayAddCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayEmptyViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayEntryCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayNotesInfoViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/__tests__/DiaryEditEntriesCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/__tests__/DiaryEditEntriesViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Info/__tests__/DiaryInfoViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__tests__/DiaryContactPersonTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__tests__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__tests__/DiaryEntryTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__tests__/DiaryLocationTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__tests__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Info/__tests__/CheckinsInfoScreenViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/__tests__/CheckinsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/CheckInTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/CheckinSubmissionPreparationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/Models/CheckinTestCase.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/Models/CheckinTestCasesWithConfiguration.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/TraceLocationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/TraceLocationTypeTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/checkin-timeinterval-derivation.json
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/__tests__/TraceLocationsConfigurationViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/__tests__/TraceLocationsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__tests__/RecycleBinViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/__tests__/RiskLegendeTest.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/CWATestCase+HealthCertificateConvenience.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+PDFTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+AdmissionStateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonBoosterTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonKnownVaccinationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonOtherVaccinationProductTypeTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Name+ExtensionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/ENARangeTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/ExposureWindowTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/Models/ExposureWindowTestCase.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/Models/RiskCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/Models/TestCasesWithConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/RiskCalculationTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/ScanInstanceTest.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/exposure-windows-risk-calculation.json
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/Pluginfile
Labels: admin

#3999 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4000 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4005 Delete the Row if the AdmissionState changes upon deleting a certificate
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
Labels: bug

#4006 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4001 Feature/10760 2 g plus check in/11062 unit test
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task

#4007 Fix/11057 max person count exemption
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4002 Fix/10443 tabbar scrolling issue on home screen
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
Labels: bug

#3980 Fix/11002 no caching used by http client
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AllowListResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AppConfigurationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountriesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/Resource+Fake.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/Types/CacheUsePolicy.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/Types/ServiceType.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/CachedRestServiceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/Error+Fake.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/StandardRestServiceTests.swift
Labels: bug

#4003 Fix/11037 refactor file scanner errors to show missing errors
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerErrorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4008 Fix/10999 illustration misallignements
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHeadlineWithImageCell.swift
Labels: bug

#4011 Bump to next Version 2.16.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4013 Recommended action high risk card - remove unnecessary line
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug, text-change

#4014 Fix/11047 legal text turkish
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change
