Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-10, with the labels that each got.

#3617 Fix references to parent view controller
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: bug

#3605 Feature/#9113 notification rework/#9675 delta onboarding
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/CrossCountrySupport/DeltaOnboardingCrossCountrySupport.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/CrossCountrySupport/DeltaOnboardingCrossCountrySupportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/CrossCountrySupport/DeltaOnboardingCrossCountrySupportViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/Data Donation/DeltaOnboardingDataDonation.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationRework.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationReworkViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationReworkViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingViewControllerTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITestsDeltaOnboarding.swift
Labels: task

#3616 Feature/9316 scanner tab/9632 popover
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tooltip_Close.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tooltip_Close.imageset/Icons_Tooltip_Close.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Tooltip/QRScannerTooltipViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Tooltip/QRScannerTooltipViewController.xib
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#3620 Quickfix for screenshots and ui tests
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationRework.swift
Labels: chore

#3615 Feature/9280 scan qr codes from image file/9410 display errors
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3623 Feature/9280 scan qr codes from image file/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/file_button.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/file_button.imageset/FileButton.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Button Colors/IconWithText.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerIndicatorView.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/QRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: feature

#3622 Task/9459 extend UI tests
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_OnBehalfCheckinSubmission.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: task

#3624 Feature/9316 scanner tab/9630 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITests_02_AppInformation.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITests_00_Onboarding.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITests_03_Settings.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_15_OnBehalfCheckinSubmission.swift
  src/xcode/ENA/ENAUITests/UniversalQRCodeScanner/ENAUITests_16_UniversalQRCodeScanner.swift
  src/xcode/fastlane/Snapfile
Labels: task

#3635 restore version number because our algorithm does not work with that …
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationRework.swift
Labels: admin, chore

#3636 Fix/removedubstrings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#3633 chore/9599 cleanup navigation items for health certificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewController.swift
Labels: community, mirrored-to-jira

#3640 Bump to next Version 2.12.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3639 Bump to next Version 2.13.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#3634 Fix/9767 fix titles of topViewControllers
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/SendErrorLogsViewController/SendErrorLogsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/ExposureSubmissionCheckinsViewController.swift
Labels: community, mirrored-to-jira

#3638 Fix for onboarding.
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingCoordinatorTests.swift
Labels: bug

#3630 chore/9599 cleanup navigation items: exposure submission
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TestOverwriteNotice/TestOverwriteNoticeViewController.swift
Labels: community, mirrored-to-jira

#3641 Bugfix/9776 fix faq links low risk with exposure
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
Labels: bug

#3619 change notification text for certificates
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#3644 chore/9599 cleanup remaining navigation items for Exposure Submission
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/ExposureSubmissionCheckinsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionThankYouViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/TestResultAvailableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationReworkViewController.swift
Labels: community, mirrored-to-jira

#3637 Fix/9667 cancelation button doesnt work in event checkin
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#3618 Feature/#9113 notification rework/#9676 settings screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/UITableView/UITableViewCell+ViewTags.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewSection.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewDoubleLabelViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewRoundedCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewTextViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationReworkViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/Cells/NotificationSettingsOffTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/Cells/NotificationSettingsOffTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/Cells/NotificationSettingsOnTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/Cells/NotificationSettingsOnTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
Labels: task

#3645 Chore/fix test details selection of location visit()
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: admin, chore

#3643 Feature/#9113 notification rework/#9677 tests & reorder delta onboarding
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewRoundedCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/CrossCountrySupport/DeltaOnboardingCrossCountrySupport.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/Data Donation/DeltaOnboardingDataDonation.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/DeltaOnboardingNotificationRework.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NotificationRework/__tests__/DeltaOnboardingNotificationReworkViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/__tests__/DeltaOnboardingCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/__tests__/NotificationSettingsViewModelTests.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITests_03_Settings.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3647 Chore/fix onboarding screenshots
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/Settings/ENAUITests_03_Settings.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: admin, chore

#3646 Feature/9411 file scanner UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
  src/xcode/ENA/ENAUITests/FileScanner/ENAUITests_17_FileScanner.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#3650 Fix/#9824 settings out of sync
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewController.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/StoreTests.swift
Labels: bug

#3652 make onboardings more independent of flaky system settings jump.
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
Labels: admin, chore

#3653 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3656 Fix/9504 is validity state new fixes
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
Labels: bug

#3651 Feature/9795 filescanner unittests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/QRCodeDetecting.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerCoordinatorViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerErrorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/QRCodeDetectorFake.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/QRCodeParsableMock.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: task

#3659 Protocol Buffer update for release 2.13.x at Thu Oct 7 12:02:44 UTC 2021
  proto/resources/internal/stats/key_figure_card.proto
  proto/resources/internal/stats/local_statistics.proto
Labels: admin

#3660 Fix/screenshots
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: tests

#3661 Feature/9909 update protobuf for statistics
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
Labels: task

#3666 Fix/9904 wrong error message
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerErrorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#3673 Feature/9814 new appstore graphics
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CheckinQRCodeParser.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
Labels: chore

#3678 Update Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/VaccinationHintCellModelTests.swift
Labels: text-change

#3683 Feature/9809 adjust info screen release 2.13
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#3690 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#3695 Feature/9876 fix tests statistics
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
Labels: tests, task

#3696 Story/9773 statistics hospitalization
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/hospital_rate_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_7Days_Hospital_Rate.imageset/hospital_rate_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCard.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/RegionStatisticsData.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeStatisticsCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_Statistics+SupportedIDsTests.swift
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/StatisticsProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/stats.bin
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
  src/xcode/ENA/ENAUITests/LaunchArguments.swift
Labels: feature

#3693 Story/9772 fault tolerance certificates/9953 grouping migration
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore+Migration.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#3704 fix/Dispatch presentation on main.
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
Labels: bug

#3711 Attempt to fix flaky FileScannerCoordinatorViewModelTests.
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/__tests__/FileScannerCoordinatorViewModelTests.swift
Labels: bug

#3715 Chore/split building and testing
  .circleci/config.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/TestPlans/AntigenTestProfileUITests.xctestplan
  src/xcode/ENA/TestPlans/AppInformationUITests.xctestplan
  src/xcode/ENA/TestPlans/CheckInsUITests.xctestplan
  src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
  src/xcode/ENA/TestPlans/CreateHealthCertificateUITests.xctestplan
  src/xcode/ENA/TestPlans/DataDonationUITests.xctestplan
  src/xcode/ENA/TestPlans/DeltaOnboardingUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureDetectionUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureLoggingUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureSubmissionUITests.xctestplan
  src/xcode/ENA/TestPlans/FileScannerUITests.xctestplan
  src/xcode/ENA/TestPlans/HomeUITests.xctestplan
  src/xcode/ENA/TestPlans/OnBehalfCheckinSubmissionUITests.xctestplan
  src/xcode/ENA/TestPlans/OnboardingUITests.xctestplan
  src/xcode/ENA/TestPlans/QuickActionsUITests.xctestplan
  src/xcode/ENA/TestPlans/RecycleBinUITests.xctestplan
  src/xcode/ENA/TestPlans/SettingsUITests.xctestplan
  src/xcode/ENA/TestPlans/StatisticsUITests.xctestplan
  src/xcode/ENA/TestPlans/TraceLocationsUITests.xctestplan
  src/xcode/ENA/TestPlans/UniversalQRCodeScannerUITests.xctestplan
  src/xcode/ENA/TestPlans/UpdateOSUITests.xctestplan
  src/xcode/ENA/TestPlans/ValidateHealthCertificateUITests.xctestplan
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
Labels: admin

#3717 Fix/10067 gradient issue
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.xib
Labels: bug

#3721 Fix/restore certificate from bin
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/RecycleBin.swift
Labels: bug

#3712 fix/7968 align layout of country list in onboarding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
Labels: community, mirrored-to-jira, Fix 2.13

#3725 Changes to the sentence & capitalization
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#3601 Release/9152-Publish-failing-screenshots-in-general-channel
  .circleci/config.yml
  scripts/announce_failing_screenshots.sh
Labels: admin

#3732 Fix sonar nightly
  .circleci/config.yml
Labels: admin

#3730 Support parsing multiple codes from the same QRCodeParser instance
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/QRCodeParser.swift
Labels: bug

#3737 Bump to next Version 2.13.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin
