Repository corona-warn-app/cwa-app-ios, pull requests merged in 2021-04, with the labels that each got.

#2328 Crash if user clicks on link in "Exposure check failed" detail screen
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
Labels: bug

#2332 Fix flaky TraceLocation tests
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: bug

#2317 Feature/6088 use presence tracing config parameters to parse qr codes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/SAPDownloadedPackage.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/EncodingType.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
Labels: task

#2330 Contact Diary Store Key Not Regenerated After Reset
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreCreation.swift
Labels: bug

#2336 Fix/Improve Flaky UI Test
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENAUITests/Helper/UITestHelper.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: chore

#2333 Fix TraceWarningDiscoveryCall
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDiscoveryTests.swift
Labels: bug

#2326 Feature/6089 configure error correction level
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/TraceLocation+GenerateQRCode.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/__tests__/TraceLocationDetailsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodeErrorCorrectionLevelProvider.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodeErrorCorrectionLevelType.swift
Labels: task

#2331 Fixed a bug in data privacy note EN/PL/RO/BG
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: Fix 2.0

#2323 Feature/6100 known issues event reg/xxx adjust check ins
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/__tests__/CheckInTimeModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewModel.swift
Labels: task

#2337 Bump to next Version 2.0.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2334 Bugfix/fix sort in contact diary
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
Labels: bug

#2335 Feature/5588 event host/small tasks
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/TraceLocation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/TraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/__tests__/TraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/__test__/TraceLocationsOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2329 AppLauncher - QR (nur Darstellung im AppLauncher)
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#2338 fix/ Automatic Checkout – Contact Journal Entries - Checkout Notifications
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
Labels: bug

#2340 Feature/5958 dev menu trace locations
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMMostRecentTraceLocationCheckedInto/DMDMMostRecentTraceLocationCheckedIntoViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMMostRecentTraceLocationCheckedInto/DMDMMostRecentTraceLocationCheckedIntoViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMMostRecentTraceLocationCheckedInto/DMRecentTraceLocationCheckedInto.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMRecentCreatedEvent/DMRecentCreatedEventViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMRecentCreatedEvent/DMRecentCreatedEventViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#2339 Feature/5588 event host/unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/__test__/TraceLocationsConfigurationViewModelTest.swift
Labels: task

#2347 Edit check-in: text fields too small
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
Labels: bug

#2348 Match issue templates to Android ones
  .github/ISSUE_TEMPLATE/01_bugs.md
  .github/ISSUE_TEMPLATE/02_enhancement.md
  .github/ISSUE_TEMPLATE/03_questions.md
Labels: admin

#2345 Event Creation: UI elements to don't change on touch
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/AddEventTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
Labels: bug

#2344 Contact journal entries cut off
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__test__/DiaryDayEntryCellModelTest.swift
Labels: bug

#2354 Reset encryption key on EventStore reset
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
Labels: bug

#2351 Fix suggested checkout time max duration value
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
Labels: bug

#2353 Change in poster descriptions based on tech specs changes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/sample_qr_code_template/default_qr_code_poster_template_ios.bin
Labels: task

#2343 Improve wording of Trace Location info screen (COMMUNITY) (Closes #2342)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2355 5585 check in download matching risk calculation/add some unit tests
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#2362 Contact Journal-Info-DSE can be closed via swipe down
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
Labels: bug

#2318 Feature/5586 event check in processing key submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/PlausibleDeniabilityService.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Extensions/Array+SaveAccess.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/ArrayExtensionTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/CheckinSplittingService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionServiceFactory.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/TestPlans/SmokeTests.xctestplan
Labels: feature

#2352 Protocol Buffer update for release 2.0.x at Tue Apr 6 08:07:37 UTC 2021
  proto/resources/internal/pt/qr_code_poster_template.proto
  proto/resources/internal/pt/trace_location.proto
Labels: admin

#2359 Feature/6112 share sheet description and pdf file name
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/PrintVersion/TraceLocationPrintVersionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/PrintVersion/TraceLocationPrintVersionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: task

#2358 Event Creation: text fields too small
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
Labels: bug

#2368 Bump to next Version 2.0.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2363 Missing background and frame on inactive "Save" button
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
Labels: bug

#2360 Missing close element on the infoscreen of Event Registration (Organizer)
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Info/TraceLocationsInfoViewController.swift
Labels: bug

#2361 Check-in-Information-DSE can be closed via swipe down
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewController.swift
Labels: bug

#2370 Feature/6095 6179 translations info screen to announce new release features for 2.1
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2372 Wording changes for new version features 2.0
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2357 EventStore cleanup – Remove update tracelocation API.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceLocation/UpdateTraceLocationQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
Labels: task

#2369 Fix/duplicate journal entry creation
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: bug

#2373 Text is cut off on the infoscreen of Event Registration (Organizer)
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
Labels: bug

#2364 https://github.com/corona-warn-app/cwa-app-android/pull/2747#6204
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2367 Feature/6100 known issues event reg/6114 keyboard avoidance
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
Labels: bug, feature

#2366 Fix/contact journal location creation date
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
Labels: bug

#2375 Feature/6100 known issues event reg/6230 missing localization for button einchecken
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2377 Fix/6246 App Crash When Creating QR Code
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
Labels: bug

#2379 Re-Add a removed test to the project.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: task

#2374 Add hash test
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/TraceLocationTests.swift
Labels: task

#2356 Use Base64url instead of Base32 encoding for QR URL
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/__tests__/SAP_Internal_Pt_TraceLocation_Tests.swift
  src/xcode/ENA/ENA/Source/Extensions/Foundation+Base64URL.swift
  src/xcode/ENA/ENA/Source/Extensions/TraceLocation+GenerateQRCode.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/Base32DecodingTests.swift
Labels: feature

#2349 Feature/5686 add unit tests for qr code scan
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/__tests__/TraceLocationDetailViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/__tests__/CheckinQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelperTests.swift
Labels: task

#2383 Bump to next Version 2.0.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2376 Corrected 'Information' to 'Informationen' in strings file (EXPOSUREAPP-6206)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2381 Tab Bar has wrong Check-in icon
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Icons_Tabbar_Checkin.pdf
Labels: bug

#2388 Feature/6120 add error messages for qr codes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/__tests__/CheckinQRCodeScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#2384 Add checkins to the submission payload.
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#2380 Feature/6095 adjust info screen to announce new release features for 2.1
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2393 Remove Base32 from licenses
  licenses.json
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
Labels: admin

#2394 Bump to next Version 2.0.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2386 Fix/6214 not possible to adjust the time for automatic check out
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/__tests__/TraceLocationDetailViewModelTests.swift
Labels: bug

#2385 External camera is not redirecting to the event details
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
Labels: bug

#2390 Check content length.
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
Labels: task

#2399 Feature/checkin download logging
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/CheckinRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningMatching.swift
Labels: chore

#2378 Contact Journal - Actual days do not appear directly
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__test__/DiaryOverviewViewModelTest.swift
Labels: bug

#2392 QRGeneration-Information-DSE can be closed via swipe down
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#2398 Fix/6241 restrict check in time
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/__tests__/CheckInTimeModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewModel.swift
Labels: feature

#2397 Feature/5409 check in info screen/5821 screenshots
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDescriptionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Info/CheckinsInfoScreenViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsHeaderCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/Cells/TraceLocationDetailsLocationCell.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_09_CheckIns.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: task

#2400 Bump to next Version 2.0.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2404 Fix/6288 checkin submission fixes
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
Labels: bug

#2402 6277 close button missing label
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
Labels: bug

#2403 remove subscriptions after obtaining the TraceLocation or the error
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
Labels: bug

#2406 Fix/6311 change check in time triggers UI issue
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
Labels: bug

#2405 recieve on main to update ui without crashing
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
Labels: bug

#2410 Fix/6320 aerosol decay
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/PresenceTracingSubmissionConfiguration/AerosoleDecayFunctionLinear.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/PresenceTracingSubmissionConfiguration/DurationFilter.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/PresenceTracingSubmissionConfiguration/PresenceTracingSubmissionConfiguration.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/CheckInTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/Models/CheckinTestCase.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/Models/CheckinTestCasesWithConfiguration.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__test__/checkin-timeinterval-derivation.json
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__test__/RiskCalculationTest.swift
Labels: bug

#2411 set proper background color and navigation bar to small
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/PrintVersion/TraceLocationPrintVersionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
Labels: bug

#2418 Fix/event check in fixes
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/Cells/CheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/Cells/__tests__/CheckinCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/__test__/TraceLocationsConfigurationViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/TraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/Cells/__tests__/TraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: bug

#2408 tilt gradient layer
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: bug

#2391 App launcher displays the funktion "Einchecken", although the access to camera is denied by user
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/NotificationName.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#2419 Bump to next Version 2.0.0.8
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2409 updated text on tab bar item
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: bug, text-change

#2420 Update Protos for RAT
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
Labels: chore

#2422 Added additional new feature to 2.1 features
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2423 Reload table view after delete animation to introduce the cells to th…
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/__test__/CheckinsOverviewViewModelTest.swift
Labels: bug

#2416 Feature/exclude own checkin from matching
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/EditCheckinDetailViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/CheckinSplittingService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Extensions/Checkin+Update.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/CreateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/Checkin/UpdateCheckinQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/StoreV1/EventStoreSchemaV1.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Checkin+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/CheckinSplittingServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/Model/CheckinTests.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/CheckinRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/CheckinRiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ENAExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/__tests__/TraceWarningMatcherTests.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: feature

#2424 Feature/6364 enhance risk calculation logging
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/CheckinRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
Labels: task

#2425 Fix/6355 long event description hides adress
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewController.swift
  src/xcode/ENA/ENA/Source/Extensions/PDFDocument+EmbedImage.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/PDFDocument+EmbedImageTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/sample_qr_code_template/default_qr_code_poster_template_ios.bin
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
Labels: bug

#2431 Compile SwiftLint from source to fix homebrew CDN hickup
  .circleci/config.yml
Labels: admin

#2432 Feature/6377 verify important qr code attributes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelperTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2426 Feature/5138 international hotline
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/phone_foreign.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/phone_foreign.imageset/phone_foreign.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionHotlineViewControllerTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionStepCell.swift
Labels: feature

#2434 Bump to next Version 2.0.0.9
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2430 Feature/5949 rat submission flow/6149 warning if test already registered
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Overwrite_Notice.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Overwrite_Notice.imageset/Illus_two-test-results_dark-mode.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Overwrite_Notice.imageset/Illus_two-test-results_light-mode.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DismissHandlingNavigationController/DismissHandlingNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/TestOverwriteNotice/TestOverwriteNoticeViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TestOverwriteNotice/TestOverwriteNoticeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TestOverwriteNotice/__tests__/TestOverwriteNoticeViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2433 Fix/6373 update dev menu poster generation
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewController.swift
Labels: task

#2428 Feature/6144 rat preparations/6148 update qr code scanner to support rat
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Foundation+Base64URL.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/AntigenTestInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestQRCodeInformation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelGuidTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
Labels: task

#2438 Feature/5409 check in info screen/5821 UI tests
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: task

#2442 Fix/6400 reject manipulated qr codes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRScannerError.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelper.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeVerificationHelperTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#2429 Feature/6151 handle consent rat pcr
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#2443 12.5 - Event registration - QR code scan with native camera
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: bug

#2445 Fix/6393 checkin update crash
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/Cells/CheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Overview/TraceLocationsOverviewViewController.swift
Labels: bug

#2446 Fix/6364 event store fix cleanup
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
Labels: bug

#2441 Fix/6366 text changes existing screens
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionWarnOthersViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionWarnOthersViewControllerTests.swift
Labels: text-change

#2447 Feature/6152 modal success screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSuccessViewControllerTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: feature, task

#2448 Contact Journal - Actual days do not appear directly
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
Labels: bug

#2449 Event Check-in - App Launcher - wrong target screen
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
Labels: bug

#2444 Feature/5582 Event Check-in UI Scan QR Code/6181 UI Test
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_09_CheckIns.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_10_TraceLocations.swift
Labels: task

#2435 Feature/5948 retrieve test result/6154 background update
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestResult.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/AntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/PCRTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/TestResultTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
Labels: task

#2451 Bump to next Version 2.0.0.10
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2452 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2437 Make ExposureSubmissionTestResultViewController handle RAT and PCR
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/AntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/PCRTest+Mock.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/View Helpers/CountdownTimer.swift
  src/xcode/ENA/ENA/Source/View Helpers/__tests__/CountdownTimerTests.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.swift
Labels: feature

#2454 Capitalization of 'Check-in' in privacy-policy.html #6461
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#2453 Chore/update default app config
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/default_app_config_200
Labels: chore

#2440 Feature/5949 6146 update exposure submission intro view controller
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Funktion1.imageset/Illu_Submission_Funktion1-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Funktion1.imageset/Illu_Submission_Funktion1.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_registration.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_registration.imageset/Illu_Test_registrieren_dark-mode.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Test_registration.imageset/Illu_Test_registrieren_light-mode.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENAUITests/ENAUITests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ExposureSubmissionUITests.swift
Labels: task

#2455 Feature/5949 rat submission flow/6394 open correct test result from notification
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: task

#2456 Add submission of test type.
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
Labels: task

#2458 Update fastlane to 2.180.1
  src/xcode/Gemfile.lock
Labels: admin

#2457 Feature/6094 data privacy note 2.1
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
Labels: text-change

#2459 Only reset triggerReload to false if it was true before
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
Labels: bug

#2462 Fix/6370 background color check in screen
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Background Colors/ENA Background Light Gray Color.colorset/Contents.json
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
  src/xcode/ENA/ENA/Source/Views/Common/HtmlTextView.swift
Labels: bug

#2232 Dont block Main-Thread when running PPA with many ExposureWindows
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: bug

#2463 Fix/6295 etag missing in request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPosterGeneration/DMPosterGenerationViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMRecentCreatedEvent/DMRecentCreatedEventViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Details/TraceLocationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProvider.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/QRCodePosterTemplate/QRCodePosterTemplateProviding.swift
Labels: bug

#2461 Feature/5591 Automated Screenshots
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/CheckinQRCodeScannerViewModel.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
  src/xcode/ENA/ENAUITests/TraceLocations/ENAUITests_09_TraceLocations.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: task

#2467 TestResult metadata should not be sent if status is pending and under 165 hours
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: bug

#2468 fix/6508 missing checkin background image
  src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift
Labels: bug

#2464 Feature/6435 rat 3rd party solution integration
  src/xcode/ENA/ENA/Resources/ENA.entitlements
  src/xcode/ENA/ENA/Resources/ENACommunity.entitlements
  src/xcode/ENA/ENA/Resources/ENATest.entitlements
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestQRCodeInformation.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/QRCodeScanner/apple-app-site-association
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/QRScanner/ExposureSubmissionQRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#2460 Event-Check-in Native Camera - wrong screenflow if app is only updated
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckinCoordinator.swift
Labels: bug

#2471 Fix/6521 techspecs change - days since most recent date at risk level
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
Labels: bug

#2472 Gradient is horizontal and not tilted
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.xib
Labels: bug

#2475 Feature/6529 check in selection in submission flow
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Selected.imageset/Checkin_Checkmark_Selected.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Selected.imageset/Checkin_Checkmark_Selected_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Selected.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Unselected.imageset/Checkin_Checkmark_Unselected.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Unselected.imageset/Checkin_Checkmark_Unselected_Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Checkin_Checkmark_Unselected.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/Checkin.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocationType.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/Cells/ExposureSubmissionCheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/Cells/ExposureSubmissionCheckinDescriptionCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/Cells/ExposureSubmissionCheckinDescriptionTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/Cells/ExposureSubmissionCheckinTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/ExposureSubmissionCheckinsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionCheckins/ExposureSubmissionCheckinsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionError.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ENAExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#2480 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#2479 Fix/unit tests
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ENAExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENAUITests/CheckIns/ENAUITests_10_CheckIns.swift
Labels: Fix 2.1

#2473 refactoring AntigenTest, added Unittest as well
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/AntigenTestInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/AntigenTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
Labels: feature

#2478 Feature/6552 update anitigen qr code to use hash
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route+Equatable.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/AntigenTestInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestQRCodeInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/AntigenTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/AntigenTestInformation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
Labels: bug

#2466 Event Check-in - scanned QR: change automatical checkout time difficult to see because of missing autoscroll/focus
  src/xcode/ENA/ENA/Source/Scenes/Checkin/CheckInDetail/TraceLocationDetailViewController.swift
Labels: bug

#2483 Bump to next Version 2.1.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2484 Set autocapitalization for input fields
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
Labels: bug

#2486 Remove Codeowners
  CODEOWNERS
Labels: admin

#2481 Fix/5941 low risk card title fixes
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell+ExposureDetection.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITestsHome.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: bug

#2487 updated alert text if qr code format is wrong
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: feature, text-change

#2476 Event-Check-in Native Camera - wrong screenflow if installed app isn't onboarded
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: bug

#2492 Rearrange Backgroundtasks priority
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
Labels: feature

#2490 Fix/6585 tan hotline only for pcr test
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2488 Fix/6551 error messages and other bugs
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: Fix 2.1

#2489 Fix/6509 missing background and frame on several buttons in dark mode
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Views/BaseElements/ENAButton.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: bug

#2470 Feature/6063 censor private logs/storybranch
  README.md
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/StringInterpolation+Private.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/TanInputViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: feature

#2494 do not show loading indicators when we navigate back from warn others…
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
Labels: bug

#2501 Bump to next Version 2.2.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2502 Bump to next Version 2.1.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#2504 Fix for typo in New Functions
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2503 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
Labels: text-change

#2505 Fix typo in New Functions UI
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#2506 remove the hashing from the AntigenTestInformation model
  src/xcode/ENA/ENA/Source/Models/Submisstion/AntigenTestInformation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/QRScanner/ExposureSubmissionQRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#2499 Fix/6324 aufenthaltsdauer anpassen date time announcements
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInBottomCornerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTimeModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Cells/CheckInTopCornerCell.swift
Labels: bug

#2507 Feature/submit checkins once
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+CheckinSubmission.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__test__/ExposureSubmissionCheckinTests.swift
Labels: feature

#2509 Bump to next Version 2.1.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin
