Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-10, with the labels that each got.

#4810 fix/13975 missing navigation bar booster vaccination
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/BoosterDetails/BoosterDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
Labels: bug

#4812 Update the white risk card check to exclude bluetooth state
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
Labels: bug

#4818 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4816 Fix/9679 info button alignment on certificate screen
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
Labels: bug

#4814 Fix/9746 missing swipe down on trace locations infoViewController
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Info/TraceLocationsInfoViewController.swift
Labels: bug

#4811 Fix/9928 bullet point text without scaling when Notification On
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
Labels: bug

#4817 Fix/9412 date has wrong format on IP-History
  src/xcode/ENA/ENA/Source/Utils/ENAFormatter.swift
Labels: bug

#4815 Fix/14021 unseen news and red dot on admission state changes
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4821 Fix/11293 take extra screenshots for the risk card
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: bug

#4824 story/14049 adjust info screen release 2.28
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4823 story/14051 adapt privacy notice text release 2.28
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4831 Fix/7267 & 5429 dark mode colors do not match
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illu_EUCHWideOnboarding-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_EU_Interop.imageset/Illustration-Laenderuebergreifende_Risiko-Ermittlung-Dark.pdf
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/BackgroundAppRefresh/InfoBoxView.xib
Labels: bug

#4830 fix skipped ELS tests after refactoring
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/ELSSubmitResource.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/Model/ELSError.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
Labels: task

#4828 Fix/9746 initial swipe down redirects wrong screen
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Info/TraceLocationsInfoViewController.swift
Labels: bug

#4833 Update scrolling behaviour
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Model/LocalStatisticsRegion.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProviding.swift
Labels: task

#4827 Fix/8921 color inconsistencies in dark mode
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputDescriptionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TraceLocationsCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/Cells/SelectTraceLocationTypeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeFooterView.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeHeaderView.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewController.swift
Labels: bug

#4835 Fix/5713 button area formatting issues
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DaysSinceInstallTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/EuTracingTableViewCell.swift
Labels: bug

#4836 Fix/5723 flags horizontal left padding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController+Extension.swift
Labels: bug

#4838 Fix/14129 Pandemic Radar - Typos and Information Text adaption
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#4844 Fix/14110 outdates timestamp
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug

#4843 Update Statistics UITests and screenshots
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: task

#4841 Fix/14127 Pandemic radar button UI issues
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/export_icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/export_icon.imageset/dark export.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/export_icon.imageset/export_icon.pdf
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCardView/HomeLinkCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeLinkCardViewModelTests.swift
Labels: bug

#4846 fix/14110 outdated timestamp privacy texts EN
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: bug

#4847 Fix/14020 Add accessibility id for Checkin Texts Labels
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Info/TraceLocationsInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/TraceLocationsOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/Header/SelectTraceLocationTypeHeaderView.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/TypeSelection/TraceLocationTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/EmptyStateView/EmptyStateView.swift
  src/xcode/ENA/ENA/Source/Views/EmptyStateView/EmptyStateViewModel.swift
Labels: bug

#4852 Fix/14128 Added local statistic does not focus to the added tile on iOS 12.5
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
Labels: bug

#4829 Fix/14021 unseen news and red dot on admission state changes
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4851 Fix/10044 Universal Scanner "Datei öffnen" Label Color
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Button Colors/IconWithText.colorset/Contents.json
Labels: bug

#4850 Fix/14149 Crash when scanning a redeemed code
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/UserAntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/UserPCRTest+Mock.swift
Labels: bug

#4853 Fix/14149 REVERT FIX for app crash when scanning redeemed qr code
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/UserAntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/UserPCRTest+Mock.swift
Labels: chore

#4856 Fix/14919 UI issue on the screen "Einstellungen"
  src/xcode/ENA/ENA/Source/Scenes/Settings/Settings/SettingsViewController.swift
Labels: bug

#4859 Fix/14207 Booster Notification Screen - unnecessary space in subtitle
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/BoosterDetails/BoosterDetailsViewModel.swift
Labels: bug

#4860 Fix/14168 app includes wrong note
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4857 14214: UI issue on the screen "Ausführliche Informationen zur Datenspende"
  src/xcode/ENA/ENA/Source/Scenes/DataDonationDetails/DataDonationDetailsViewModel.swift
Labels: bug

#4861 Fix/14163 UI issues on several screens.
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#4858 Fix/11497 some screen texts do not resize
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/DiaryAddAndEditEntryViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayAddTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/Cells/DiaryEditEntriesTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/EditEntries/DiaryEditEntriesViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDescriptionTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/TestCertificateRequest/TestCertificateRequestTableViewCell.xib
Labels: bug

#4863 Fix/11123 Add hyphenation also to My QR Codes and My Checkins
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/String+Attributed.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/Cells/CheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/Cells/__tests__/CheckinCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/OnBehalfTraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/__tests__/OnBehalfTraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/Cells/TraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/Cells/__tests__/TraceLocationCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/__tests__/TraceLocationsOverviewViewModelTest.swift
Labels: bug

#4867 Fix/14149 app crash redeemed code
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#4865 Fix/6210 wrong font on Check-In-Information Screen
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Info/CheckinsInfoScreenViewModel.swift
Labels: bug

#4864 Fix/10953 support link preview pop-up not shown
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewModel.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITests_02_AppInformation.swift
Labels: bug
