Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-12, with the labels that each got.

#4907 Fix testflight pipeline issue
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: chore

#4908 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4911 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-issue

#4912 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-issue

#4913 Task/14376 Handle SRS server warning for truncated keys
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/SRSKeySubmissionResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/SRSSuccessReceiveResource.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4914 Fix/7109 add alert view on error log
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/BottomErrorReportViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITests_02_AppInformation.swift
Labels: bug

#4917 Story/14382 Switch to BMG pandemic radar
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCard.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCardView/HomeLinkCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/HomeLinkCardViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_LinkCard+Mock.swift
Labels: feature

#4920 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4919 Fix crash on fakeService
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
Labels: bug

#4921 Task/14280 add entry to contact journal
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Warn_light.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Warn_light.imageset/Warn_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__tests__/DiaryAddAndEditEntryViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/__tests__/DiaryDayViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDay.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/DiaryDaySubmission.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Model/__tests__/DiaryDayTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/__tests__/DiaryOverviewDayCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore+Creation.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/DiaryStoringProviding.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV6/ContactDiaryMigration5To6.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV6/ContactDiaryStoreSchemaV6.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/MockDiaryStore.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4924 Fix migration crash
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/StoreV6/ContactDiaryMigration5To6.swift
Labels: bug

#4922 Task/14408 Update SRS legal texts
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#4925 Fix/14396 Adapt headers["cwa-keys-truncated"] casting
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/SRSSuccessReceiveResource.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4926 Fix/14385 new features screen headings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
Labels: bug

#4927 Fix/update srs assets
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Test Tube.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Ventilation.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_high_small.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Attention_low.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_admission_state.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-No-Certificate-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Positive-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Warn-Others-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Self_Test_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Self_Test_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Submission_PositiveSelfTest_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Submission_PositiveSelfTest_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Illu_Submission_SRS_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Illu_Test_positive_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Illu_Test_positive_light.pdf
Labels: bug

#4929 Fix/14397 crash on check-in screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4930 Fix/14402: SRS already warned - Popup shows "90 days" instead of config value "timeBetweenSubmissionInDays"
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSPreconditionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4932 Fix/7830 add numbers on risk level change alert view
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: bug

#4934 Fix/14412 contact diary warned others entry UI issues
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#4939 Fix/14405 various icons on different thank you screens
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/Icons - ContactJournal.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/icons_contactjournal_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/icons_contactjournal_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Icons - ErhohtesRisiko Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Icons - ErhohtesRisiko Light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Icons - ErhohtesRisiko.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/Cross_DarkMode.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/Icons - RedPlus.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/cross_light.pdf
Labels: bug

#4937 Task/14282 UI tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACServiceMock.swift
  src/xcode/ENA/ENA/Source/Services/SRSService/SRSService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: task

#4933 Task/14355 add submission unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/__tests__/SRSKeySubmissionResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/OTPAuthorizationForSRSResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/__tests__/OTPAuthorizationForSRSResourceTests.swift
Labels: task

#4940 Compiler Flag
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/MockRiskProvider.swift
Labels: chore

#4942 Adapt privacy policy texts for release 3.0
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4944 Fix/14449 14455 SRS Consent Screen
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: bug, task

#4943 Fix/14454: Self-test: only one times warning within 24h allowed is blocking testing
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPACService/DMPPACViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACServiceMock.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/__tests__/PPACServiceTest.swift
  src/xcode/ENA/ENA/Source/Services/SRSService/SRSService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#4945 Fix/14405 blue icons thank you screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultFamilyMemberViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
Labels: bug

#4946 Fix/14429 duplicate URL
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
Labels: bug

#4935 Fix/10243 layout of warn on behalf
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTypeTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionViewController.swift
Labels: bug

#4947 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-issue

#4950 Fix/14467: SRS - Warn others "Achtung" popup - "abbrechen" has wrong screenflow
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4951 Fix the overlap between submission cells in contact diary
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#4953 Add missing identifiers for contact diary
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: chore

#4952 Fix/14482 SRS: ConfirmWarnOthers alert action order
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4954 Fix/14466 SRS Data protection screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSDataProcessingInfo/SRSDataProcessingInfoViewController.swift
Labels: bug

#4956 Fix/14148: Event Check-in - default duration 00:00 when event has same start date and end date
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
Labels: bug

#4957 Fix/13385 correct the enum order in the srs type screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
Labels: bug

#4958 Fix/14468 mapping SRSKeySubmissionResourceError and corresponding message
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/SRSKeySubmissionResource.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4915 Admin/SPM packages latest versions
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: admin

#4961 Fix/14491 SRS consent screen legal texts in TR
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#4960 Fix/9623: Statistic cards - local 7 day incidence is empty when you turn WLAN off
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Utils/InternetConnectivityMonitor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4962 13750: Certificate for PCR Test older than 72 Hours is exported
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
Labels: bug

#4963 Patch 1
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4965 add accessibilityIdentifier to the DM datapicker
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMInstallationDate/DMInstallationDateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMInstallationDate/DMInstallationDateViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: bug, accessibility

#4964 Fix/14485 wrong entry in table self report submissions
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMInstallationDate/DMInstallationDateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMInstallationDate/DMInstallationDateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/SubmissionTestType.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: bug

#4969 Renew simulator cerificates VC 1/2 VC 2/2.
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
Labels: admin

#4970 Show the day picker directly in the devmenu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerTableViewCell.swift
Labels: chore

#4968 Fix/8541: Certificate validity: Spinning the country selection wheel and closing the section prevents UI update
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/CountrySelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellPickerSelectionPreventableMock.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellTests.swift
Labels: bug
