Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-04, with the labels that each got.

#4407 GitHub actions
  .circleci/config.yml
  .github/workflows/MergeToReleaseBranch.yml
  .github/workflows/PullRequest.yml
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENAUITests/UpdateOS/ENAUITests_08_UpdateOSUITests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Fastfile
  src/xcode/fastlane/README.md
  src/xcode/fastlane/Snapfile
Labels: admin

#4417 Feature/11890 cert revocation/generate protos
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/gen/output/internal/dgc/revocation_chunk.pb.swift
  src/xcode/gen/output/internal/dgc/revocation_kid_list.pb.swift
  src/xcode/gen/output/internal/dgc/revocation_kid_type_index.pb.swift
  src/xcode/gen/output/internal/ppdd/ppac_android.pb.swift
Labels: chore

#4414 Save ENA.xcresult on failure
  .github/workflows/MergeToReleaseBranch.yml
  .github/workflows/PullRequest.yml
  .github/workflows/Screenshots.yml
  src/xcode/fastlane/Fastfile
Labels: admin

#4420 Route notifications for family member tests
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: task

#4406 Fix/12367 bg task expiration
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/HealthCertificateQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRestorationHandler.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/ValidationStateServiceTests.swift
Labels: bug

#4412 Feature/12219 testprocess family members/12482 unit tests exposure submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultFamilyMemberViewModelTests.swift
Labels: task

#4421 Add Nightly Workflow
  .circleci/config.yml
  .github/workflows/Nightly.yml
Labels: admin

#4428 disable testing on dev branches on CircleCI
  .circleci/config.yml
Labels: admin

#4426 possible memory leak - added some log informations too
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
Labels: bug, chore

#4418 Add resource for kid list.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/Locator+KIDList.swift
Labels: task

#4423 Fix/12607 notification is not created after blocked certificate is scanned
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#4430 Fixing ContactJournalUITests flakyness
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: bug, admin

#4429 Move RCs creation from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/ReleaseCandidate.yml
  src/xcode/fastlane/Matchfile
Labels: admin

#4431 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4432 Fix/test add statistics button maximum number of cards
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: bug, admin

#4434 Fix/disable flaky test
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
Labels: bug

#4436 Bump to next Version 2.21.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4438 receive on main
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
Labels: bug

#4419 Feature/11890 cert revocation/12561 fetch kid type index
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/__tests__/KIDListResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeIndex/KIDTypeIndexResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeIndex/Locator+KIDTypeIndex.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeIndex/__tests__/Locator+KIDTypeIndexTests.swift
Labels: task

#4439 Feature/12562 screenshots for family members
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestResult.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsTestResultCollector.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
  src/xcode/ENA/ENAUITests/Utils/UITestingParameters.swift
  src/xcode/ENA/FamilyMemberUITests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: feature

#4442 Feature/12655 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/__tests__/FamilyMemberCoronaTestCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/__tests__/FamilyMemberCoronaTestsViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/MockFamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
Labels: task

#4441 Fix/12676 tap on notification when app is terminated opens home
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
Labels: bug

#4437 Finish transition away from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/Nightly.yml
  sonar-project.properties
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA.xcodeproj/xcshareddata/xcschemes/ENA.xcscheme
  src/xcode/ENA/FamilyMemberUITests.xctestplan
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/AntigenTestProfileUITests.xctestplan
  src/xcode/ENA/TestPlans/AppInformationUITests.xctestplan
  src/xcode/ENA/TestPlans/CheckInsUITests.xctestplan
  src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
  src/xcode/ENA/TestPlans/CreateHealthCertificateUITests.xctestplan
  src/xcode/ENA/TestPlans/DataDonationUITests.xctestplan
  src/xcode/ENA/TestPlans/DeltaOnboardingUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureDetectionUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureLoggingUITests.xctestplan
  src/xcode/ENA/TestPlans/ExposureSubmissionUITests.xctestplan
  src/xcode/ENA/TestPlans/FileScannerUITests.xctestplan
  src/xcode/ENA/TestPlans/HomeUITests.xctestplan
  src/xcode/ENA/TestPlans/OnBehalfCheckinSubmissionUITests.xctestplan
  src/xcode/ENA/TestPlans/OnboardingUITests.xctestplan
  src/xcode/ENA/TestPlans/QuickActionsUITests.xctestplan
  src/xcode/ENA/TestPlans/RecycleBinUITests.xctestplan
  src/xcode/ENA/TestPlans/ReissueHealthCertificateUITests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/SettingsUITests.xctestplan
  src/xcode/ENA/TestPlans/SmokeTests.xctestplan
  src/xcode/ENA/TestPlans/StatisticsUITests.xctestplan
  src/xcode/ENA/TestPlans/TicketValidationUITests.xctestplan
  src/xcode/ENA/TestPlans/TraceLocationsUITests.xctestplan
  src/xcode/ENA/TestPlans/UniversalQRCodeScannerUITests.xctestplan
  src/xcode/ENA/TestPlans/UpdateOSUITests.xctestplan
  src/xcode/ENA/TestPlans/ValidateHealthCertificateUITests.xctestplan
  src/xcode/fastlane/Fastfile
Labels: admin

#4443 Fix/12663 app in dead mode after tap on notification on lock screen
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#4445 Fix/12703 background task crash
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#4440 Dispatch on persons queue to avoid conflicts.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
Labels: bug

#4435 Feature/11890 cert revocation/12578 calculate revocation entries
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateRevocationEntries.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateRevocationEntriesTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_14_ValidateHealthCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/MockDigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Error.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/Extensions/DigitalCovidCertificate+Convenience.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/SignatureVerification/DCCSignatureVerification.swift
Labels: task

#4425 Add resource for kid type chunk.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeChunk/KIDTypeChunkResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeChunk/Locator+KIDTypeChunk.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeChunk/__tests__/KIDTypeChunkResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeChunk/__tests__/Locator+KIDTypeChunkTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/__tests__/LocatorTests.swift
Labels: task

#4446 Fix/sonar branch
  .github/workflows/Nightly.yml
Labels: admin

#4450 Fix/12768 revoked certificate cant be changed back to valid
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeCCLService.swift
Labels: bug

#4449 Fix ValidateHealthCertificate ui-tests
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_14_ValidateHealthCertificate.swift
Labels: admin

#4447 Adjust Info Screen to announce new Release-Features for 2.22
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4452 Smaller CI fixes
  .github/workflows/MergeToReleaseBranch.yml
  .github/workflows/Nightly.yml
Labels: admin

#4455 Bump to next Version 2.22.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4456 Fix family member test crash
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewModel.swift
Labels: bug

#4453 Feature/12372 family members rat profile/12648 antigen profile overview
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AntigenTestProfile_Empty.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AntigenTestProfile_Empty.imageset/Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AntigenTestProfile_Empty.imageset/Light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Models/Profile/AntigenTestProfile.swift
  src/xcode/ENA/ENA/Source/Models/Profile/__tests__/AntigenTestProfileTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/__tests__/AntigenTestProfileViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/__tests__/CreateAntigenTestProfileViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/AddAntigenTestProfileCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/AntigenTestPersonProfileCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/AntigenTestPersonProfileCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionIntroViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
Labels: feature

#4460 RevocationList Provider update list
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeChunk/KIDTypeChunkResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeIndex/KIDTypeIndexResource.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/__tests__/HealthCertificatePDFVersionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/__tests__/RecycleBinItemCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/CertificateSelection/__tests__/TicketValidationCertificateSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceBoosterNotificationRulesTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateMapping.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/CWATestCase+HealthCertificateConvenience.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+BelongsToSamePersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+PDFTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/RevocationLocation.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/RevocationProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/__tests__/RevocationProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/Models/__tests__/ValidationConditions+CertificateSelectionTests.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateFake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/MockDigitalCovidCertificateAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateFakeTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/SchemaValidationTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/Legacy/LegacyTests.swift
Labels: task

#4464 Feature/11890 cert revocation/12600 update UI 2
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateMapping.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateValidityState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4459 Implement sorting
  src/xcode/ENA/ENA/Source/Models/Profile/AntigenTestProfile.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewModel.swift
Labels: task

#4470 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4471 Remove CircleCI badge from README
  README.md
Labels: community, admin

#4467 Feature/11890 cert revocation/12580 check certificate
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateValidator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateRevocationEntries.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+Mock.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/Extensions/HealthCertificateService+Inits.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/Fakes/HealthCertificateValidatorFake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateValidatorTests.swift
Labels: task

#4469 Feature/12868 pre fill name on consent screen
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyMemberConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyMemberConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyNameTextFieldCell.swift
Labels: task

#4468 Feature/12372 family members rat profile/12801 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/__tests__/CreateAntigenTestProfileViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/__tests__/AntigenTestProfileOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/AntigenTestPersonProfileCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/__tests__/AddAntigenTestProfileCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/__tests__/AntigenTestPersonProfileCellModelTests.swift
Labels: task

#4476 Bump to next Version 2.22.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4478 fix ui textfield glitch
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
Labels: bug

#4483 added environment launchargument
  src/xcode/ENA/ENA/Source/Environment/Environments.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: feature

#4482 Feature/11890 cert revocation/12883 unit tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/__tests__/MockRevocationProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/__tests__/RevocationProviderTests.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task

#4479 Fix/12604 lazy loading ccl service
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/CCLConfigurationResource.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceBoosterNotificationRulesTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceInvalidationRulesTests.swift
Labels: bug

#4480 Text changes for Schnelltest-Profil
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4484 Change word Info
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4486 Bump to next Version 2.22.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4489 Changed ExposureSubmission_Profile_ProfileTile_Title to plural form
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4481 update description of the expired certificate
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
Labels: task

#4487 Fix/12943 button weiter jumps back to ihre testverwaltung
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4491 Wrong text in navigation element to data privacy
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4492 Fix/12930 family tests multiple layout issues
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/__tests__/FamilyMemberCoronaTestCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/__tests__/FamilyMemberCoronaTestsViewModelTest.swift
Labels: bug

#4490 Feature/10307 risk calculation http client/10308 request available days
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/AvailableDays.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/AvailableDaysResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/__tests__/AvailableDaysResourceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: chore, task
