Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-06, with the labels that each got.

#4603 Fix/13205 check reissuance identifier
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4594 Fix/12215 app information faq link twice
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITests_02_AppInformation.swift
Labels: bug, chore

#4606 fixing various issues on different screens related to status bar
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+StatusBar.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/CovPassCheckInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/InformationScreen/ValidationInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Info/QRScannerInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/FirstConsent/FirstTicketValidationConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/Result/TicketValidationResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/TicketValidation/SecondConsent/SecondTicketValidationConsentViewController.swift
Labels: bug

#4609 13285 info screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/__tests__/HealthCertificateExportCertificatesInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/Alias.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4611 13286 export functionality
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/__tests__/HealthCertificateExportCertificatesInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_RecoveryCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_VaccinationCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
Labels: task

#4616 Bump to next Version 2.24.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4615 13338 unit tests
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/__tests__/HealthCertificateExportCertificatesInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
Labels: task

#4619 Task/13242/13371 miscellaneous
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4624 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4622 Story/13242 export all certificates pdf format
  .github/workflows/PullRequest.yml
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Extensions/NotificationName.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/__tests__/HealthCertificateExportCertificatesInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFGenerationInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_RecoveryCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_VaccinationCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/Alias.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/TooltipViewController.swift
  src/xcode/ENA/ENA/Source/Views/TooltipViewModel.swift
  src/xcode/ENA/ENA/Source/Views/__tests__/TooltipViewModelTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/Validation/ENAUITests_14_ValidateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: alternative approaches, feature

#4628 13403 Remove expiration details text
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateExpirationDateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4632 Bump to next version 2.24.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4634 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-issue

#4636 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4637 Bump to next version 2.24.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4639 Fix/9404 transparent status bar
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/Contagion/ContagionInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/HygieneRules/HygieneRulesInfoViewController.swift
Labels: bug

#4640 Fix/13431 13443 various button icons
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/icon-smartphone-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Smartphone.imageset/phone_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/certificate_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Certificates_04.imageset/certificate_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Info.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Info.imageset/i_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Info.imageset/i_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Printer.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Printer.imageset/icon_print.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Printer.imageset/printer_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Printer.imageset/printer_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/export_dark mode.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/export_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/export_light mode.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Share.imageset/export_light.pdf
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#4627 Checking Pipeline with 13.4.1
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/fastlane/Fastfile
Labels: chore

#4641 Fix/9680 Update UI to match the Design
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
Labels: bug
