Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-03, with the labels that each got.

#4269 Story/12045 feature switch changes - 11995 text changes based on feature switch
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/OverviewLabelTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeCCLService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/AppFeatures/AppFeatureProviding.swift
Labels: feature

#4263 Task/12010 refactor the getDCCScenarios intro a seperate helper
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLScenariosHelper.swift
Labels: task

#4271 Adapt privacy policy text changes
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4272 Story/11620 adjust info screen for release 2.19
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLScenariosHelper.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4270 Feature/11999 add link to accessability document
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icons_safari_link.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/icons_safari_link.imageset/icons_safari_link.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationDynamicAction.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppInformation/ENAUITests_02_AppInformation.swift
Labels: feature

#4275 Compare base45 instead of identifier.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4273 Feature/11997 inform user about regrouping
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMTextFieldCellViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DMTextFieldTableViewCell.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHealthCertificateMigration/DMHealthCertificateMigrationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHealthCertificateMigration/DMHealthCertificateMigrationViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#4277 Added missing fullstop
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4279 Downgrade OpenCombine
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: bug

#4278 Fix test_HealthCertificate_FederalState_Flow()
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: tests

#4283 Bump to next Version 2.19.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4285 Bump to next Version 2.19.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4284 Show correct error messages and remove repeat button
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceError.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4286 Protocol Buffer update for release 2.20.x at Thu Mar 3 10:36:25 UTC 2022
  proto/resources/internal/v2/corona_test_parameters.proto
  proto/resources/internal/v2/presence_tracing_parameters.proto
  proto/resources/internal/v2/risk_calculation_parameters.proto
Labels: admin

#4282 Feature/11911 merge configurations
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/CCLConfigurationReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/CCLConfigurationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/CCLConfigurationResourceTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
Labels: task

#4238 Added quick actions for qr code scanner and certificates
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4289 Feature/update appconfig
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/AppConfig/default_app_config_2200
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfigurationMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/AppConfiguration+FeaturesTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CacheAppConfigMockTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/default_app_config_270
Labels: task

#4290 Compile protos.
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: chore

#4288 Fix/12054 handle test type specific results
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestType.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestResult.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/TestResultTests.swift
  src/xcode/ENA/ENAUITests/Utils/UITestingParameters.swift
Labels: bug

#4291 Test the date formatters.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetAdmissionCheckScenariosInputTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetWalletInfoInputTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/SystemTimeTests.swift
Labels: bug

#4292 Changes to privacy policy texts
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4294 Bump to next Version 2.19.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4297 Fix/flaky date tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetAdmissionCheckScenariosInputTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetWalletInfoInputTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/SystemTimeTests.swift
Labels: bug

#4298 Feature/xxx add logging for reissuance error handling
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/__tests__/DCCReissuanceResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocument/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentValidationDecorator/ServiceIdentityDocumentValidationDecoratorResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/TeleTanResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationAccessToken/TicketValidationAccessTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationResult/TicketValidationResultTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountries/ValidationOnboardedCountriesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
Labels: task

#4302 Addition to "Überblick" > "Infektionsrisiko"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4300 Feature/performance optimization
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__tests__/RecycleBinViewModelTest.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: chore

#4301 Chore/logs and debug menu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBackendConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMLogging/LogDataItem.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/EvaluateTrust/DefaultTrustEvaluation.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/URLSessionDelegates/CoronaWarnSessionTaskDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Workers/Logging/Logging.swift
Labels: chore

#4313 Bump to next Version 2.19.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4312 Fix/dont scale segmented controls
  src/xcode/ENA/ENA/Source/Extensions/ENAFont.swift
  src/xcode/ENA/ENA/Source/Extensions/UIFont+DynamicType.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Views/DiarySegmentedControl.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug

#4311 Feature/11929 three certificates on overview
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
Labels: feature

#4305 add screenshots for reissuance
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_20_CertificateReissuance.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: feature, task

#4308 Fix alignment on risk card
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeImageItemView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeImageItemViewModel.swift
Labels: bug

#4309 Read lastSelectedScenarioIdentifier from store on setup
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#4317 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4316 Fix the but using the isNew flag
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4306 Feature/add loading screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/LoadingScreen/LoadingScreenViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/LoadingScreen/LoadingScreenViewController.xib
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/ValidationStateServiceTests.swift
Labels: chore

#4315 Chore/fix warnings zip foundation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/SAPDownloadedPackageTests.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/Archive+CBOR.swift
  src/xcode/ENA/ENATests/Helper/SAPDownloadedPackage+Helpers.swift
Labels: chore

#4314 Story/11827 changes recovery certificates details
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/RecycleBinItemCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/__tests__/RecycleBinItemCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/RecoveryEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4310 Task/12149 unit and UI tests for g status update
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4325 Add default for appconfig value.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/Extensions/RiskCalculationParameters+Defaults.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: task

#4326 Feature/10751 risk calculation max days/12123 change text onboarding
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Models/Onboarding/OnboardingInfo.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/__tests__/OnboardingInfoViewControllerTests.swift
Labels: task

#4319 feature/12101-make-some-cell-parts-not-clickable
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/ContactJournal/ENAUITests_07_ContactJournalUITests.swift
Labels: task

#4324 use maxEncounterAgeInDays in alert
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/Extentions/RiskCalculationParameters+Defaults.swift
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4327 Trigger CircleCI - MDC tests
  src/xcode/fastlane/Fastfile
Labels: admin

#4330 Story/12083 adjust info screen for release 2.20
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4295 Add filter for maxCheckInAgeInDays and tests.
  src/xcode/ENA/ENA/Source/Services/Event Registration/CheckinRiskCalculation/CheckinRiskCalculation.swift
  src/xcode/ENA/ENA/Source/Services/Event Registration/__tests__/CheckinRiskCalculationTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: task

#4320 Feature/12100 notification if already showing increased risk
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Backend/Extentions/RiskCalculationParameters+Defaults.swift
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01c_HighExposureAlert.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: task

#4331 Feature/11605 show red risk card on positive test
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Test Result Metadata/__tests__/TestResultMetadataTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/MockCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/DeadmanNotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/ENFRiskCalculationResult+Fake.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Calculation/__tests__/Models/RiskCalculationResultTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderError13Tests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#4321 RapidPCR Pending without DGC shows wrong details in testresult
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/PCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/PCRTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/RecycleBin.swift
Labels: bug

#4336 Feature/12245 suppress alert
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
Labels: task

#4335 Fix/ 12195 certificate marked as new
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
Labels: bug

#4332 Add maxEncounterAgeInDays to days since install screen.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DaysSinceInstallCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DaysSinceInstallTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
  src/xcode/ENA/ENA/Source/Utils/UITableView+Utils.swift
Labels: task

#4338 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4339 Bump to next Version 2.19.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4340 Bump to next version 2.20.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4329 Add maxEncounterAgeInDays to info screen.
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/RiskLegendViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/RiskLegend/__tests__/RiskLegendeTest.swift
Labels: task

#4341 Fix failing test_screenshot_local_statistics_card()
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
Labels: screenshots

#4293 Feature/12102 implement logic for g status change
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: feature

#4343 Improve text box sizes in pdf generation to fit more text
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/HealthCertificate+PDF.swift
Labels: bug

#4345 Bump to next Version 2.20.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4344 delay reloadData to fix overscrolling
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#4323 Fix/7954 create test journal entry after the user sees the result
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/MockCoronaTestService.swift
Labels: bug

#4346 Update language and service hours of technical hotline
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4350 Migrate missing content hugging and compression resistance priorities
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.swift
Labels: bug

#4353 Use configurable amount of days for "risk status lowered" alert
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#4362 fix failing test
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4355 Feature/12246 delta enf logic/12347 mark packages as checked for exposure
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/AppleFilesWriter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderError13Tests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: chore, task

#4363 Extend query to set bin and signature empty.
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V3/DownloadedPackagesSQLLiteStoreV3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
Labels: task

#4361 Feature/12246 delta enf logic/12337 sql update
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/Migrations/Migration2To3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V3/DownloadedPackagesSQLLiteStoreV3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V3/DownloadedPackagesStoreV3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/DownloadedPackagesStoreErrorStub.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/DownloadedPackagesSQLLiteStoreTests.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Migration/Migration2To3Tests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/AppleFilesWriter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionExecutorTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderError13Tests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: task

#4366 Bump to next Version 2.20.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4369 Bump to next Version 2.21.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4368 Bump to next Version 2.19.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4364 wait for the screen to appear before tapping
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4370 Text change "Neue Funktionen"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4352 Fix/12364 contact journal glitches
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/UIStackView+Background.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#4373 chore: update default CCL configuration to 1.2
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
Labels: chore

#4374 update default appconfig
  src/xcode/ENA/ENA/Resources/AppConfig/default_app_config_2200
Labels: chore

#4372 Set homestate to non nil value for DiaryCoordinator.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/DiaryCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/__tests__/DiaryOverviewViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeStateFake.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvidingFake.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProviding+Fake.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/StatisticsProvidingFake.swift
Labels: bug

#4375 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.stringsdict
Labels: text-change

#4376 Add support for ukrainian language
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: feature

#4378 Fix/11572 error alert during key preauthorization
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4380 Set content compression resistance.
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
Labels: bug

#4381 Move legal text to legal.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4379 Feature/12219 testprocess family members/12340 create family member consent screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Family.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Family.imageset/Group 625350.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icon_Family.imageset/Group 625351.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Family_Test_Consent.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Family_Test_Consent.imageset/family-test-04 1.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Family_Test_Consent.imageset/family-test-04 2.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyMemberConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyMemberConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyNameTextFieldCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/__tests__/FamilyMemberConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4382 12423 test admission state changes fails
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/CreateHealthCertificateUITests.xctestplan
Labels: bug

#4359 Feature/12350 update old logic to check the blocklist
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesResource.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetWalletInfoInputTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: task

#4358 Feature/12345 download and cache invalidation rules from cdn
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesResource.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceInvalidationRulesTests.swift
Labels: task

#4387 Fix/12433 is admission state changed false on update
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4388 Bump to next Version 2.20.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4386 Story/12218 support revocation of certificates from an issuer based on invalidation rules
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesResource.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceInvalidationRulesTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetWalletInfoInputTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: feature

#4390 Fix #2417 by removing "Shows touch on highlight" property
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.xib
Labels: bug, community

#4395 Story/12468 adapt privacy notice release 2.21
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4396 Story/12247 adjust info screen release 2.21
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4392 Compare the age in days.
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#4397 moved text to leagal and localized them
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#4398 DM: Add Button to crash the app to test crash reporting.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMCrashAppViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
Labels: chore

#4393 Feature/12219 testprocess family members/12342 changes test result
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultFamilyMemberViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultModeling.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestOwnerSelection/ExposureSubmissionTestOwnerSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberPCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/MockFamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.swift
Labels: task

#4399 Fix/reissue url
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Environment/Environments.default.json
Labels: bug

#4400 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.stringsdict
Labels: text-change

#4383 fix saving tests into contact diary
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/MockCoronaTestService.swift
Labels: bug

#4403 Bump major CCL version
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/Locator+CCLConfiguration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/Locator+CCLConfigurationTest.swift
Labels: feature

#4404 without header it's not working correctly
  src/xcode/fastlane/Fastfile
Labels: admin

#4405 Bump to next Version 2.21.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin
