Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-01, with the labels that each got.

#4016 Fix privacy policy english texts
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: bug, text-change

#4024 Bump copyright year in README.md
  README.md
Labels: community

#4012 Fix layout in no-g rule
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
Labels: bug

#4009 Feature/11084 log app version
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Client Metadata/ClientMetadata.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#4021 Update "ExposureDetection_Guide_Title" text (Addresses corona-warn-app/cwa-wishlist/#738)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community

#4023 Replace information in LICENSE with placeholder
  LICENSE
  LICENSES/Apache-2.0.txt
Labels: community

#4026 Improve 2G+ with RAT text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
Labels: community

#4020 Recycle Bin - rescan a test does not open the detail view
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: bug

#4033 Datenschutz called by certificate validation has swipe down functionality
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationCoordinator.swift
Labels: bug

#4034 only use downscaling if image width is bigger that screen size
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewHeadlineWithImageCell.swift
Labels: bug

#4032 display issues after deleting the rapid test profile
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#4030 Text to small in statistics info screen
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
Labels: bug

#4031 Fix/9227 event check in date of an event should not appear in the contact journal entry
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventCheckoutServiceTests.swift
Labels: bug

#4029 Some illustrations don't stretch completely to the borders
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.xib
Labels: bug

#4036 Fix/8482 illustrations dont stretch to the borders
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.xib
Labels: bug

#4027 Fix/5328 settings datenspende pic missing text
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende.imageset/Illustration_Datenspendedatenspende.pdf
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/SettingsDataDonationViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/SettingsCoordinator.swift
Labels: bug

#4037 added missing text alignment
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
Labels: bug

#4038 Bump to next Version 2.16.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4017 Handling error on key packages download
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/__tests__/HomeRiskCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/MockRiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#4039 Typos corrected
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
Labels: text-change

#4045 Read key and value as one text in voice over mode
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/Cell/HealthCertificateKeyValueTextCell.swift
Labels: bug

#4046 fix/10429-formatting-issue
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug

#4043 Show number of persons in dev menu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMStoreViewController.swift
Labels: feature

#4044 Fix/8567 performance improvement
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/Mocks/MockUserNotificationCenter.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4041 Show QR code in pdf generation in correct orientation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/CGPDFDocument+EmbedImage.swift
Labels: bug

#4048 story/10882-censor-token-ticket-validation
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AccessToken/TicketValidationAccessTokenProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
Labels: feature

#4049 Feature/10767 social media link to coronawarn.app page
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/More/more_social_media.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/More/more_social_media.imageset/Group 625217social.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/More/more_social_media.imageset/socialmedia_dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/More/HomeMoreItem.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: feature

#4042 Story/10883 text changes positive test
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/cross_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - Red Plus.imageset/cross_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSuccessViewControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeImageItemView.xib
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: feature

#4053 Story/11162 http caching part1/11219 cbor receive resource
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/CBORReceiveResource.swift
Labels: task

#4054 Adjust working hours TAN hotline
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4050 Fix/7265 app shows alert
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
Labels: bug

#4061 Bump to next Version 2.16.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4055 Story/11151 adjust info screen text
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4063 Quarantine 14 --> 10 days
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4056 Feature/10399 get test results port
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetTestResultTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/Locators/Send/TestResultDownload.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TestResultResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TestResultsResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/TestResultModel+Fake.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/TestResultModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Send/RegistrationTokenSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestResultOperation.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
Labels: feature

#4064 Fix flaky tests and warnings
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/Dark_fullyVaccination.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/FullyVaccinated.imageset/Light_fullyVaccinated.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Booster_Vaccination.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Booster_Vaccination.imageset/Dark_boosterVaccination.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Booster_Vaccination.imageset/Light_boosterVaccination.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_booster_vaccination.imageset/Light_booster.pdf
  src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
Labels: bug

#4051 fix/11211 Revert headline removal
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewController.swift
  src/xcode/ENA/ENAUITests/DataDonation/ENAUITests_05_DataDonation.swift
Labels: bug

#4066 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4065 fix/9819 remove first instruction
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionQRInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionQRInfoModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, text-change

#4067 Story/11162 http caching part1/archive for testing
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/__tests__/Archive+CBOR.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/CBORReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/ProtobufReceiveResource.swift
Labels: task

#4068 Story/11162 http caching part1/detailled errors
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Extensions/Dictionary+Headers.swift
  src/xcode/ENA/ENA/Source/Extensions/HTTPURLResponse+Header.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service.swift
Labels: task

#4047 fix/Crash getAppConfig
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/CachingHTTPClientMock.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/CachedAppConfigurationTests.swift
Labels: bug

#4071 Add image trait to images inside the DynamicTableViewHeader
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewHeader.swift
Labels: bug, accessibility

#4073 Update flash a11y to reflect flash state on first try
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
Labels: bug, accessibility

#4075 A11y: Add button trait to header labels in HealthCertifiedPersonTableViewCell
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug, accessibility

#4074 Fix A11y order in HealthCertificateQRCodeCell
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
Labels: bug, accessibility

#4070 Data donation - update the artwork
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende_heart.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende_heart.imageset/Frame 1878g.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_Datenspendedatenspende_heart.imageset/Illustration_Datenspende_darkg black.png
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
Labels: bug

#4022 Error Submitting exposure keys
  src/xcode/ENA/ENA/Source/Client/HTTP Client/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionError.swift
Labels: bug

#4077 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4080 Fix/11283 rat personal data in log 2.16
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
Labels: bug

#4062 Fix/11112 notification opens cwa home panel instead of test result screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route+Equatable.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: bug

#4082 add some logs
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMErrorLogSharing/DMErrorLogSharingViewModel.swift
Labels: bug

#4078 Story/10125 recycle bin show deletion date
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/RecycleBinItemCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/RecycleBinItemTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/RecycleBinItemTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/Cells/__tests__/RecycleBinItemCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/RecycleBin/RecycleBin.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4083 Bump to next version 2.16.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4084 Fix/ Upgrade to SwiftCBOR to 0.4.4
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: bug

#4081 Fix/11282 recover certificates after failed decoding
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateDecodingContainer.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4085 fix/ Upgrade swift pancakes.
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug

#4087 Story/11162 http caching part1/11163 validation onboarded countries
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetDccRules.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ValidationOnboardedCountries.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/CBORReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountriesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/ValidationOnboardedCountriesResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/ValidationOnboardedCountriesModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/HealthCertificateValidationServiceValidationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/Model/HealthCertificateValidationOnboardedCountriesCache.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/Model/HealthCertificateValidationOnboardedCountriesError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/__tests__/HealthCertificateValidationOnboardedCountriesProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/__tests__/MockHealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Fakes.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/RuleValidation/OnboardedCountriesAccessTests.swift
Labels: task

#4089 fix/8702 static data for statistics
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/__tests__/sample_stats/stats.bin
Labels: tests, screenshots

#4095 Only allow iat and exp to be timestamps, not other date formats
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/DigitalCovidCertificateAccess.swift
Labels: bug

#4086 Support new booster notation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/CWATestCase+HealthCertificateConvenience.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
Labels: feature

#4100 Bump to next Version 2.17.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4103 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4101 Fix/correct vaccination state and image
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4094 Certificate Travel Infos wrong text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4104 Bump to next Version 2.17.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4107 Use custom uncompression logic.
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/Utils/Data+Compression.swift
Labels: bug

#4108 censor missing values
  src/xcode/ENA/ENA/Source/Services/TicketValidation/ValidationDecorator/TicketValidationDecoratorIdentityDocumentProcessor.swift
Labels: bug

#4109 Bump to next Version 2.17.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4110 Feature/11471 allow sync access to cache o resource
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/CachedRestServiceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/__tests__/RestServiceProviderTests.swift
Labels: task

#4111 Fix contact diary info 14 days (Addresses cwa-documentation issue 527) (COMMUNITY)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: community, mirrored-to-jira, text-change, contact-journal

#4105 Feature/11355 business configuration dcc prioritization/11466 faq anchor url
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Workers/LinkHelper.swift
  src/xcode/ENA/ENA/Source/Workers/__tests__/LinkHelperTests.swift
Labels: task

#4117 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4121 Adjustment of iOS text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4097 bug/9078-missing-test-results-in-journal-export
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/__tests__/ContactDiaryStoreTests.swift
Labels: bug

#4123 Fix/11548 crash background threads
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidationOnboardedCountries/HealthCertificateValidationOnboardedCountriesProvider.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
Labels: bug

#4124 Bump to next Version 2.17.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4122 Feature/integrate funktions package
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: task

#4126 Certificate Travel Infos - wrong text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4125 Feature/11458 create interfaces
  licenses.json
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController+LegalModel.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: task

#4129 Feature/11458 create models
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLConfiguration.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletCertificate.swift
Labels: task

#4132 Bump to next Version 2.17.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4131 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4118 Feature/11464 information about caching or not
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/CBORReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/StringReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ReceiveResources/WithHeaderReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationAccessTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TicketValidationResultTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationAccessTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/TicketValidationResultTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/ModelWithMetadata.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/ModelWithHeaders.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/TicketValidationAccessTokenReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/ValidationOnboardedCountriesModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Models/Receive/ValidationRulesModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/AccessToken/TicketValidationAccessTokenProcessor.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/TicketValidation.swift
  src/xcode/ENA/ENA/Source/Services/TicketValidation/__tests__/TicketValidationAccessTokenProcessorTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Fakes.swift
Labels: task

#4133 Add cbor access to CCLConfiguration.
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration+Fake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfigurationAccess.swift
  src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CommonCovidLogic/CCLConfigurationAccessTests.swift
Labels: task

#4137 Add layer for correct decoding
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration+Fake.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration.swift
Labels: task

#4138 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4142 Bump to next Version 2.17.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4130 Feature/11468 update caching
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountries/__tests__/ValidationOnboardedCountriesResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/GenericModels/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Types/CacheUsePolicy.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/CachePolicyTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/CachedRestServiceTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/CacheData.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureCache.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/CacheData+Fake.swift
  src/xcode/ENA/ENA/Source/Workers/Store/__tests__/CacheDataTests.swift
Labels: task

#4141 Feature/11455 wallet info model 2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Certificates/VaccinationCertificate_FullyVaccinated_Icon.imageset/VaccinationCertificate_FullyVaccinated_Icon.pdf
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationHint/VaccinationHintCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/VaccinationHintCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+AdmissionState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+Fallback.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray+MostRelevant.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/VaccinationEntry+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPersonAdmissionState.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/VaccinationProductType.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/CWATestCase+HealthCertificateConvenience.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+AdmissionStateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+FallbackTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+MostRelevantTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonBoosterTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonKnownVaccinationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonOtherVaccinationProductTypeTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: task
