Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-09, with the labels that each got.

#4753 Feature/13820 implement mask section on certificate details
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Badge_mask.imageset/Badge_mask_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Badge_mask.imageset/Badge_mask_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Badge_mask.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Badge_nomask.imageset/Badge_nomask_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Badge_nomask.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/ENAColor.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/MaskStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4758 Feature/13817 change color scheme
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: feature

#4762 Update privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Labels: text-change

#4760 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4761 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#4763 Story/13810 Single export non-DE certificates
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: feature

#4765 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.stringsdict
Labels: text-change

#4759 Feature/10317 port request (authorize otp els)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/RestServiceAuthorizationOTPElsTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForELS/AuthorizeOtpEls.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForELS/OTPAuthorizationForELSResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForELS/OTPResponsePropertiesReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/JSONReceiveResource.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Survey/SurveyURLServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
Labels: feature

#4764 Feature/13818 13819 Add UI test & screenshots
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: feature

#4767 Fix/13891 Convert maskState to optional for backward compatibility
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: bug

#4769 Bump to next version 2.27.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4771 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4770 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4773 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4772 Fix/13883 mask admission states design requirements
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug

#4775 Bump to next version 2.27.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4768 Feature/13819 update screenshot tests
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: feature

#4774 Fix build for Xcode14
  src/xcode/ENA/ENA/Source/Scenes/App/AppNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/App/AppOnboardingNavigationController.swift
Labels: chore

#4777 Single Export: Removing extra text from data privacy
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4778 fix/13883 Hide empty badges
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug

#4781 fix/13908 green gradient direction
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: bug

#4779 fix/13923 No mask feature by default on version update
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#4784 fix/13823 pdf not saving on 12.5
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
Labels: bug

#4785 Bump to next version
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4783 fix/13920 false screen color when checking mask rules for recovery certificate
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4787 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4789 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4788 Fix/13952: Update gradient type when changing state government rules (BW->BY)
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#4791 Fix/13966 Adding missing identifiers statistics tiles
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: bug

#4792 Fix/13970: Certificates - mask symbol when you choose "Berlin" or "Keine Auswahl"
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/MaskState/MaskStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/MaskStateCellModelTests.swift
Labels: bug

#4793 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4790 Fix/13772 Data Privacy and Terms Screen: Bottom text is cut off.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/usage.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/usage.html
Labels: bug

#4796 Story/13963 Replace non-DE certificate template
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_RecoveryCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_TestCertificateTemplate_v4.1.pdf
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificate+PDF/Templates/NonDE_VaccinationCertificateTemplate_v4.1.pdf
Labels: feature

#4795 Fix/3428 Remove non public repo link
  src/xcode/ENA/ENA/Source/Models/SymptomsOnset.swift
Labels: bug

#4797 Fix/10926 data privacy and terms screen - issue with format of some links
  src/xcode/ENA/ENA/Resources/Localization/style.css
Labels: bug

#4799 fix/13969 default text scenario selection
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: bug

#4800 fix/12930 broken constraints and the red dot layout issue
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestTableViewCell.xib
Labels: bug

#4802 Fix/13781: Infinite zoom out when previewing certificates using "Export all certificates"
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
Labels: bug

#4804 Chore/add uniqueName for MDC upload
  src/xcode/fastlane/Fastfile
Labels: chore

#4803 Fix/13990 QR Codes processed without opening QR Code Scanner
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
Labels: bug

#4801 Fix/13907: Mask Badge in Person Overview should be aligned with Toggle
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
Labels: bug

#4805 Fix/14009 Adding accessibility identifiers for local statistics
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: bug

#4798 Fix/13818 & 13819 mask state UI and screenshot tests
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
  src/xcode/ENA/TestPlans/UITests.xctestplan
Labels: bug

#4807 Fix/mdc upload
  src/xcode/fastlane/Fastfile
Labels: bug

#4808 QRCode screen is blocked
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
Labels: bug
