Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-11, with the labels that each got.

#4869 Fix/9910 Tab bar gets invisible in the contact diary
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#4854 Fix/10498 Show New Functions Screen footernote only with delta onboarding
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/__tests__/DeltaOnboardingNewVersionFeaturesControllerTests.swift
Labels: bug

#4872 Fix/14087 issues statistics info screen
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
Labels: text-change

#4868 Fix/7429 Fehlerberichte ID History: IDs are ordered with oldest entry on top and newest entry to focus on at the bottom
  src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/ErrorReportHistory/ErrorReportHistoryViewModel.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
Labels: bug

#4874 Fix/14283 wrong font of "Ihr Einverständnis" on Check-in-Information
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Info/CheckinsInfoScreenViewModel.swift
Labels: bug

#4870 Fix/14215 Certificate Details - "back" disappears if manual swipe is interrupted
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
Labels: bug

#4876 Fix/8455 date picker keyboard issues
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/EditCheckInTime/Cells/CheckInDatePickerCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/DateTimeSelection/Cells/OnBehalfDateSelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/ValidationDateSelectionCell.swift
Labels: bug

#4880 Protocol Buffer update for release 2.29.x at Tue Nov 8 11:54:17 UTC 2022
  proto/resources/internal/submission_payload.proto
Labels: admin

#4877 Task/14276 Adapt manage your tests screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Anruf.imageset/Illu_Submission_Anruf-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_Anruf.imageset/Illu_Submission_Anruf.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Submission_PositiveSelfTest_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_PositiveSelfTest.imageset/Illu_Submission_PositiveSelfTest_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Illu_Submission_SRS_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_SRS.imageset/Illu_Submission_SRS_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_TAN.imageset/Illu_Submission_TAN-Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Submission_TAN.imageset/Illu_Submission_TAN.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionIntroViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/AppDelegate/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
Labels: task

#4878 Task/14281 Adapt thank you screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/icons_contactjournal_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ContactJournal.imageset/icons_contactjournal_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Risikoermittlung/Contents.json
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSuccessViewControllerTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4875 Task/14274 Adapt manage your tests tile
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_WarningAfterSelfTest.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_WarningAfterSelfTest.imageset/Illu_WarningAfterSelfTest_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_WarningAfterSelfTest.imageset/Illu_WarningAfterSelfTest_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Extensions/UIView+Utils.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/__tests__/HomeTestRegistrationCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/GradientView.swift
Labels: task

#4879 Task/14277 Add new consent screen and os confirmation
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-No-Certificate-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-No-Certificate-icon.imageset/SRS-No-Certificate-icon-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-No-Certificate-icon.imageset/SRS-No-Certificate-icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Positive-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Positive-icon.imageset/SRS-Positive-icon-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Positive-icon.imageset/SRS-Positive-icon.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Warn-Others-icon.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Warn-Others-icon.imageset/SRS-Warn-Others-icon-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/SRS-Warn-Others-icon.imageset/SRS-Warn-Others-icon.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSFlowType.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/__tests__/SRSConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCardView/HomeLinkCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4881 Task/14306 Adapt test result screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: task

#4883 Task/14278 Exposure Submission: Test Type Selection
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/SRSTestTypeSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_LinkCard+Mock.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4885 Protocol Buffer update for release 2.29.x at Fri Nov 11 12:45:23 UTC 2022
  proto/resources/internal/ppdd/ppac_android.proto
  proto/resources/internal/ppdd/srs_otp_request_android.proto
Labels: admin

#4884 Task/14278 Make Unit Tests buildable again
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/SRSTestTypeSelectionViewModelTests.swift
Labels: task

#4887 Task/14295 wiring up SRS flow
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/SubmissionTestType.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4892 Task/Removing back button from symptoms screens
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
Labels: task

#4890 Task/14347 Add SRS error codes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Survey/SurveyURLProvider.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSError.swift
Labels: task

#4896 Task/14350 adapt new changes
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/__tests__/SRSConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSDataProcessingInfo/SRSDataProcessingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSDataProcessingInfo/SRSDataProcessingInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionSuccessViewControllerTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/SRSTestTypeSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4897 fix/6441 disabled button when edit & delete the event cell
  src/xcode/ENA/ENA/Source/Scenes/Events/Cells/EventTableViewCell.swift
Labels: bug

#4898 Story/adjust info screen release 3.0
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/I_NeueFunktionen_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/I_NeueFunktionen_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/new_feature_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/new_feature_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4899 Fix/crash on other languages
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4900 Fixing important SRS issues
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/SRSKeySubmissionResource.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: chore

#4901 Fix small font size in SRS confirmation details
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSDataProcessingInfo/SRSDataProcessingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSDataProcessingInfo/SRSDataProcessingInfoViewModel.swift
Labels: bug

#4895 Task/14315 error handling
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Developer Menu/DMSrsPrechecks/DMSrsPrechecksViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMSrsPrechecks/DMSrsPrechecksViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Extensions/UIViewController+Helpers.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionIntroViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestTypeSelection/SRSTestTypeSelectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionIntroViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/SRSTestTypeSelectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/ErrorCodeProviding.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/PPACError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSErrorAlert.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSErrorAlertProviding.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/SRSService/MockSrsService.swift
  src/xcode/ENA/ENA/Source/Services/SRSService/SRSService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/Alias.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#4903 Fix/Double push SRS Consent Screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSPrechecksViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSPrechecksViewModel.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: bug

#4905 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4904 Fix/SRS submitting works own SRS model type (with string)
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForELS/OTPAuthorizationForELSResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForELS/OTPForELSResponsePropertiesReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/OTPAuthorizationForSRSResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/OTPForSRSResponsePropertiesReceiveModel.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OTP/OTPService.swift
  src/xcode/ENA/ENA/Source/Services/OTP/__tests__/OTPServiceTests.swift
Labels: bug
