Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-08, with the labels that each got.

#4705 ci: change trigger for test automation from CircleCI to GitHub Actions
  .github/workflows/ReleaseCandidate.yml
  src/xcode/fastlane/Fastfile
Labels: chore

#4704 Feature/support dcc schema 1.3.2
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Model/DigitalCovidCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CertificateAccess/Ressources/CertificateSchema.json
Labels: feature

#4709 Bump to next version 2.26.0
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4702 Fix/13466 Nachweis Funktion
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultFamilyMemberViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultFamilyMemberViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4708 Add AccessibilityIdentifiers for test automation
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/cells/AddAntigenTestProfileCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/Cells/AddCheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/CheckinsOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfScanQRCodeCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfTraceLocationSelectionEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/Cells/AddTraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/TraceLocationsOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSuccessViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TANInputViewController/Cells/TANInputCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Custom/ExposureSubmissionDynamicCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/ChangeAdmissionScenario/ChangeAdmissionScenarionCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeImageItemViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/RecycleBinEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCelling.swift
  src/xcode/ENA/ENA/Source/Views/EmptyStateView/EmptyStateView.swift
  src/xcode/ENA/ENA/Source/Views/EmptyStateView/EmptyStateViewModel.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/RecycleBin/ENAUITests_18_RecycleBin.swift
Labels: bug

#4707 Adjust info screen for release 2.26
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4706 fix/10444 Button bounce on screen "others have been warned"
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
Labels: bug

#4700 fix/12462 trait button missing on certificates news
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/BoosterNotification/BoosterNotificationTableViewCell.swift
Labels: bug

#4712 Update DCC Schema - Unit tests
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Name+ExtensionTests.swift
Labels: task

#4710 Fix/13704 cleanup old keypackages
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V3/DownloadedPackagesSQLLiteStoreV3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/V3/DownloadedPackagesStoreV3.swift
  src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/__tests__/Doubles/DownloadedPackagesStoreErrorStub.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
Labels: bug

#4713 Fix/13213 Update DCCWalletInfo in foreground
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#4714 fix/13349 family member functions - slower performance
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewController.swift
Labels: bug

#4717 Add accessibility label for the alert action
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug, chore

#4718 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4719 Fix/12781 diary spacing automatically added entries
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#4716 Update grouping logic to support the new rules
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+BelongsToSamePersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Resources/dcc-holder-comparison.json
Labels: bug

#4720 Fix/13122 Expired Certificates Consent and Confirmation screen 12.5
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceSucceeded/HealthCertificateReissuanceSucceededViewController.swift
Labels: bug

#4722 Fix/11116 remove info button icon | 9640 Wrong text in UQS-Warn Others
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4721 Fix/9868: "Datenspende" - display issues on the detailed information screen about data share
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewRoundedCell.swift
Labels: bug

#4723 Adjust automation trigger url
  src/xcode/fastlane/Fastfile
Labels: chore

#4725 Fix/13772: Data Privacy and Terms Screen: Bottom text is cut off
  src/xcode/ENA/ENA/Resources/Localization/style.css
Labels: bug

#4724 Fix/10926: Data privacy & Terms screen - issue with format of some links
  src/xcode/ENA/ENA/Resources/Localization/style.css
Labels: bug

#4727 Fix/5328 data donation title appears twice
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/__tests__/SettingsDataDonationViewModelTests.swift
Labels: bug

#4729 Fix/13775 refactoring warn others logic
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewController.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
Labels: chore

#4728 Feature/10318 refactor els submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitErrorLogFileTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/ELSSubmitReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/ELSSubmitResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/SubmitELS.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/Locator.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/Model/ELSError.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: feature

#4726 Fix/10070: Fix Xcode compiler warnings.
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/GenericModels/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewController.swift
Labels: bug

#4732 Bump to next version 2.26.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4731 fix/10429 Certificates tab formatting issue
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
Labels: bug

#4730 9765: Simulator: Choosing "fake" HC1/HC2 leads to invalid signature error
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
Labels: bug

#4735 Bump to next version 2.26.0.4
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4734 Fix/9906 settings notifications screen text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/__tests__/NotificationSettingsViewModelTests.swift
Labels: bug

#4737 fix/7193 Misleading error during no internet connection
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
Labels: bug

#4745 Bump to next version 2.26.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4744 Fix/13728: Fault Tolerance - delete a merging TC crashs the app
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
Labels: bug

#4741 Fix/12222 wrong badge count on status tab
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeBadgeWrapper.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#4739 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4738 Update Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.stringsdict
Labels: text-change

#4746 Fix/10458 restore tests from recycle bin error
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#4740 Fix/13799 contact diary location duration screenobject id issue for test automation
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: bug

#4750 Fix/13728: Merged certificates: delete the currently used certificate
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
Labels: bug

#4747 12781: Diary Spacing for entries in exposure history
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.xib
Labels: bug

#4755 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4757 Adjust info screen for release 2.27
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature
