Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-07, with the labels that each got.

#4652 Bump to next Version 2.24.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4654 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4649 13470: BSI: Cocoapods-Downloader version bump to 1.6.3
  src/xcode/Gemfile.lock
Labels: chore

#4647 12765 Exposure logging scrolls up automatically
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: bug

#4648 UI Issue on certificate screen when access from family tests
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
Labels: bug

#4645 12946: Reisegueltigkeit pruefen button disabled cell selection
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
Labels: bug

#4643 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4613 13342: COMMUNITY: Add new bullet point to info screen (Addresses cwa-wishlist issue 660)
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/CovPassCheckInformationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/CovPassCheckInformation/__tests__/CovPassCheckInformationViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: community, mirrored-to-jira

#4656 admin/bump to next version 2.25.0.1
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4655 Fix/13375 photo library access
  src/xcode/ENA/ENA/Resources/Info.plist
  src/xcode/ENA/ENA/Resources/Info_Debug.plist
  src/xcode/ENA/ENA/Resources/Info_Testflight.plist
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/InfoPlist.strings
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift
Labels: bug

#4657 9372: Remove Risk Level for text partial days since app installation
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
Labels: bug

#4661 9768: Avoid UI glitch by setup transparent navigation bar asynchronously
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Result/HealthCertificateValidationResultViewController.swift
Labels: bug

#4660 13179: Fast double tap should not push VC Risiko-Ermittlung twice.
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#4664 Adjust new features screen release 2.25
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4663 Fix/13476 delete exported certificates from temporary directory
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Extensions/FileManager+TemporaryDirectory.swift
  src/xcode/ENA/ENA/Source/Extensions/__tests__/FileManager+TemporaryDirectoryTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/PdfGeneration/HealthCertificatePDFVersionViewController.swift
Labels: bug

#4665 13609: Adapt texts and icons.
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Icons - ErhohtesRisiko Dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons - ErhohtesRisiko.imageset/Icons - ErhohtesRisiko Light.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Info/Contagion/ContagionInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/Info/ContagionInfoViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#4666 13620: Adapt STIKO-Cell to match design requirements
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewIconWithLinkTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
Labels: task

#4667 admin/bump to next version 2.25.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4669 13630: Revert bouncing bug fix changes
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: bug, task

#4662 Feature/10319 refactor ppa submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitAnalyticsDataTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAMostRecentData.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/PPA/PPASubmitResource.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: task

#4670 Story/10318 refactor ppa and els submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitAnalyticsDataTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAActualData/DMPPAActualDataViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAMostRecentData.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMPPAnalytics/DMPPAnalyticsViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/PPA/PPASubmitResource.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/Model/PPASError.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
Labels: feature

#4671 Bump to next version 2.25.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4673 Changes to fastfile to make adhoc distribution work
  .github/workflows/PullRequest.yml
  src/xcode/fastlane/Fastfile
Labels: chore

#4674 13617: Add accessibility identifier to the specific view element.
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/Cells/DiaryDayEntryTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Day/DiaryDayViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: bug

#4675 fix/13634 Recommended actions adjustments
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
Labels: bug, text-change

#4679 the heading on the screen "Ihr Einverständnis- Andere Warnen erteilt" is too small
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultConsentViewController.swift
Labels: bug

#4680 Fix/13637 wrong text risk change status
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#4685 Chore: update default DSC list (EXPOSUREAPP-13661)
  src/xcode/ENA/ENA/Source/Services/DSCList/Default/default_dsc_list.bin
Labels: chore

#4682 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4686 fix/13567 family member button bounces
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
Labels: bug

#4681 12766: Update EnState in ExposureNotificationSettingViewController
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionCoordinator.swift
Labels: bug

#4688 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4687 Fix/13609: Add Stiko-URL für BG, EN, PL, RO, TR Lang.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
Labels: bug

#4690 Fix/13640 UI glitch on soon expiring certificate screen
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
Labels: bug

#4693 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-issue

#4692 Fix/13669: Increased risk, Link for test locations is missing in polish language
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
Labels: bug

#4691 Fix/13462: Expired Certificates - "About to expire" needs to be removed on personal wallet on screen "Zertifikate"
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
Labels: bug

#4695 13467: Change `validityStateIsConsideredNewsworthy`
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: bug

#4696 fix/13686 pdf sorting issue
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateExportCertificatesInfoViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4697 PPA submission: Error API_TOKEN_ALREADY_ISSUED shown
  src/xcode/ENA/ENA/Source/HTTPClient/LocatorsNotYetUsed/SubmitPPA.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/PPA/PPASubmitResource.swift
Labels: bug

#4698 fix/9906 settings notifications screen wording wrong when notifications are turned off
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug
