Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-02, with the labels that each got.

#4147 Call evaluate on instance property.
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
Labels: task

#4153 Adjust Info Screen to announce new Release-Features for 2.18
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4156 Change term
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4159 Added fallback tests.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificateArray+FallbackTests.swift
Labels: task

#4148 Feature/11457 localized strings wallet info
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/DCCUIText.stringsdict
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/BoosterNotification/BoosterNotificationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationState/VaccinationStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/VaccinationStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCUITextTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/Models/TestCases.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/ccl-text-descriptor-test-cases.json
Labels: feature

#4146 Feature/11459 adapt certificates tab
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
Labels: task

#4158 Feature/11456 update ccl configuration and booster notification rules
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesReceiveModel.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestResultAvailable/__tests__/TestResultAvailableViewModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/BoosterNotification/BoosterNotificationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationState/VaccinationStateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/AdmissionStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/VaccinationStateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCUITextTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/DeadmanNotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/BoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/RulesDownloadService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/BoosterNotificationsServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeBoosterNotificationsService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeCCLService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration.swift
Labels: task

#4165 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4164 Attempt to fix flaky AddStatisticsButton test.
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/CustomDashedView.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
Labels: bug

#4168 Fix flaky date tests
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/GetWalletInfoInputTests.swift
Labels: bug

#4160 set the badge if the risk level changes regardless of the level
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeBadgeWrapper.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeBadgeWrapperTests.swift
Labels: bug

#4167 Removed title incl. accessibility identifiers
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, feature

#4166 Feature/11461 booster details screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_booster_details.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_booster_details.imageset/Illu_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illustration_booster_details.imageset/Illu_light.pdf
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/BoosterDetails/BoosterDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/BoosterDetails/BoosterDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/BoosterDetails/__tests__/BoosterDetailsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: task

#4171 Attempt to fix flaky test part 977
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENATests/Helper/XCUIElement+Utils.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
Labels: bug

#4175 Exclude DCCUIText.stringsdict from translations
  translation_v2.json
Labels: task

#4173 Fix scanning of tests and fake request
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/TeleTanResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/__tests__/TeleTanResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/__tests__/OnBehalfCheckinSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENATests/Helper/RestServiceProviderFactory.swift
Labels: bug

#4170 Fix/11625 fix test complete vaccination admission state()
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationState/VaccinationStateTableViewCell.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/TestPlans/CreateHealthCertificateUITests.xctestplan
Labels: task

#4178 Feature/11475 update wallet info
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/VaccinationState/VaccinationStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/TestPlans/AllTests.xctestplan
  src/xcode/ENA/TestPlans/CreateHealthCertificateUITests.xctestplan
  src/xcode/ENA/TestPlans/UnitTests.xctestplan
Labels: task

#4172 Feature/11687 extend UI test booster details
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/BoosterNotification/BoosterNotificationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4177 Feature/11702 configuration is updated all the time
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRules/DCCRulesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/GenericModels/MetaDataProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceBaseTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceBoosterNotificationRulesTests.swift
Labels: bug

#4184 Fix/11710 dev menu
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMCCLConfiguration/DMCCLConfigurationViewModel.swift
Labels: task

#4185 Update app links to support rapid pcr tests
  src/xcode/ENA/ENA/Resources/ENA.entitlements
  src/xcode/ENA/ENA/Resources/ENACommunity.entitlements
  src/xcode/ENA/ENA/Resources/ENATest.entitlements
Labels: task

#4186 Update fastlane
  src/xcode/Gemfile.lock
  src/xcode/fastlane/Pluginfile
Labels: admin

#4181 Rename TeleTan's and RegistrationToken's ReceiveModel and Locators
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/Locator+RegistrationToken.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/__tests__/RegistrationTokenResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/Locator+TeleTan.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/TeleTanReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/TeleTanResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/__tests__/TeleTanResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/__tests__/FakeRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/OnBehalfCheckinSubmission/__tests__/OnBehalfCheckinSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENATests/Helper/RestServiceProviderFactory.swift
Labels: chore

#4188 Request COVID-Certificate has wrong text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4189 Request COVID-Certificate has wrong text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Labels: text-change

#4179 Story/11608 fault tolerant name handling/11682 certificate person matching
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+BelongsToSamePersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Name+ExtensionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Resources/dcc-holder-comparison.json
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Resources/dcc-holder-name-components.json
  src/xcode/ENA/ENA/Source/Utils/Set+Utils.swift
Labels: task

#4187 Update Text for 116117 info telephone
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4192 Bump to next version 2.18.0.2
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4193 fix typo
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
Labels: community

#4196 Bump to next Version 2.18.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4194 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4191 RestServiceProvider: Add missing cases
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: chore

#4204 chore: update default CCL config to v1.0.0-rc.3
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
Labels: chore

#4202 Fix/11772 priority fallback string
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCUITextTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/ccl-text-descriptor-test-cases.json
Labels: bug

#4203 Fix/11706 show last risk calculation when rate limit is reached
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProviding.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderError13Tests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
Labels: bug

#4206 Fix/11734 wallet info improvements
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotificationsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/RoundedLabeledView/RoundedLabeledView.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: task

#4208 Story/11790 show ccl version
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/More/MoreActionItem/MoreActionItemView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeCCLService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfiguration+Fakes.swift
Labels: feature

#4209 Bump to next Version 2.18.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4190 Story/11692 update logic to support rapid PCR tests
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
Labels: task

#4214 unify days of installation calculation
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/ExposureNotificationSettingViewController.swift
Labels: bug

#4219 Fix/11834 date format
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/ccl-text-descriptor-test-cases.json
Labels: bug

#4220 Text change for 116117 phone number
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4221 Fix/11655 no responding error
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
Labels: bug

#4222 Fix/11839 wallet recalculation
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotificationsViewController.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4205 Task/11693 unit tests for rapid pcr tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/RapidTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
Labels: task

#4215 Story/11608 fault tolerant name handling/11683 grouping add case
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Utils/Array+Utils.swift
Labels: task

#4224 chore: update default CCL config to v1.0.0-rc.5
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
Labels: chore

#4213 Story/11356 support rapid pcr tests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/RapidTestQRCodeInformation.swift
  src/xcode/ENA/ENA/Source/Models/Submisstion/__tests_/RapidTestInformationTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/AntigenTestInformation+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/QRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
Labels: feature

#4227 Dismiss override notice after test rescan to show test result
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: bug

#4217 Task/11779 changes certificate overview screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_admission_state.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_admission_state.imageset/icon_admission_state.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/Overview/Cells/AddCheckinCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/OnBehalfCheckinSubmission/TraceLocationSelection/OnBehalfScanQRCodeCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Overview/Cells/AddTraceLocationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/ChangeAdmissionScenario/ChangeAdmissionScenarionCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/CreateCertificate/AddCertificateCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/OverviewLabelTableCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/AddCertificateCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/ChangeAdmissionScenarionCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Views/AddButtonAsTableViewCell/AddButtonAsTableViewCelling.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4223 Added texts for QR Code Scanner RAT Errors
  src/xcode/ENA/ENA/Source/Models/Submisstion/CoronaTestRegistrationInformation.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/Parser/CoronaTestsQRCodeParser.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/Model/QRCodeResult.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
Labels: bug

#4218 Feature/11733 admission scenarios list screen
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueTableViewCell.swift
Labels: task

#4231 Story/11353 adapt privacy policy release 2.19
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#4225 Story/11608 fault tolerant name handling/11696 deletion case
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertifiedPersonArray+Utils.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
Labels: task

#4230 Fix/11802 make failed certificates removable
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4240 Fix/remove 1 of 1 hint
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4241 Correct text for "Warnende Personen"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4235 Complete encodable implementation
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug

#4242 Typo new Functions " , oder"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4243 Feature/fix certificate comparison
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: task

#4248 chore: update default CCL config to v1.0.0-rc.7
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
Labels: chore

#4249 Protocol Buffer update for release 2.19.x at Sun Feb 20 16:46:33 UTC 2022
  proto/resources/internal/v2/dgc_parameters.proto
Labels: admin

#4234 Feature/11915 extract health certified person coordinator
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
Labels: chore, task

#4245 Fix/11935 readable error texts
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Types/ServiceError.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
Labels: bug

#4236 11876 implement overall flow
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/ChangeAdmissionScenario/ChangeAdmissionScenarionCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/ChangeAdmissionScenarionCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#4251 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
Labels: text-change

#4252 Text changes on certificate validation result
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4232 Story/11608 fault tolerant name handling/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/PreferredPerson/PreferredPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/HealthCertificateMigrator.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertifiedPersonArray+Utils.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertificate+BelongsToSamePersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/HealthCertifiedPersonTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Name+ExtensionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Resources/dcc-holder-comparison.json
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/__tests__/Resources/dcc-holder-name-components.json
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceMigrationTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Utils/Array+Utils.swift
  src/xcode/ENA/ENA/Source/Utils/Set+Utils.swift
Labels: feature, on hold

#4246 Feature/11898 flow with error
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceConsent/HealthCertifiedPersonReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceConsent/HealthCertifiedPersonReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceSucceeded/HealthCertifiedPersonReissuanceSucceededViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceSucceeded/HealthCertifiedPersonReissuanceSucceededViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4244 Feature/11733 admission scenarios list screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/DefaultDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/DataDonation/DataDonationViewModels/SettingsDataDonationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerActivityIndicatorView.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/Cell/SelectValueTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectValueViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/SelectableValue.swift
  src/xcode/ENA/ENA/Source/Scenes/SelectValueViewController/__tests__/SelectValueViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4255 Feature/11896 success screen
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Replace_Success.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Replace_Success.imageset/Replace_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_Replace_Success.imageset/Replace_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceSucceeded/HealthCertifiedPersonReissuanceSucceededViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceSucceeded/HealthCertifiedPersonReissuanceSucceededViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4262 Feature/12009 update protobuf
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_export.pb.swift
  src/xcode/gen/output/external/exposurenotification/temporary_exposure_key_signature_list.pb.swift
  src/xcode/gen/output/internal/app_config.pb.swift
  src/xcode/gen/output/internal/app_version_config.pb.swift
  src/xcode/gen/output/internal/attenuation_duration.pb.swift
  src/xcode/gen/output/internal/dgc/value_sets.pb.swift
  src/xcode/gen/output/internal/evreg/check_in.pb.swift
  src/xcode/gen/output/internal/evreg/signed_event.pb.swift
  src/xcode/gen/output/internal/ppdd/edus_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/els_otp_request_ios.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
  src/xcode/gen/output/internal/ppdd/ppa_data_request_ios.pb.swift
  src/xcode/gen/output/internal/pt/qr_code_poster_template.pb.swift
  src/xcode/gen/output/internal/pt/trace_location.pb.swift
  src/xcode/gen/output/internal/risk_score_parameters.pb.swift
  src/xcode/gen/output/internal/stats/key_figure_card.pb.swift
  src/xcode/gen/output/internal/stats/local_statistics.pb.swift
  src/xcode/gen/output/internal/submission_payload.pb.swift
  src/xcode/gen/output/internal/v2/app_config_ios.pb.swift
  src/xcode/gen/output/internal/v2/corona_test_parameters.pb.swift
  src/xcode/gen/output/internal/v2/dgc_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_edus_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_els_parameters.pb.swift
  src/xcode/gen/output/internal/v2/ppdd_ppa_parameters.pb.swift
  src/xcode/gen/output/internal/v2/presence_tracing_parameters.pb.swift
  src/xcode/gen/output/internal/v2/risk_calculation_parameters.pb.swift
Labels: task

#4261 PCR test details text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4258 Feature/11900 update models and schedule notification
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: task

#4254 Feature/refactor health certificate service
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/NotificationManagerTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/QRScannerViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Migration/__tests__/HealthCertificateMigratorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateService+GroupingAfterDeletionTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/ValidationStateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: chore

#4259 Feature/11784 UI test federal state configuration
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#4264 Feature/11897 add dev menu entry
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
Labels: task

#4266 Feature/11887 consent screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/DismissHandlingNavigationController/DismissHandlingNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionHeaderCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceConsent/HealthCertifiedPersonReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceSucceeded/HealthCertificateReissuanceSucceededViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceSucceeded/HealthCertificateReissuanceSucceededViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task

#4268 feature/12052-Adopt-tech-spec-change
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceSendModel.swift
Labels: task

#4265 Feature/11930 add missing texts
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/__tests__/DCCReissuanceResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/DismissHandlingNavigationController/DismissHandlingNavigationController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Cells/ExposureDetectionHeaderCell.xib
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceConsent/HealthCertifiedPersonReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/ReissuanceSucceeded/HealthCertifiedPersonReissuanceSucceededViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceSucceeded/HealthCertificateReissuanceSucceededViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceSucceeded/HealthCertificateReissuanceSucceededViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENATests/Helper/XCTestCase+HealthCertificate.swift
Labels: task
