Repository corona-warn-app/cwa-app-ios, pull requests merged in 2022-05, with the labels that each got.

#4499 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4500 Chang to plural form
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4501 Fix/12784 prevent double registration of keyboard notifications
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
Labels: bug

#4494 Feature/10307 risk calculation http client/10309 request available hours
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Client/ClientWifiOnly.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/Locator+AvailableDays.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/AvailableHoursResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/Locator+AvailableHours.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/__tests__/AvailableHoursTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: chore, task

#4503 Only update statistics on day change
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#4502 Feature/10297 httpclient key package download/10298 retry
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AllowList/AllowListResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AppConfiguration/AppConfigurationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/CCLConfigurationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/CCLConfigurationResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDTypeIndex/KIDTypeIndexResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/RegistrationToken/RegistrationTokenResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocument/ServiceIdentityDocumentResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ServiceIdentityDocumentValidationDecorator/ServiceIdentityDocumentValidationDecoratorResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TeleTan/TeleTanResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountries/ValidationOnboardedCountriesResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/GenericModels/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/__tests__/Resource+Fake.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/CachedRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Types/ServiceError.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Types/ServiceType.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RetryingTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestServiceError.swift
Labels: enhancement, feature

#4507 Fix/12982 set up UI only once
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: bug

#4504 Feature/10313 port request key submission
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/PlausibleDeniabilityService.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+PlausibeDeniabilityTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+SubmitTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/HTTPClient/LocatorsNotYetUsed/KeySubmission.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/KeySubmissionResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/KeySubmission/__tests__/KeySubmissionResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Types/ServiceError.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/FakeRequestService.swift
  src/xcode/ENA/ENA/Source/Services/FakeRequestService/__tests__/FakeRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENATests/Helper/RestServiceProviderFactory.swift
Labels: task

#4509 Remove health certificate requests on app reset
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
Labels: bug

#4505 Feature/10307 risk calculation http client/10310 request fetch hours
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/ClientWifiOnly.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClientTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHourResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHoursServiceHelper.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/Locator+DiagnosisKeys.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/__tests__/FetchHourTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/PackageDownloadReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/WifiOnlyRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: chore, task

#4497 Feature/10321 refactor test dcc requests
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DccRegisterPublicKeyTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+GetDigitalCovid19CertificateTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/DCCPublicKeyRegistrationError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/DCCPublicKeyRegistrationResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/DCCPublicKeyRegistrationSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/Locator+DCCPublicKeyRegistration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/__tests__/DCCPublicKeyRegistrationResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCPublicKeyRegistration/__tests__/Locator+DCCPublicKeyRegistrationTest.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/DigitalCovid19CertificateError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/DigitalCovid19CertificateReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/DigitalCovid19CertificateResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/DigitalCovid19CertificateSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/Locator+DigitalCovid19Certificate.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/__tests__/DigitalCovid19CertificateResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DigitalCovid19Certificate/__tests__/Locator+DigitalCovid19CertificateTest.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/DCCRSAKeyPair.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/__tests__/HealthCertificateOverviewViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/DCCErrors.swift
  src/xcode/ENA/ENA/Source/Services/DGCRegistration/Model/DCCResponse.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateServiceError.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateRequestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Revocation/__tests__/RevocationProviderTests.swift
Labels: chore

#4515 Text change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4511 Feature/10307 risk calculation http client/12989 request fetch hours retry update
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/FetchDayResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/FetchDaysServiceHelper.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/Locator+DiagnosisKeys.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/__tests_/FetchDayTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHourResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/__tests__/FetchHourTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/__tests__/HTTPClient+DaysAndHoursTests.swift
Labels: chore, task

#4517 Remove obsolete reload data that interferes with scrolling to top
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#4516 Adapted texts for tests for family members
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4519 Feature/10307 risk calculation http client/storybranch
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/ClientWifiOnly.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/WifiOnlyHTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+DaysAndHoursTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/WifiHTTPClientTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMDeveloperMenu.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSubmissionStateViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMWifiClient/DMWifiClientViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/AvailableDaysResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/Locator+AvailableDays.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableDays/__tests__/AvailableDaysResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/AvailableHoursResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/Locator+AvailableHours.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/AvailableHours/__tests__/AvailableHoursTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/FetchDayResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/FetchDaysServiceHelper.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/Locator+DiagnosisKeys.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/__tests_/FetchDayTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHourResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHoursServiceHelper.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/Locator+DiagnosisKeysHour.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/__tests__/FetchHourTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/__tests__/MetadataTests.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/PackageDownloadReceiveResource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/_Resource.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/WifiOnlyRestService.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/_RestServiceProviding.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/MockNetworkStack.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/__tests__/RestServiceProviderStub.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/URLSession+Convenience.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
Labels: chore

#4522 Corrected Genitiv
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4526 Bump to next Version 2.23.0.3
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4527 Changed "test result" to "test certificate"
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
Labels: text-change

#4524 Fix/13006 hide placeholder text
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeTestResultCellModelTests.swift
Labels: bug

#4523 Fix/12656 wrong wording for family member scans
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultFamilyMemberViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionTestResultFamilyMemberViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/AntigenExposureSubmissionNegativeTestResultHeaderView.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/ExposureSubmissionTestResultHeaderView.swift
Labels: bug

#4525 Feature/13067 update certlogic
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCUIText.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/TestData/dcc-validation-rules-common-test-cases.json
  src/xcode/ENA/ENA/Source/Services/Migration/SerialSecureCacheMigrator.swift
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
  src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/RuleValidation/CertLogic+Protocol.swift
Labels: chore

#4521 Feature/10307 risk calculation http client/10311 request trace warning package discovery
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDiscoveryTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/Locator+TraceWarningDiscovery.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/TraceWarningDiscoveryModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/TraceWarningDiscoveryResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/TraceWarningError.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/__tests__/HTTPClient+TraceWarningPackageDiscoveryTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/__tests__/TraceWarningDiscoveryResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarningDiscovery/__tests__/TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestRestorationHandlerTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/Model/TraceWarningDiscovery.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
Labels: chore, task

#4529 added new app string
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/Locator+CCLConfigurationTest.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#4530 updated text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
Labels: text-change

#4485 Feature/12922 12911 12913 changes reissuance screen and update network call and business logic
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/Locator+CCLConfiguration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/Locator+CCLConfigurationTest.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/__tests__/DCCReissuanceResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceError.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletCertificate.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateMapping.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateWebTokenHeader.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#4531 Story/12775 support reissuing of expired certificates
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/Locator+CCLConfiguration.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/__tests__/Locator+CCLConfigurationTest.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/ccl-configuration.bin
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/DCCReissuanceSendModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCReissuance/__tests__/DCCReissuanceResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceError.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletCertificate.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateMapping.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificateWebTokenHeader.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4532 Changed test result > test certificate
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#4534 Feature/13096 support old wallet versions + update notifications
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
Labels: task

#4528 Feature/10307 risk calculation http client/12849 request trace warning package download
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Client/Client.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient+Configuration.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/HTTPClient.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+ConfigurationTests.swift
  src/xcode/ENA/ENA/Source/Client/HTTP Client/__tests__/HTTPClient+TraceWarningPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Client/__tests__/Mocks/ClientMock.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/FetchDayResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchDay/__tests_/FetchDayTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/FetchHour/FetchHourResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Discovery/Locator+TraceWarningDiscovery.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Discovery/TraceWarningDiscoveryModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Discovery/TraceWarningDiscoveryResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Discovery/__tests__/TraceWarningDiscoveryResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Discovery/__tests__/TraceWarningDiscoveryTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Download/Location+TraceWarningDownload.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Download/TraceWarningDownloadResource.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Download/__tests__/TraceWarningDownloadResourceTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Download/__tests__/TraceWarningDownloadTests.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Shared/PackageDownloadResponse.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/TraceWarning/Shared/TraceWarningError.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Resource/ReceiveResources/PackageDownloadReceiveResource.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/__tests__/ExposureDetectionTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/KeyPackageDownload/KeyPackageDownload.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/DayKeyPackageDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/HourKeyPackagesDownloadTests.swift
  src/xcode/ENA/ENA/Source/Services/TraceWarningDownload/TraceWarningPackageDownload.swift
Labels: chore, task

#4533 Feature/13092 logic and UI accompanying certificates
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/AccompanyingCertificates/AccompanyingCertificatesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/AccompanyingCertificates/AccompanyingCertificatesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4540 Story/13015 show accompanying certificates when reissuing
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/AccompanyingCertificates/AccompanyingCertificatesViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/AccompanyingCertificates/AccompanyingCertificatesViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#4541 Bump to next Version 2.23.0.5
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4537 added texts for 2.23 new features screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: text-change

#4542 Corrected typos and time frame
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
Labels: text-change

#4543 Changes to "About the app" text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4535 Fix/12957 risk level change
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Risk.swift
  src/xcode/ENA/ENA/Source/Services/Risk/__tests__/RiskTests.swift
Labels: bug

#4544 Change debug menu entry to delete only downloaded data.
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventStoring.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/MockEventStore.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Queries/TraceTimeIntervalMatch/DeleteAllTraceTimeIntervalMatchQuery.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/__tests__/EventStoreTests.swift
Labels: feature

#4545 Fix/4206 scroll view keyboard keep input in focus
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/TextFieldManager.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/AddAndEditEntry/__tests__/TextFieldsManagerTests.swift
Labels: chore

#4547 UITest and screenshot for Accompanying Certificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/AccompanyingCertificates/AccompanyingCertificatesViewController.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService+UITestingMethods.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_20_CertificateReissuance.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: task

#4551 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4552 Fix/13117 about to expire text change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
Labels: text-change

#4555 Bump to next Version 2.23.0.6
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4548 Fix/13007 flaky screen shot
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/ValidationOnboardedCountries/ValidationOnboardedCountriesReceiveModel.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Service/RestServiceProvider.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/Country.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/CountryTests.swift
Labels: chore

#4553 Changed last bullet point on reissuance consent screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4520 Update dcc wallet info for revoked or unrevoked certificates.
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#4560 Fix/13134 missing UI element
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeTestResultTableViewCell.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: chore

#4559 set today as a minimal date for selection
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/ValidationDateSelectionCell.swift
Labels: bug

#4562 Fix/13003 reset accessibility identifiers
  src/xcode/ENA/ENA/Source/Scenes/Settings/Reset/ResetViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
Labels: chore

#4558 Remove estimated row height to prevent overscrolling
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#4563 Addition to note about soon expiring certificates
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
Labels: text-change

#4549 use dispatch group to handle multiple completions
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/HealthCertificateReissuanceCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/__tests__/HealthCertificateReissuanceConsentViewModelTests.swift
Labels: bug

#4554 Make the root progress behave gracefully.
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetection.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
Labels: bug

#4565 add RAT Profiles screenshots
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/TestPlans/Screenshots.xctestplan
Labels: bug

#4568 Bump to next Version 2.23.0.7
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: admin

#4567 Fix/13066 issues with expired test
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/TestResult.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/TestResultTests.swift
Labels: bug

#4571 fix version number
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
Labels: bug

#4569 update certLogic to latest release
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/HealthCertificateToolkit/Package.swift
Labels: bug

#4566 Fix/13129 reissuance gradient color
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertificateCellViewModelTests.swift
Labels: bug

#4572 Feature/13140 drop expiration notifications
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: feature

#4576 Fix/11894 link leichte sprache
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: chore

#4573 added a long version
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/HealthCertifiedPersonCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore, text-change

#4582 better reset label before reuse
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/SimpleTextCell.swift
Labels: bug

#4583 Reset recycle bin publisher on store wipe
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
Labels: bug

#4585 change reissue text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
Labels: text-change

#4580 added missing icon and text
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Group.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Group.imageset/Icons_Group.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Group.imageset/Icons_Group_Dark.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Info/TraceLocationsInfoViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, text-change

#4575 Add new property to track test result change to invalid.
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/__tests__/FamilyMemberCoronaTestCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberAntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberPCRTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberAntigenTest+Mock.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberPCRTest+Mock.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: bug

#4578 added logic to scroll date picker cell in focus if keyboard appears
  src/xcode/ENA/ENA/Source/Scenes/Containers/TopBottomContainerViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewController.swift
Labels: bug

#4581 Fix/9680 certificate headlines
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/__tests__/HealthCertificateViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4590 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4592 Improve Whats New Text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4579 Fix crazy tableview bouncing
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestsViewController.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
Labels: bug

#4584 Fix/9816 tabbar items low contrast
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Certificates.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Certificates.imageset/Icons_Tabbar_Certificates.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Certificates.imageset/Zertificate_black.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Check-in_black.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Checkin.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Diary.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Diary.imageset/Diary_black.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Home.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_Home.imageset/Status_black.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_UniversalScanner.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_UniversalScanner.imageset/Icons_Tabbar_UniversalScanner.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Common/Icons_Tabbar_UniversalScanner.imageset/Scanner_black.pdf
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: accessibility

#4588 Fix/11498 request tan call button
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionHotlineViewController.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: accessibility

#4596 9471: Developer Menu: Download Booster Rules: Closeable
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterChoosePersonViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMBoosterRules/DMBoosterRulesViewModel.swift
Labels: bug

#4597 Trigger notification for decreased risk.
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#4598 Don't fail risk caculation on failed trace warning download.
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
Labels: bug

#4601 Rework text of expired certificates
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/__tests__/HealthCertificateQRCodeCellViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4600 11491: Set the accessibility order of input fields to match VoiceOver…
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
Labels: bug
