Repository corona-warn-app/cwa-app-ios, pull requests merged in 2023-02, with the labels that each got.

#5029 Feature/14606 adjust info screen features for release 3.1
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/new_feature_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_NewVersion_Features.imageset/new_feature_light.pdf
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: feature

#5028 Fix/14647: SRS Warning - No Check-ins ENDED - only running Check-ins --> Empty "Check-ins teilen?" screen appears
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#5034 Update Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#5033 Fix/14690 14680 various app clousure notice bugs
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01b_Statistics.swift
Labels: bug

#5025 Fix/10452: Recycle Bin - Missing Test-certificate connection if test was deleted before certificate arrived
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/UserAntigenTest.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/UserPCRTest.swift
Labels: bug

#5035 Fix/14681 EOL "more" arrow has wrong placement
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeTableViewCell.xib
Labels: bug

#5032 Persist only the Latest updated CCL version
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMServerEnvironmentViewController.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceBoosterNotificationRulesTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLServiceInvalidationRulesTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#5037 New Feature Screen not appearing after app update
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeatures.swift
Labels: bug

#5038 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.stringsdict
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.stringsdict
Labels: text-change

#5036 Fix/14647: SRS-Warning: Running and completed checkins.
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#5041 Move the current version outside the #if block
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: chore

#5039 Fix/14692 wrong values submittedWithCheckIns
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService+Protocol.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
Labels: bug

#5040 Fix/14682 EOL - Detail screen has no close functionality
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#5043 Fix/14707 App crashes after change date
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#5045 Fix/14576 Wrong error text for min time since onboarding
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSPreconditionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: bug

#5046 Fix/14640 ccl caching issue
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMCCLConfiguration/DMCCLConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMCCLConfiguration/DMCCLConfigurationViewModel.swift
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/CCLConfiguration/CCLConfigurationResource.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: bug

#5049 Fix/14576 Wrong error text for MIN_TIME_SINCE_ONBOARDING
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: bug

#5047 Fix/10829 Duration Picker Auto Scroll
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
Labels: bug

#5050 Fix/8882 Screen changes without user input during onboarding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#4994 Fix/11222 remove badge count from redeemed tests
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionCoordinatorTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerCoordinator.swift
Labels: bug

#5051 Task/14811: Preparation - global variable
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
Labels: task

#5056 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-issue

#5057 Fix/14576 Wrong error text for MIN_TIME_SINCE_ONBOARDING
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: bug

#5053 Task/14812 Preparation Dev menu support to change the date
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/DMViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Helper/DMMenuItem.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#5059 Task/14815 adapt changes to TabBar
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: task

#5055 Task/14824 new thank you tile on home screen
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/EndOfLifeThankYouIllustration.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/EndOfLifeThankYouIllustration.imageset/EndOfLifeThankYouIllustration.pdf
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/Utils/LaunchArguments.swift
Labels: task

#5062 Task/14814 14816 adapt changes home screen app info
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewControllerTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/More/HomeMoreInfoTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCardView/HomeLinkCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeLinkCardView/HomeLinkCardView.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
Labels: task
