Repository corona-warn-app/cwa-app-ios, pull requests merged in 2023-03, with the labels that each got.

#5052 Fix/14764 app closure details subheading text alignment
  src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/AppClosureNoticeDetailsViewModel.swift
Labels: bug

#5067 Fix: DMDatePickerTableViewCell trailing space for UIDatePicker.
  src/xcode/ENA/ENA/Source/Developer Menu/Features/ConfigureAbleCells/CellsAndViewModels/DatePicker/DMDatePickerTableViewCell.swift
Labels: bug

#5065 Task/14823 adapt changes to error logging
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/MockCWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/Model/ELSError.swift
  src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
Labels: task

#5058 Task/14817 adapt changes to certificates
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
Labels: task

#5070 Task/14889 Dev Menu: make it possible to select also a time to the hibernation start date
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewModel.swift
Labels: task

#5054 Task/14813 adapt changes onboarding
  src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/__tests__/OTPAuthorizationForSRSResourceTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingPageType.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSErrorTests.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITests_00_Onboarding.swift
Labels: task

#5069 Task/14887 Disable ENF when app starts and change hibernation start to 01.05.2023
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
  src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/ActionTableViewCell.swift
Labels: task

#5071 Task/14890 update thank you text
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
Labels: task

#5066 Task/14821 Adapt changes to QR code scanning and deep links
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/RouteTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/__tests__/TraceLocationTests.swift
Labels: task

#5061 Task/14819 adapt changes to background tasks
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Models/Task Scheduling/ENATaskScheduler.swift
  src/xcode/ENA/ENA/Source/Protocols/RequiresAppDependencies.swift
Labels: task

#5073 Text change for end of life thank you screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: task, text-change

#5075 Task/14896 Update the description text for `EndOfLifeThankYouCell`
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: task

#5076 Fix/13784: Replace Redeemed the days in the Text from 21 days to 2 days.
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#5077 Fix/14900 dev menu hibernation not working properly
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#5085 Fix/14909 CWA 3.2.0 (3) is unusable for Testing
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/__tests__/CWAHibernationProviderTests.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMHibernation/DMHibernationOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
  src/xcode/ENA/ENAUITests/Onboarding/ENAUITests_00_Onboarding.swift
Labels: bug

#5086 Fix/14908 EOL - TabBar unchanged after EOL and without AppRestart
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/RootCoordinator.swift
Labels: bug

#5080 Fix/14905 EOL - Vielen Dank area - spacing issues
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.xib
Labels: bug

#5079 Fix/14904 EOL - "Mehr" area has unnecessary line / space in the end
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/More/HomeMoreInfoTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/More/MoreActionItem/MoreActionItemView.swift
Labels: bug

#5083 Fix/14901 EOL - RampDown notice ("PostIt") still visible
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
Labels: bug

#5081 Fix/14903 EOL - Vielen Dank in Dark mode has wrong pic
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/EndOfLifeThankYouIllustration.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/EndOfLifeThankYouIllustration.imageset/EndOfLifeThankYouIllustration-dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/EndOfLifeThankYouIllustration.imageset/EndOfLifeThankYouIllustration-light.pdf
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Views/HomeCardView.swift
Labels: bug

#5084 Fix/14907 EOL - AppLauncher "Eintrag hinzufügen" does not open the actual day if "Tagebuch" is not selected
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
Labels: bug

#5094 update text for thank you screen
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#5097 add missing bullet text point for RAT tests
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#5098 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#5060 Task/14818 adapt changes to notifications
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/CWAHibernationProvider.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/NotificationManager.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNotifications/DMNotificationsViewModel.swift
  src/xcode/ENA/ENA/Source/Extensions/UNNotificationCenter+Extension.swift
  src/xcode/ENA/ENA/Source/Extensions/UNUserNotificationCenter+WarnOthers.swift
  src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/WarnOthersReminderTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/CoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/__tests__/FamilyMemberCoronaTestServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/DeadmanNotificationManager.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/UserNotificationCenter.swift
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/__tests__/Mocks/MockUserNotificationCenter.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/ExposureSubmissionServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateNotificationService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/__tests__/HealthCertificateServiceTests.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: task

#5072 Fix/14865: "Back" button doesn't change color when switching to light mode
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInformation/AntigenTestProfileInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewViewController.swift
Labels: bug

#5096 Update homescreen when app becomes active
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
Labels: bug

#5093 Fix/14911 EOL - Overview still visible after EOL and without AppRestart (Info Icon)
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#5100 Fix/14543 Positive test without warning: text on the testresult (homescreen) differs between iOS and Android/FIGMA
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/HomeShownPositiveTestResultCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestResult/__tests__/HomeShownPositiveTestResultCellModelTest.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#5099 Task/14946 EOL - Certificate Status Calculation
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
Labels: task

#5095 Fix/14948 EOL - "Zertifikate" still shows a red badget and "Es gibt Neuigkeiten zu Ihren Zertifikaten"
  src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/CheckinTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/FamilyMemberCoronaTests/FamilyMemberCoronaTestTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateQRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificatesTabCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/AdmissionState/AdmissionStateTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/BoosterNotification/BoosterNotificationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/CertificateReissuance/CertificateReissuanceTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/Cells/HealthCertificate/HealthCertificateCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
Labels: bug

#5091 Task/14945 EOL - Cert-Toggler
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
Labels: task

#5102 Fix/14966 EOL "PostIt" - Dark Mode - wrong font color
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/App Closure Notice Colors/ENA App Closure Text Subtitle Color.colorset/Contents.json
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeTableViewCell.xib
Labels: bug

#5103 hide tests from recycle bin
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/RecycleBinViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/RecycleBin/__tests__/RecycleBinViewModelTest.swift
Labels: bug

#5106 Fix/14963 EOL - App Information > Impressum is clickable but nothing happens
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewControllerTests.swift
Labels: bug

#5109 Feature/14956 Adapt privacy notice for Release 3.2
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: feature, text-change

#5108 hide booster notification tile
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/__tests__/HealthCertifiedPersonViewModelTests.swift
Labels: bug

#5113 Fix/14965 EOL - Notification for Universal scanner shown after onboarding
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#5114 Fix privacy policy notice
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: text-change

#5110 Fix/14973 EOL - App still tries to update the hidden local statistics
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeState.swift
  src/xcode/ENA/ENA/Source/Services/LocalStatistics/LocalStatisticsProvider.swift
Labels: bug

#5115 Fix/14968 Reminder to share Keys is shown after Ramp Down
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5118 Fix/14953 EOL - contact journal - add person / add location missing save button
  src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateCoordinator.swift
Labels: bug

#5117 Fix/14983 New link in Data Privacy text is is not clickable
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug

#5116 Fix/14981 EOL - Blocked Vaccination and Recovery Certificates stay in Stautus BLOCKED after RampDown
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#5120 Fix/14334 location based revoked certificates have a cov pass check note
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeView.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/HealthCertificateQRCodeViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Views/__tests__/HealthCertificateQRCodeViewTests.swift
Labels: bug

#5122 Fix/14992 deadman notification still comes when eol is already reached
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5123 Fix/14993: EOL - About to expire/Expired Certificates loose this info in EOL
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#5131 Fix/14981 Blocked Vaccination and Recovery Certificates stay in Status BLOCKED after RampDown
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#5126 remove test certificates in hibernation
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5130 Fix/15002 EOL - Thank you screen - FAQ Text + Link missing in all languages except DE
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: bug, text-change

#5127 Fix/14996 EOL - all statistics remain visible if app is running in background when EOL is reached
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
Labels: bug

#5128 Fix/14968 Reminder to share Keys is shown after Ramp Down
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5125 Removing about section from app information
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewControllerTests.swift
Labels: bug

#5136 Fix/14997 eol most revelevant dcc only re calculated after additional app background
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift
Labels: bug
