Repository corona-warn-app/cwa-app-ios, pull requests merged in 2023-01, with the labels that each got.

#4967 Fix/8882: Screen changes without user input during onboarding
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
Labels: bug

#4973 Fix/14480: Wrong text in SRS dialog "Andere warnen nicht möglich" for error MIN_TIME_SINCE_ONBOARDING
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSPreconditionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
Labels: bug

#4975 Fix/14526: SRS Consent Screen - Legal Text box - Issues in all languages except DE
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/CountrySelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellPickerSelectionPreventableMock.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSPreconditionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Utils/InternetConnectivityMonitor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#4976 Revert last commit
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/Cells/CountrySelectionCell.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/HealthCertificateValidationViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellPickerSelectionPreventableMock.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Validation/__tests__/CountrySelectionCellTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/OnboardingInfoViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/QRScanner/QRScannerViewModel.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSPreconditionErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertificate.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Utils/InternetConnectivityMonitor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: chore

#4977 Fix/en tr legal remove google
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#4978 Fix/14495: Multiple submission entries in the contact diary (3.0)
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSPreconditionError.swift
Labels: bug

#4980 fix/13928 Wrong Button text if Background App Refresh is off
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug

#4966 Fix/10829 Duration Picker broken layout
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
Labels: bug

#4979 Fix/14481 Remove alert prefix "Fehlercode"
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#4983 Fix/revert wrong profiles
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
Labels: bug

#4971 Bump copyright year in README.md
  README.md
Labels: mirrored-to-jira

#4986 Fix/14525: SRS - Some text elements have no font resize behaviour
  src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewBulletPointCell.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/SRSConsentViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/SRSConsent/__tests__/SRSConsentViewModelTests.swift
  src/xcode/ENA/ENA/Source/Views/ExposureSubmission/DynamicLegalExtendedCell.swift
Labels: bug

#4987 Protocol Buffer update for release 3.1.x at Tue Jan 10 14:30:05 UTC 2023
  proto/resources/internal/ppdd/ppa_data.proto
Labels: chore

#4988 Protocol Buffer update for release 3.1.x at Tue Jan 10 14:52:23 UTC 2023
  proto/resources/internal/ppdd/ppa_data.proto
Labels: chore

#4989 Chore/update protobuf swift files
  src/xcode/gen/output/internal/ppdd/ppa_data.pb.swift
Labels: chore

#4992 Translation Delivery
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/uk.lproj/Localizable.strings
Labels: text-change

#4993 Fix/14319 certificate details ui issue
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
Labels: bug

#4995 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-change

#4991 Fix/6511 Nothing happens when you check-in at an event
  src/xcode/ENA/ENA/Source/Scenes/Events/Store/Model/TraceLocation.swift
Labels: bug

#4996 Fix/14423: Create a QR-Code: UI issue in darkmode/whitemode
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.xib
Labels: bug

#4999 Fix/14548: DSE privacy notes issues
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug, text-change

#4972 Fix/14416 Bad-behavior-of-CWA-when-WLAN-has-no-connection
  src/xcode/ENA/ENA/Source/HTTPClientCore/URLSessionConfiguration+Default.swift
Labels: bug

#5000 Fix/14552 skip popup bold text
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
Labels: bug

#5003 Fix/14577 first srs submission leads to api token already issued
  src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACService.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
  src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
Labels: bug

#4985 Feature/14153 extend ppa for warning with selftest
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/KeySubmissionMetadata.swift
  src/xcode/ENA/ENA/Source/Models/Metadata/Key Submission Metadata/__tests__/KeySubmissionMetadataTests.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/SubmissionTestType.swift
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/ExposureSubmissionService.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPADataType.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/Model/PPAnalyticsData.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAAnalyticsSubmissionCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/PPAnalyticsCollector.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/Mocks/TestDummyPPAnalyticsDataImplementation.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsCollector/__tests__/PPAnalyticsCollectorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
  src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
Labels: feature

#5001 Fix/14412 Contact Diary Warn others entry UI issue
  src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/Cells/DiaryOverviewDayTableViewCell.swift
Labels: bug

#5005 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-issue

#5009 Update Localizable.legal.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.legal.strings
Labels: text-issue

#5013 Wrong error text for MIN_TIME_SINCE_ONBOARDING
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinatorModel.swift
Labels: bug

#5018 Fix/9623: Statistic cards - local 7 day incidence is empty when you turn WLAN off
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Manage Statistics/ManageStatisticsCardView.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Services/OTP/Model/OTPError.swift
  src/xcode/ENA/ENA/Source/Utils/InternetConnectivityMonitor.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#5014 Fix/7295 Overlapping text while creating Rapid Test Profile
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/AntigenTestProfileInputViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileInput/Cells/AntigenTestProfileInputCell.swift
Labels: bug

#5017 Fix/14622: Dev Menu - SRS Options - Date - hh:mm:ss
  src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSOptionsViewModel.swift
Labels: bug

#5015 SPM: Update latest package versions
  src/xcode/ENA.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: admin

#5019 Fix/14578 no internet prevents clicking on srs
  src/xcode/ENA/ENA/Source/Services/Risk/Provider/Helper/CachedAppConfiguration.swift
Labels: bug

#5016 Fix/14303: Add accessibility id for TestProfiles Texts Labels
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/AntigenTestProfileViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/QRCodeCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/SimpleTextCell.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfile/Cells/SimpleTextCellViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileOverview/AntigenTestProfileOverviewEmptyStateViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/HomeTestRegistrationTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/TestRegistration/__tests__/HomeTestRegistrationCellModelTests.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/AntigenTestProfile/ENAUITests_12_AntigenTestProfile.swift
  src/xcode/ENA/ENAUITests/AppDelegate/ENAUITests_11_QuickActions.swift
  src/xcode/ENA/ENAUITests/AppStore/ENAUITests.swift
  src/xcode/ENA/ENAUITests/DeltaOnboarding/ENAUITests_06_DeltaOnboarding.swift
  src/xcode/ENA/ENAUITests/ExposureSubmission/ENAUITests_04a_ExposureSubmission.swift
  src/xcode/ENA/ENAUITests/FamilyMember/ENAUITests_21_FamilyMember.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: bug

#5021 Fix/14548: Update BG / RO / PL version of privacy notes.
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
Labels: bug, text-change

#5020 Adjust info screen to announce new Release-Features for 3.1
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/NewVersionFeatures/DeltaOnboardingNewVersionFeaturesViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature

#5026 Chore/ dev menu PPA SRS
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSRSPrechecks/DMSRSOptionsViewController.swift
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMSRSPrechecks/DMSRSOptionsViewModel.swift
  src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
Labels: chore

#5027 Fix/14648: Add second pin to certificate pinning
  src/xcode/ENA/ENA/Resources/Environment/Environments.default.json
  src/xcode/ENA/ENA/Source/Developer Menu/Features/DMNewHttpCommunication/DMNHCViewModel.swift
  src/xcode/ENA/ENA/Source/Environment/Environments.swift
  src/xcode/ENA/ENA/Source/Environment/__tests__/TestEnvironments.json
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/EvaluateTrust/DefaultTrustEvaluation.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/URLSessionDelegates/CoronaWarnURLSessionDelegate.swift
  src/xcode/ENA/ENA/Source/HTTPClientCore/Security/__tests__/HTTPClientCertificatePinningTests.swift
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Reissuance/ReissuanceConsent/HealthCertificateReissuanceConsentViewModel.swift
Labels: bug

#5023 Story/14557 configurable status tab notice
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AppClosure_Notice.imageset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AppClosure_Notice.imageset/Illu_Betriebsende_dark.pdf
  src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets/Illustrations/Illu_AppClosure_Notice.imageset/Illu_Betriebsende_light.pdf
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/App Closure Notice Colors/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/App Closure Notice Colors/ENA App Closure Notice Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Certificate-PDF Blue.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Miscellaneous Colors/ENA Chevron Dark Color.colorset/Contents.json
  src/xcode/ENA/ENA/Resources/Assets/ena-colors.xcassets/Text Colors/ENA Text Primary 2 Contrast Color.colorset/Contents.json
  src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/AppClosureNoticeDetailsViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/AppClosureNoticeDetailsViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/__tests__/AppClosureNoticeDetailsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/__tests__/HomeAppClosureNoticeCellModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/__tests__/HomeTableViewModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/DCCWalletInfo.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/GetWalletInfoInput.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificateValidation/__tests__/FakeCCLService.swift
  src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
  src/xcode/ENA/ENAUITests/Home/ENAUITests_01a_Home.swift
Labels: task

#5022 Fix/14566 SRS Warn others offline - error message unclear
  src/xcode/ENA/ENA.xcodeproj/project.pbxproj
  src/xcode/ENA/ENA/Source/Services/Exposure Submission/__tests__/SRSErrorTests.swift
  src/xcode/ENA/ENA/Source/Services/PPAccessControl/Model/SRSError.swift
Labels: bug
