Repository corona-warn-app/cwa-app-ios, pull requests merged in 2023-04, with the labels that each got.

#5135 Fix/15005 Status tab app closure notice arrow is not aligned correctly
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/HomeAppClosureNoticeTableViewCell.xib
Labels: bug

#5140 Fix/14992 EOL - Remove notifications syncronously
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5139 Fix/14996 EOL - all statistics remain visible if app is running in background when EOL is reached
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsTableViewCell.xib
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/__tests__/SAP_Internal_Stats_LinkCard+Mock.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug, text-change

#5141 EOL - Show "About the App" in the App Informations again.
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewController.swift
  src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationViewControllerTests.swift
Labels: bug

#5142 EOL - Certificate Overview: don't show the certificate scanning info text, when hibernation is given.
  src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
Labels: bug

#5143 Fix/14997 EOL-Most-Revelevant-DCC-only-re-calculated-after-additional-app-background
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
Labels: bug

#5144 House keeping for PRs
  src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCellModel.swift
Labels: chore

#5145 Fix/14992 deadman notification still comes when eol is already reached
  src/xcode/ENA/ENA/Source/Services/DeadmanNotification/DeadmanNotificationManager.swift
Labels: bug

#5146 Fix/9769 Community build with MockENManager cannot disable Exposure detection
  src/xcode/ENA/ENA/Source/Models/Exposure/MockExposureManager.swift
Labels: bug

#5147 Fix/10545 Corrupted layout in QR code creation screen on iPhone SE first generation
  src/xcode/ENA/ENA/Source/Scenes/Events/TraceLocations/Configuration/TraceLocationConfigurationViewController.swift
Labels: bug

#5149 15010-EOL-Installation-Pandemie-Radar-Link-does-not-work
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: bug

#5150 Feature/15014 EOL - Update text on EOL card
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/Localizable.links.strings
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
  src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
Labels: feature, text-change

#5152 small text change
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: text-change

#5151 15011-False-Frame-Color-for-INVALID-and-REVOKED-Certificates-after-RampDown
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#5155 Fix/15012 Data Privacy Issues
  src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
  src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
Labels: bug, text-change

#5154 Thank You: Change in german: "external link" to "externer Link".
  src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Labels: bug, text-change

#5157 14949-EOL-test-result-and-test-certificate-still-updated-after-ramp-down
  src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
  src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
Labels: bug

#5156 EOL-14954-offline-onboarding-shows-popup-for-risk-calculation
  src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
Labels: bug

#5158 Fix/15011 False Frame Color for INVALID and REVOKED Certificates after RampDown
  src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
  src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
Labels: bug

#5160 Chore/fix screenshots
  src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/__tests__/AppClosureNoticeDetailsViewModelTests.swift
  src/xcode/ENA/ENA/Source/Scenes/Home/Cells/AppClosureNotice/__tests__/HomeAppClosureNoticeCellModelTests.swift
  src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
Labels: chore
